### ISSUE TITLE
Add information tag component

### ISSUE THREAD

**Issue by shanaka-rajitha** [h2oai/wave#1005]
# Features

- Display wide card with multiple columns of information.
- Card should take full width of the page container or section included.
- Display alert badges (un-clickable)

Design URL for specs : https://xd.adobe.com/view/809c4f44-9861-4f57-978a-e2d3515a426e-d5cf/screen/7fc2c20f-f278-4779-82e9-0f061f6e6f2f/

## Wide card layout
<img width="1350" alt="Wide card layout" src="https://user-images.githubusercontent.com/12246331/133742054-8f572f10-67c9-430c-a29e-c86b6a91ab2f.png">

**Comment by mturoci** [comment]
@shanaka-rajitha as discussed on Slack, this card is implementable as a form_card. The only feature missing is leftmost badges, please edit the issue accordingly.

**Comment by shanaka-rajitha** [comment]
Hi @mturoci the alert badges are different to the existing information badges. By default we will have information badges and alert badges. The alert badges stand prominence over the other sections and information badges as the purpose served is different. There will be instances we will have both alert and information badges on the same information row.

**Comment by mturoci** [comment]
https://github.com/h2oai/wave/issues/1006#issuecomment-922829712

**Comment by shanaka-rajitha** [comment]
The following component will be developed as part of form_card and coloured badges will have size variations mainly small and large.

**Comment by mturoci** [comment]
Implementation notes: Create a new form component with the same API as `ui.tag` with minor style differences (listed in comments).

**Comment by aalencar** [comment]
Should we call the component alert badge or information tag?

**Comment by mturoci** [comment]
Let's go with an `information tag` to be consistent. We have no component named badge yet. Tip: `make generate` lists all the existing types so can be beneficial when thinking about naming.
