### ISSUE TITLE
Messages  ( Toast without close button )

### ISSUE THREAD

**Issue by sandruparo** [h2oai/wave#1048]
https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/8e728e9a-cab7-42cd-8dc4-061a3ca65235/

**Comment by sandruparo** [comment]
![image](https://user-images.githubusercontent.com/9942408/136232007-aaa0cc80-90e2-4faa-9d4e-3063d3eb0d06.png)

**Comment by sandruparo** [comment]
@mturoci  can you help us creating this too in sdk ?

**Comment by mturoci** [comment]
@sandruparo is this intended to be a rewamp of our existing `ui.message_bar` or is it related to #1007 ? If the latter, please include it within corresponding issue and close this one.
