### ISSUE TITLE
Manual input to spinbox partly broken

### ISSUE THREAD

**Issue by psinger** [h2oai/wave#1051]
#### Wave SDK Version, OS

Wave 0.18, Ubuntu 18

#### Actual behavior

When trying to manually input data into a `spinbox`, I can observe unexpected behavior:

https://user-images.githubusercontent.com/1677826/136384964-72ba518f-c4ee-4c0a-bd13-94524c07dcdf.mp4

In this example, I want to manually enter `0.01`. A common procedure is to delete everything, and add the value manually.
So in this case, I delete the current value, and try to input the new value. However, it does not allow to enter the decimal value.
At that point it breaks.

#### Expected behavior

Spinbox should allow to properly provide manual input.

cc @goldentom42

**Comment by psinger** [comment]
@aalencar @mturoci 
Is this fixed? In 0.9 I still see this problem, but it might not have made that release.

**Comment by lo5** [comment]
@psinger The fix was applied after the v0.19 release; will be available in v0.20
