### ISSUE TITLE
Add tooltips support for Tables

### ISSUE THREAD

**Issue by MartinBarus** [h2oai/wave#1096]
When we want to show a table (imagine loaded csv file) and some of the columns contain long texts, we cannot see the full text, but we would like to be able to see the text in the toolbox when hovering over the table column entry.

It works out of the box in Safari, I am attaching  and example:

<img width="530" alt="Screenshot 2021-10-29 at 13 21 07" src="https://user-images.githubusercontent.com/6991522/139426585-489b1379-6611-4814-8a68-cca8a16bae19.png">

Talking to @mturoci it seems the fact it renders nicely in Safari is a coincidence due to Safari handling of some property. It would be great if this worked in any browser.

**Comment by mturoci** [comment]
Implemented as part of #515, available in 0.21
