### ISSUE TITLE
wide_info_card

### ISSUE THREAD

**Issue by 5675sp** [h2oai/wave#1114]
#### Wave SDK Version, OS

Wave 0.19.0

#### Actual behavior

According to the wave documentation we can use markdown for the **caption** parameter when using a **wide_info_card**. The following is stated in the documentation: 

**The card's caption, displayed below the subtitle, supports markdown.**

But when render I see the following: 

![Screen Shot 2021-11-06 at 9 37 01 AM](https://user-images.githubusercontent.com/64230238/140617043-a12bba56-7010-41b3-80d3-36d6276a09fb.png)

This is my code: 

    return ui.wide_info_card(
        name="value_proposition_card",
        box="body_right_bottom_1",
        title="Value Proposition",
        caption="**hello**",
        icon="Trophy",
        category="mAB",
    )

#### Expected behavior

Have the caption parameter support markdown.

**Comment by lo5** [comment]
Thanks for reporting. 

Fixed via https://github.com/h2oai/wave/commit/926ceebeb8234e8c62e45eebf7e8452a4acb30f6

Will be available in the next release.

**Comment by 5675sp** [comment]
@lo5 I am wondering if during the next version it will be possible to make the **wide_info_card** non-clickable? I am just trying to use the **wide_info_card** to display information and not have the user click on it. Is this possible? Thanks.

**Comment by mturoci** [comment]
> I guess one option is to disable clicking if the name is '', consistent with other components.

Agree, this should be fine. 

Currently, the only way how to not make the whole card clickable is to specify the `label`, but then you have to handle the button click.

**Comment by 5675sp** [comment]
@lo5 I changed the **name** value to `''`, but the card is still clickable:

     return ui.wide_info_card(
        name='',
        box="body_right_bottom_2_ROW_1",
        title="Monoclonal Antibody",
        caption=f"{content}",
        icon="CircleRing",
        category="mAB",
    )

**Comment by mturoci** [comment]
@5675sp it is just a proposal, not implemented yet. Maybe in the next release.

**Comment by 5675sp** [comment]
Are there any current solutions? Or managing each click is the only option for now?

**Comment by mturoci** [comment]
No current solutions, you just need to manage the clicks for now.

In order to prevent infinite loading, you can use this hacky snippet:
```py
q.page['non-existent'].items = [] # Call on every render.
```

However, the cursor will still be a pointer, indicating clickability - can be handled via custom CSS, but probably not worth it.

**Comment by 5675sp** [comment]
Thank you, looking forward to the next release.

**Comment by mturoci** [comment]
Tracked [here](https://github.com/h2oai/wave/issues/1117).
