### ISSUE TITLE
Add popup attribute to dropdown to force popup dialog

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#1116]
Add `popup: bool` to `ui.dropdown()`, default to `false`. If set to `true`, then always display the popup picker regardless of the number of items.

Via https://github.com/h2oai/wave/discussions/1100#discussioncomment-1588518

cc @dipplestix

**Comment by lo5** [comment]
Another option is to use an enum with values `Auto` (current behavior), `Always` (always display popup), and `Never` (never display popup).

**Comment by mturoci** [comment]
I suggest going with the second option as it is more robust.

**Comment by dipplestix** [comment]
Agree on preference for option 2
