### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1118]
#### Is your feature request related to a problem? Please describe

Wave currently supports only header where title, subtitle, and menu can be specified. However, some apps may want to use side nav menu only, but still keep the branding.

#### Describe the solution you'd like

Allow people to use a layout like:
![image](https://user-images.githubusercontent.com/64769322/141092811-85313675-c2d1-4da5-aa9d-4ffc3d1c8194.png)
![image](https://user-images.githubusercontent.com/64769322/141092995-c6a566a9-e30e-4c12-8b7c-467bf2860674.png)

#### Proposed API

There are 2 options, either go with a new `ui.side_nav` card or enhance the existing `ui.nav` card.

```ts
/** Create a card containing a navigation pane. */
export interface State {
  /** The navigation groups contained in this pane. */
  items: NavGroup[]
  /** The name of the active (highlighted) navigation item. */
  value?: S
  /** Items that should be displayed at the bottom of the card. */
  secondary_items?: Component[]
  /** The card's title. */
  title?: S
  /** The card's subtitle. */
  subtitle?: S
  /** The logo displayed at the top. **/
  image?: S
  /** The user avatar displayed at the top. Mutually exclusive with image, title and subtitle. **/
  persona?: Component
  /** Card background color. Defaults to 'card'. */
  color?: 'card' | 'primary
}
```
Extending the existing card makes probably more sense to me, wdyt @lo5?

**Comment by lo5** [comment]
- `title` could be mandatory
- Maybe add `icon` and `icon_color` in addition to `image` so that it's consistent with the new header. 
- Can also order the members similar to the header.

**Comment by mturoci** [comment]
> title could be mandatory.

This would be a breaking change.

>Maybe add icon and icon_color in addition to the image so that it's consistent with the new header card.

Will do.

>Can also order the members to match the header card.

Will try, but it's not 100% possible due to `items` being mandatory, thus needing to be specified as first.

**Comment by lo5** [comment]
OK. Then maybe follow this ordering:

`items, value, title, subtitle, icon, icon_color, image, persona, secondary_items, color`
