### ISSUE TITLE
Allow repositioning of meta.dialog

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#1148]
#### Is your feature request related to a problem? Please describe

The default position of **ui.dialog** can feel off (too low) depending on the layout of the content in the background.

#### Describe the solution you'd like

I would like to have the option to reposition the  **ui.dialog** on the screen. Either relative to the browser screen, relative to the drawn content or by incorporating it somhow in the layout system.

#### Describe alternatives you've considered

CSS, e.g.
```css
.ms-Dialog-main {
  position: fixed;
  top: 225px;
}
```

**Comment by lo5** [comment]
> The default position of ui.dialog can feel off (too low)

Is the dialog not vertically centered in your app? That might be a bug.

**Comment by Far0n** [comment]
It seems vertically centered in the browers. That works most of the time just fine, but somtimes I would like it to move a bit up:

Here, I would like it have it a bit more towards the top:
![grafik](https://user-images.githubusercontent.com/6949295/145090563-f34d4338-ed90-43b3-9a68-0405f075e9c9.png)

That's fine I guess:
![grafik](https://user-images.githubusercontent.com/6949295/145090715-04d7707e-88d6-4dc4-821f-bb14d7214182.png)

**Comment by mturoci** [comment]
>I would like it have it a bit more towards the top:

Hey @Far0n what's the reason for ^^ in comparison to centering? (if this feature request is still valid)

**Comment by Far0n** [comment]
@mturoci I can easily look a bit off (imho) if center of mass of the app's cards is significantly above the screen center:
![grafik](https://user-images.githubusercontent.com/6949295/184869126-3ce032a8-18ae-4074-8f1a-72d9dec0d69d.png)

I like this better:
![grafik](https://user-images.githubusercontent.com/6949295/184869387-936f5991-0556-420f-8f30-9d896742caad.png)

**Comment by mturoci** [comment]
This seems like a color contrast problem rather than a need for alignment.

**Comment by Far0n** [comment]
idk, for me dialogs just too far down:
![grafik](https://user-images.githubusercontent.com/6949295/184870027-91cd67f0-c013-4ed8-b49a-c27fe17d1dd4.png)

**Comment by Far0n** [comment]
would be nice to allow it to place here:
![grafik](https://user-images.githubusercontent.com/6949295/184870180-c16d05ce-d82d-4a02-a5bf-b98c59de57c0.png)

**Comment by Far0n** [comment]
kk, let's close this here then?

**Comment by mturoci** [comment]
Agree.
