### ISSUE TITLE
Cannot find available options for the `icon` attribute in cards

### ISSUE THREAD

**Issue by rasika** [h2oai/wave#1156]
#### Is your feature request related to a problem? Please describe
When creating various type of cards often there's a parameter for `icon` which accepts a string text. But developers cannot find any reference on the available options/names for the icons.

```
ui.stat("User", q.user.user.name, icon='contact'),
```

#### Describe the solution you'd like

With some offline discussions I could find that WAVE is supporting fonts available in https://uifabricicons.azurewebsites.net/.
Better if we can provide this link in WAVE docs for developer reference.

#### Describe alternatives you've considered

May be we can also introduce an `enum`  instead of `string` for icon. But since we don't have control over the transformation of the text into icons, better solution would be a link to https://uifabricicons.azurewebsites.net/ on the docs in relevant places.

**Comment by mturoci** [comment]
Thanks @rasika! Agree. This is already handled by the upcoming docs update in the next release. In addition to that, the Pycharm plugin we will release together with `0.20.0` will provide you with autocomplete for all the `icon` attributes so the whole dev experience should be much smoother.

**Comment by rasika** [comment]
Awesome, thanks for the update @mturoci. Any link for the fix?

rel: Pycharm plugin, where can I find Pycharm plugin code? Any ETA on `0.20.0` ?

**Comment by mturoci** [comment]
> Any link for the fix?

https://github.com/h2oai/wave/tree/master/website/components

> where can I find Pycharm plugin code?

https://github.com/h2oai/wave/tree/master/tools/intellij-plugin

> Any ETA on 0.20.0

Once https://github.com/h2oai/wave/issues/59 is resolved.

**Comment by rasika** [comment]
Thanks found it https://github.com/h2oai/wave/search?q=https%3A%2F%2Fuifabricicons.azurewebsites.net%2F
