### ISSUE TITLE
Rework Tutorials to be ML or Data focused

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1173]
#### Is your feature request related to a problem? Please describe
The H2O Wave end user has primarily been Data Scientists. Our current 1-5 tutorials help you get started writing scripts and apps, but they do not help you get started building AI Apps. Our goal would be to replace Hello World, Beer Wall, System Monitor, Bean Counter, and Todo list with a similar level of examples but which are data and ML focused. 

#### Describe the solution you'd like
1. Hello World
   * Keep as is
2. Beer Wall
   * replace with "Realtime Predictions"
   * Use the same for loop along with `np.random` to generate a binary classification prediction from 0 to 1 
   * Text says something like `the {i}th prediction is {prediction}` 
3. System Monitoring 
   * replace with "Visualizing Realtime Predictions"
   * Use the stats cards to visualize the prediction over time and show the current value
   * In general using the data buffer could be super important for the predictions side of ML use cases, so this would be a nice time show that
4. Bean Counter
   * replace with `Input and Predictions` (needs better name)
   * add a text box and slider from 0 to 10
   * When the user clicks the button, the inputs are sent to a "model" function which takes the length of the string plus the slider value and returns "This is long" or "This is short" depending on if the sum of these values is greater than 15 or not (this is a silly example but it's close enough to taking data and running it though and h2o-3 or Scikit learn model that I think DS folks will get how to use it on their own data. 
   * Print the value below the button
   * We can still learn about user and app level realtime sync, all predictions can get printed permanately somewhere for "sharing"
5. Todo List
   * Keep as is
6. Confusion Matrix (before "new bean counter")
   * Create fake binary classification predictions: Real is 0 or 1 and Prediction is between 0 and 1
   * Use the sklearn CM function to get the confusion matrix
   * Have a slider with a trigger where we change the threshold and it changes the the confusion matrix accordingly 
7. Visualizing Data (before Todo List)
   * Use a classic public dataset, probably titanic or iris
   * Have a drop down list of column names
   * When you select one, show a histogram (numeric) or barchart (categorical) of values using native wave plots

#### Describe alternatives you've considered

Add these rather than replacing the originals

**Comment by lo5** [comment]
Both the beer wall and bean counter examples use a simple increment `i += 1` to illustrate concepts.

The proposal makes those examples more complicated, alienating Python developers who are not familiar with numpy, models, predictions, confusion matrices, etc.

Rather than conflating the existing tutorials with ML/DS concepts, it might be better to add more pre-built apps or templates to https://github.com/h2oai/wave-apps and move the contents to this repo and/or include them in the main docs.

**Comment by mtanco** [comment]
Closing with plans to release seperate, new intro to Wave for Data Science tutorials
