### ISSUE TITLE
Wave app arguments lose state when multiple selections are made

### ISSUE THREAD

**Issue by debugaftercoffee** [h2oai/wave#1177]
#### Wave SDK Version, OS

Wave SDK and runtime: 0.19.0, OS: Mac OS and Linux

#### Actual behavior

We recently updated Wave 0.19.0 and now one of my apps is not behaving correctly. I have a basic page where a user checks permissions they need and selects a expiration date from a date picker. Once at least one permission has been checked and the date selected, the app will show an “Edit Permissions” button so the user can implement their change. What happens is the user will check a permission, and the app gets the name of the permission selected through the arguments. When they select the expiration date, the app receives the date as an argument, but the framework does not return the checkboxes that was previously selected. The checkbox remains selected, so the check is not lost on the page. Below is an example of the UI.

![UI](https://user-images.githubusercontent.com/65924811/148568847-e89a207d-1414-4d25-985f-e08091979f3f.png)

#### Expected behavior

In previous releases of Wave the app would remember the state of the past selections, so in the example after the user selected a date and checked a box the arguments would return the date and the list of checked items. 

#### Steps To Reproduce
Below is code that will reproduce the issue. 

1. Run the app and check a permission. On the console it will log the arguments from the app and and show permissions selected.
2. Select a date from the Date picker and the console will show just the date selected in the arguments and you will not see the checkboxes that were previously selected.

```python
from h2o_wave import Q, main, app, ui

import logging
logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level='INFO')

READ_PERMISSION_NAME = 'Read'
WRITE_PERMISSION_NAME = 'Write'
DELETE_PERMISSION_NAME = 'Delete'
LIST_PERMISSION_NAME = 'List'

async def make_permissions_card(q):
    logging.info("Making permissions card")
    q.page['permissions'] = ui.form_card(
        box='6 3 5 10',
        title='Permissions',
        items=[
            ui.label("Select Permissions", visible=True),
            ui.checklist(
                name="permissions_checklist",
                label="Permissions",
                choices=[ui.choice(name=x, label=x) for x in
                         [READ_PERMISSION_NAME, WRITE_PERMISSION_NAME, DELETE_PERMISSION_NAME, LIST_PERMISSION_NAME]],
                trigger=True,
                visible=True
            ),
            ui.date_picker(
                name="permissions_date_picker",
                label="Expiration Date",
                trigger=True,
                visible=True
            ),
            ui.button(
                name='permissions_button',
                label='Edit Permissions',
                disabled=True,
                primary=True
            ),
        ])


async def client_initialize(q: Q):
    if not q.client.initialized:
        await make_permissions_card(q)
        q.client.initialized = True


@app('/')
async def serve(q: Q):
    await client_initialize(q)

    logging.info(f"Served - {q.args}")

    # save off the user selections for next refresh
    q.page['permissions'].items[1].dropdown.value = q.args.permissions_checklist
    q.page['permissions'].items[2].date_picker.value = q.args.permissions_date_picker

    if q.args.permissions_checklist and q.args.permissions_date_picker:
        q.page['permissions'].items[3].button.disabled = False
    else:
        q.page['permissions'].items[3].button.disabled = True

    await q.page.save()
```

**Comment by mturoci** [comment]
Thanks for the issue @debugaftercoffee!

The code you posted unfortunately relied on a [bug](https://github.com/h2oai/wave/issues/150) that was fixed in newer releases.

## Solution

The correct working code should be (check the `serve` function):

```py
from h2o_wave import Q, main, app, ui

import logging
logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level='INFO')

READ_PERMISSION_NAME = 'Read'
WRITE_PERMISSION_NAME = 'Write'
DELETE_PERMISSION_NAME = 'Delete'
LIST_PERMISSION_NAME = 'List'

async def make_permissions_card(q):
    logging.info("Making permissions card")
    q.page['permissions'] = ui.form_card(
        box='1 1 5 10',
        title='Permissions',
        items=[
            ui.label("Select Permissions", visible=True),
            ui.checklist(
                name="permissions_checklist",
                label="Permissions",
                choices=[ui.choice(name=x, label=x) for x in
                         [READ_PERMISSION_NAME, WRITE_PERMISSION_NAME, DELETE_PERMISSION_NAME, LIST_PERMISSION_NAME]],
                trigger=True,
                visible=True
            ),
            ui.date_picker(
                name="permissions_date_picker",
                label="Expiration Date",
                trigger=True,
                visible=True
            ),
            ui.button(
                name='permissions_button',
                label='Edit Permissions',
                disabled=True,
                primary=True
            ),
        ])


async def client_initialize(q: Q):
    if not q.client.initialized:
        await make_permissions_card(q)
        q.client.initialized = True


@app('/')
async def serve(q: Q):
    await client_initialize(q)

    logging.info(f"Served - {q.args}")

    # No longer needed, the selections should now remain in UI automatically.
    # save off the user selections for next refresh
    # q.page['permissions'].items[1].dropdown.value = q.args.permissions_checklist
    # q.page['permissions'].items[2].date_picker.value = q.args.permissions_date_picker

    # Store user selections to q.client to be accessible between multiple renders (serve function calls).
    if q.args.permissions_checklist is not None:
        q.client.permissions_checklist = q.args.permissions_checklist
    if q.args.permissions_date_picker is not None:
        q.client.permissions_date_picker = q.args.permissions_date_picker

    if q.client.permissions_checklist and q.client.permissions_date_picker:
        q.page['permissions'].items[3].button.disabled = False
    else:
        q.page['permissions'].items[3].button.disabled = True

    await q.page.save()

```

## Explanation

`q.args` is populated based on all the "dirty" form inputs per current render (serve function call). This means if you had a simple, non-trigger, checklist, datepicker and a submit button, clicking the button would submit (call serve function) both the values at once and clear the `q.args` as preparation for the next iteration.

However, in case of `trigger`, the form is submitted on every change (whenever checklist is checked or date selected) and `q.args` are cleared as preparation for the next iteration. So what happens is:

* Check a checklist item.
* Submit dirty items (only checklist) as `q.args` to server.
* Clear `q.args`.
* Select date.
* Submit dirty items (only datepicker) as `q.args` to server.
* Clear `q.args`.

**Comment by debugaftercoffee** [comment]
@mturoci thank you for the detailed explanation and the updated code.
