### ISSUE TITLE
UI Table not fully displaying

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1185]
#### Wave SDK Version, OS
Wave 0.19.0 on OS X, safari and chrome

#### Actual behavior
You'll notice there is no bottom line in both tables, you have to scroll on the table to see the end of the table. For the table on the left, one data row is under the scroll as well. 
![image](https://user-images.githubusercontent.com/4793561/149184305-d4b16b15-9f8d-4ca7-bf9b-12d99ce4d85d.png)

#### Expected behavior
If we are not explicit about the height and there is space, we would expect the full table to show on the screen.

#### Steps To Reproduce

```python
from h2o_wave import Q, main, app, ui

cities = ['Toronto', 'Ottawa', 'Montreal', 'New York', 'Los Angeles', 'Toronto', 'Ottawa', 'Montreal', 'New York', 'Los Angeles']


@app('/demo')
async def serve(q: Q):

    q.page['no_filter'] = ui.form_card(box='1 1 4 10', items=[
        ui.table(
            name='no_filter',
            columns=[
                ui.table_column(name="title", label="City", min_width="400px", link=True),
            ],
            rows=[ui.table_row(name=a, cells=[a]) for a in cities],
            multiple=True,
        ),
    ])
    q.page['filter'] = ui.form_card(box='5 1 4 10', items=[
        ui.table(
            name='filter',
            columns=[
                ui.table_column(name="title", label="City", min_width="400px", link=True),
            ],
            rows=[ui.table_row(name=a, cells=[a]) for a in cities[0:4]],
            multiple=True,
        ),
    ])


    await q.page.save()
```

**Comment by mturoci** [comment]
Thanks for the report @mtanco! This seems to be already fixed in the current master:

![image](https://user-images.githubusercontent.com/64769322/149296883-bd82dedb-a166-4539-94d6-c4c97b9720ff.png)

Can you please verify using the nightly?

**Comment by mtanco** [comment]
Ah, much better, thanks!!
