### ISSUE TITLE
Add Release to S3 as part of the Release Pipeline

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1202]
#### Is your feature request related to a problem? Please describe
Not all organizations are allowed to use GitHub, meaning they cannot download H2O Wave to their workstations. We have manually added H2O Wave 0.19.0 to s3 and created a landing page here: 

https://h2o-wave.s3.us-east-1.amazonaws.com/releases/index.html
<img width="869" alt="image" src="https://user-images.githubusercontent.com/4793561/150411947-db755b7f-0f15-4fb4-baf8-25c089459c17.png">

#### Describe the solution you'd like
- [ ] Add the process of releases going to s3 to part of the release pipeline
- [ ] In s3, move this release from the `releases` folder to a 0.19.0 folder
- [ ] Add an index at `releases` that shows all available releases as links and takes you to that page's index
- [ ] Automate / parameterize the index file for each release 
- [ ] Change the PyPi and Conda links from the general H2O_Wave URL to version specific ones 
- [ ] Optionally: backfill previous releases (I'm not sure this is worth the time) 

#### Describe alternatives you've considered
Manually add releases to s3 - this would need to be assigned to someone

**Comment by mturoci** [comment]
https://h2o-wave.s3.amazonaws.com/releases/index.html

@mtanco @lo5 I went for a more flat structure (instead of putting every release into its own folder) - basically very similar to what GH does. Also Both Anaconda and Pypi have their own mechanisms for browsing various versions so having a general link to these repos is fine.

Please let me know what you think about ^^.

**Comment by mtanco** [comment]
Can we move the documentation above the links? My only concern with the flat structure is that in a few releases the docs will be hidden.

Looks great otherwise!!

**Comment by mturoci** [comment]
@mtanco see [this PR](https://github.com/h2oai/wave/pull/1241) on the idea of how it looks, the one in this issue is out of date already. Also, there is one question for you in the PR.
