### ISSUE TITLE
Box plot Component

### ISSUE THREAD

**Issue by shihan007** [h2oai/wave#1215]
![Screenshot 2022-02-01 at 10 52 06](https://user-images.githubusercontent.com/38729017/151916947-31c6d915-f1f6-40d1-a309-1de876623d37.png)
![Screenshot 2022-01-31 at 18 45 07](https://user-images.githubusercontent.com/38729017/151916953-b49ae43a-aac6-46a0-8082-42a19da447b0.png)

For model monitoring we need to have a box plot in order to show prediction value over time. Currently this component not available in wave. ( Column chart display in the bottom of the chart is a nice to have feature.) 

Outliers display as dots.
Need to have a tooltip feature for each time frame
User should be able to look at different time scales by drag and zoom in and out the graph
For multiple models tooltip have a different structure( refer image)

design link:- https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/60aebbe8-1cbf-4628-821f-344af82ef8ee/

cc: @shereezhang @iamabhishekmathur

**Comment by shihan007** [comment]
![Screenshot 2022-01-31 at 18 45 07](https://user-images.githubusercontent.com/38729017/151915956-4c0771fa-c01c-40f8-9ff1-659b5facd62b.png)

For model monitoring we need to have a box plot in order to show prediction value over time. Currently this component not available in wave. ( Column chart display in the bottom of the chart is a nice to have feature.) 

Outliers display as dots.

design link:- https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/60aebbe8-1cbf-4628-821f-344af82ef8ee/

cc: @shereezhang @iamabhishekmathur

**Comment by lo5** [comment]
Examples: 
- https://github.com/h2oai/wave/blob/master/py/examples/plot_schema.py
- https://github.com/h2oai/wave/blob/master/py/examples/plot_schema_transpose.py

**Comment by mtanco** [comment]
Thank you @lo5 ! 
I think this implementation does not have the outlier support: https://g2.antv.vision/en/examples/box/box#with-error is that something we can do too?
