### ISSUE TITLE
New Header component

### ISSUE THREAD

**Issue by shihan007** [h2oai/wave#1227]
![Screenshot 2022-02-02 at 09 38 43](https://user-images.githubusercontent.com/38729017/152091719-ee155feb-b220-46cf-8cfe-573954d9c61e.png)
 
design link - https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/f4b9e6c7-6c86-445d-a598-fb37bcda5115/

App name have use the primary color.
Hamburger icon can be enable or disable for the header. (optional feature to toggle side nav)
Notification icon to handle notifications within the app
Profile name and image of the user.
Profile dropdown with common items ( ex:- profile, settings, logout etc..)
Header with menu item placed for special cases.

**Comment by mturoci** [comment]
All of this is already possible, see https://wave.h2o.ai/docs/widgets/content/header/. The only point that is not satisfied is primary color for title which was not implemented for 2 reasons:

* It's not a link so no point in being primary colored
* The proposed design doesn't count with existing subtitle.
