### ISSUE TITLE
Provide a way to get fresh access tokens even "in request"

### ISSUE THREAD

**Issue by zoido** [h2oai/wave#1230]
#### Is your feature request related to a problem? Please describe

Access token are usually short-lived. In order or minutes but even sub minute time to live is possible.
App can use `access_token` property of available `h2o_wave.Q.auth`. This token seems to guaranteed to be fresh on the invocation of the handler but can expire during the handling when the handling takes longer the the token's TTL. This can happen when (e.g.) remote service takes too long to respond or big data are being process within the handler.

`h2o_wave.Q.auth` exposes also `refresh_token` but no means for using it for obtaining a new access token.

#### Describe the solution you'd like

Extend `Auth` class in the so that the `access_token` is fact `@property` that ensures that the access token is fresh even withing the request handling. 

Or...

provide the callable that ensures the same.

Or...

provide the callable that forces the refresh of the access token.

#### Describe alternatives you've considered

Exposing OIDC client details so that the app can do the `refresh_token` exchange by its own.

This would expose client secret to the app and that's not desirable.

#### Additional context

N/A

**Comment by lo5** [comment]
@zoido - What's the token TTL set to in HAIC? 

> This can happen when (e.g.) remote service takes too long to respond or big data are being process within the handler.

If I understand correctly, the specific scenario you're describing is:
- app accepts request with valid token
- app backgrounds a long running process
- by the time the background operation completes, the token is no longer valid.

Is that correct?
