### ISSUE TITLE
Create or kill a named task

### ISSUE THREAD

**Issue by Nayananga** [h2oai/wave#1243]
#### Is your feature request related to a problem? Please describe

Currently, I cannot create or kill a named task using `q.run` or `q.exec`. So if I want to run an infinite loop task in the background, I have no control over it unless the task brake the loop by itself.

#### Describe the solution you'd like

Give an API to create and kill a task by name.

#### Describe alternatives you've considered

[To create a named task](https://docs.python.org/3/library/asyncio-task.html#creating-tasks)

[To kill a named task](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel)

**Comment by mturoci** [comment]
`q.run` and `q.exec` are simple wrappers for blocking functions and executing them in the background. If want to use Python tasks yourself, there is nothing stopping you from doing so. The feature you are requesting is not going to be implemented on Wave level (as it's not really wave-related).

I suggest reading [this blog post](https://medium.com/@unusualcode/background-jobs-in-wave-or-how-not-to-kill-your-ui-ae1fed95693a) that shows various ways of accomplishing what you need.
