### ISSUE TITLE
Table column filter is not opened when clicking on filter icon

### ISSUE THREAD

**Issue by marek-mihok** [h2oai/wave#1261]
#### Wave SDK Version, OS

Latest version in master; Chrome, Firefox, Safari

#### Actual behavior

Table column filter does not open when clicking on filter (chevron down) icon. It opens when clicking under the column title or on the place between title and chevron down icon. Please, see the example below:

https://user-images.githubusercontent.com/23740173/155089013-93426290-5e9a-4eed-b08e-6ab70123d9fa.mov

#### Expected behavior

Table column filter opens when clicking on chevron down filter icon next to the column title.

#### Steps To Reproduce

1. Open the table example from `py/examples/table`
2. Click on the Status column filter

**Comment by mturoci** [comment]
Closed in #1283
