### ISSUE TITLE
Support for boxplots

### ISSUE THREAD

**Issue by DrRadan** [h2oai/wave#1264]
#### Description

Wave plots to support boxplots for data vizualisations

#### Alternatives

Use boxplots from other libraries

#### Additional context

![image](https://user-images.githubusercontent.com/7996773/155604016-29358773-f47b-4b61-a5e1-1d7ac250574e.png)

@sandruparo

**Comment by lo5** [comment]
Duplicate of https://github.com/h2oai/wave/issues/1215
Will ship with v0.21.

**Comment by DrRadan** [comment]
The latestt UX for Gene Mutation AI requires this component (closed in #1215).  Is there a release date for it?

**Comment by mturoci** [comment]
@DrRadan this is available since `0.21`.
