### ISSUE TITLE
Pop-up sidebar for uploads

### ISSUE THREAD

**Issue by DrRadan** [h2oai/wave#1265]
#### Description

Enable a  pop-up side bar element that can appear upon demand when the user wants to upload (a) data or (b) models. It could have the characteristics of a _transient_ page, so as to allow a variety of ui elements within it.

#### Describe the solution you'd like

- (When needed for the app workflow) The user should have the ability to bring up the pop-up side bar. 
- The data and model can be selected via (a) drag-and-drop (b) file system (c) connectors
- Additional elements, such as a toggle switch etc , should be allowed.
- Once the data are selected the pop-up closes

#### Alternatives
To achieve this now we need to over-complicate the UI, adding all the elements as constant part of the page. These elements are there throughout the session, even after the upload has been completed or is not needed in the session. This takes up real-estate too.

#### Example
![image](https://user-images.githubusercontent.com/7996773/155607282-c4721514-6e8a-4f5c-9894-4119a0b30280.png)

![image](https://user-images.githubusercontent.com/7996773/155607157-a2ec27a1-9b88-4011-9aa0-75cada6106c2.png)

**Comment by lo5** [comment]
There's a modal side-panel available already. 
https://wave.h2o.ai/docs/examples/meta-side-panel
Does that meet your needs?
