### ISSUE TITLE
Customizations to plots

### ISSUE THREAD

**Issue by DrRadan** [h2oai/wave#1266]
#### Description

Enable customization to plots such as defining transparency, fill color, line color etc.

![image](https://user-images.githubusercontent.com/7996773/155612958-48791d67-02ac-4adb-937a-806187cadb83.png)

**Comment by lo5** [comment]
The plotting library already supports customizing fill/stroke color/opacity/line-dash for both marks and guides (reference lines).
See https://wave.h2o.ai/docs/api/ui#mark

For example, `ui.mark(..., fill_color='#ff0000', fill_opacity=0.5, ...)`.
Or shorter: `ui.mark(..., fill_color='rgba(255,0,0,0.5)', ...)`. 

There are no plans to support shadows or gradients. Ref [chartjunk](https://en.wikipedia.org/wiki/Chartjunk).
