### ISSUE TITLE
More precise definition of -oidc-skip-login

### ISSUE THREAD

**Issue by johannes-becker-otto** [h2oai/wave#1272]
Hello,

I am not sure if -oidc-skip-login
a) ignores the login
b) skips the step where I would need to push a "Log In using OpenID Connect" button

Maybe that could be added to https://wave.h2o.ai/docs/security ?

All the best
Hannes

**Comment by lo5** [comment]
@johannes-becker-otto - Thanks for pointing out. Fixed docs.

`-oidc-skip-login` skips the built-in *Log In using OpenID Connect* form.

**Comment by johannes-becker-otto** [comment]
Hi @lo5 
thanks! So I understand it as simply skipping the form - but you still need to have the correct user roles and such, right?
(It might just be me not really knowing how OIDC works...)
All the best
Hannes
