### ISSUE TITLE
Add an option that users can override min and/or max values of sliders

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/wave#1273]
#### Is your feature request related to a problem? Please describe

I like the Slider as a very user friendly and visually appealing input format. In most cases it makes sense to force the input into a fixed range of min and max value, but in some cases those min and max values may rather be a suggestion to the user and the user should be able to override that suggestion. There is currently no way to allow a user override for min and max values for H2O wave sliders. 

#### Describe the solution you'd like

I am proposing two ways that users can interact with a slider and select values outside of the proposed range. Activating this option should of course be a developer choice. In the image below at the top, the current slider is shown. 
Option 1 (middle): If the slider is moved to one end, suggest the user to type in another value by showing a box and a curser next to the current value.
Option 2 (bottom): If the slider is moved to one end, let an arrow appear, that extends the min or max values by a factor or absolute number that can be specified by the developer. 

#### Describe alternatives you've considered

One alternative would be to use another type of input which is less visually appealing. 

#### Additional context

![image](https://user-images.githubusercontent.com/1069138/156151587-5de6c15f-1e05-432c-af4b-8e44af10880d.png)

**Comment by mturoci** [comment]
Hi @pascal-pfeiffer. Can you provide some real-world usage examples of such sliders? As far as I am aware, sliders shall be used when an approximate value from a predefined range is needed.

If you want to collect an arbitrary value, you can use a regular `ui.textbox` with a tooltip containing recommendations.

**Comment by lo5** [comment]
@pascal-pfeiffer A spinbox might be a good alternative to textboxes for numeric inputs: https://wave.h2o.ai/docs/widgets/form/spinbox
