### ISSUE TITLE
bug: ui.dialog closable option is not working properly

### ISSUE THREAD

**Issue by dulajra** [h2oai/wave#1277]
#### Wave SDK Version, OS

0.19.0

#### Actual behavior

`X` button is visible and active when

```
closable=False
blocking=True
```

<img width="637" alt="Screenshot 2022-03-03 at 12 46 46" src="https://user-images.githubusercontent.com/12434380/156515396-deb2a04e-7efc-4bad-9824-c89d459b677e.png">

#### Expected behavior

`X` button should not be visible and the user shouldn't be able to close the dialog when `closable` option is set to `False`

**Comment by marek-mihok** [comment]
Thanks for your report, @dulajra! It should be fixed in v0.20.0, therefore I am closing this issue. If the problem persists there, please reopen this issue.
