### ISSUE TITLE
Grouped by rows are not sortable

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1287]
#### Steps To Reproduce

1. Run `examples.table`
2. Group by Issue
3. Sort by Issue
4. Try to expand groups - you should see no data rows there.

It would be good to also think about what's the best UX when sorting rows during group by. There are 2 options:

* Keep groups in the order they are displayed and sort rows only within the context of a particular group.
* Sort rows in the context of rows (whole table), thus groups will be rearranged on sort.

**Comment by marek-mihok** [comment]
I would go with the first option. There are several reasons from different perspectives: 
- The purpose of sort is to make order in data to make it more clear to read for user. In general, there will be fewer groups than rows (that's the purpose of groups - to group rows that have something in common into fewer units). The conclusion here is that we can bring more order by sorting rows.
- User is used to sort rows based on sortable columns when using the non-grouped table. It would be confusing to sort groups when table is grouped. And should clicking on any of the sortable column header's sort icon perform the same action - to sort groups? And what about filter? Would it filter rows inside the groups even when sort icon does not sort rows inside the group? It would be very confusing. The only reasonable solution would be to have separate headers with sort/filter support for whole table and for each of the groups separately what would make table too robust.

What do you think @mturoci ?
