### ISSUE TITLE
Improve docs string for dialog events

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1294]
#### Is your feature request related to a problem? Please describe
The current docs string for the ui.dialog events parameter is `events – The events to capture on this dialog`. However, there is a specific list of events that can be captured but this isn't documented making it hard for the user to know how to use this feature.

#### Describe the solution you'd like
Change the description to `events – The events to capture on this dialog. One of 'dismissed'.`

to match other descriptions like `ui.zone(direction)`:
"direction – Layout direction. One of 'row', 'column'. See enum h2o_wave.ui.ZoneDirection."

#### Notes
* Sidepanel and notification bar might also be related?

**Comment by mturoci** [comment]
Apply the same for side panel as well.
