### ISSUE TITLE
Navigate to specific card within a page

### ISSUE THREAD

**Issue by ranjithh** [h2oai/wave#1304]
As part of Gene Mutation AI app, we show the cancer risk predictions and model explanations in a page, one below the other. Since there are a lot of items in the results it would be nice to have a navigation bar that helps navigate user to specific card within the results page. Currently, upon clicking an item in the navigation bar takes us to a new page, instead the feature request is that upon clicking an item in nav bar, it should mimic the scroll & take to the exact card. 

![image](https://user-images.githubusercontent.com/10229032/159706582-29dcb831-8ec1-4800-b510-3ccffae561c5.png)

Also would be great if the vice versa is possible  too - upon scrolling the list of cards, the selection in the navigation bar changes automatically. ?

**Comment by aalencar** [comment]
Agreed with @ranjithh to close the issue because the use case is too specific and required too many changes on Wave codebase.
