### ISSUE TITLE
Text of all items in the Header Card to match Title

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1307]
#### Wave SDK Version, OS
Wave 0.20.0

#### Actual behavior
It seems that items don't know they're "in the header" and have the default color for labels which makes them hard to read
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/4793561/159809772-101b80e4-79d1-4963-9a5a-e30f262907d4.png">

**Comment by mturoci** [comment]
Good catch @mtanco!
