### ISSUE TITLE
Make it easier to open the wave app from terminal

### ISSUE THREAD

**Issue by codeananda** [h2oai/wave#1319]
I'm following [your tutorial](https://h2o.ai/blog/setting-up-your-local-machine-for-h2o-ai-cloud-wave-app-development/) on making your first wave app. It tells me that I can open my app at localhost:10101/demo which is true.

But when I run `$ wave run app.py` there is nothing in the output telling me to go to the above web address. Indeed, I would have no idea how to open the app unless I looked at your tutorial! Adding in a link I can click to open my app would be very helpful.

`$ wave run app.py` output
```
2022/04/01 13:00:18 # 
2022/04/01 13:00:18 # ┌────────────────┐ H2O Wave 
2022/04/01 13:00:18 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.20.0 20220131055923
2022/04/01 13:00:18 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
2022/04/01 13:00:18 # └────────────────┘
2022/04/01 13:00:18 # 
2022/04/01 13:00:18 # {"address":":10101","base-url":"/","t":"listen","web-dir":"/Users/king/opt/anaconda3/envs/h2o_wave/www"}
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12612] using statreload
INFO:     Started server process [12615]
INFO:     Waiting for application startup.
2022/04/01 13:00:19 # {"host":"http://127.0.0.1:8000","route":"/demo","t":"app_add"}
INFO:     Application startup complete.
```

Add something like 

```
CLICK HERE TO OPEN YOUR APP: http://localhost:10101/demo
```

would make the user experience a million times better.

**Comment by mtanco** [comment]
To take this a step further, the user's default browser could be opened in the link similar to Juypter Notebooks

**Comment by codeananda** [comment]
> To take this a step further, the user's default browser could be opened in the link similar to Juypter Notebooks

Yes! This is a much slicker solution!

**Comment by huangxin168** [comment]
Dash have this feature like[  localhost:10101/demo](url) displayed in the console, very convinient.

**Comment by zillionare** [comment]
how can let uvicorn listen on 0.0.0.0? My wave is launched on a remote machine, that I can't access it by http://127.0.0.1:8000.

If I set H2O_WAVE_APP_ADDRESS to http://0.0.0.0:3000 or http://192.168.100.112:3000 (ip address of this machine, and can be accessed from other machine), it only take the port changed:

`
INFO:     Will watch for changes in these directories: ['/apps/alpha']
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     Started reloader process [244383] using statreload
INFO:     Started server process [244386]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
`
uvicorn still listen on localhost

**Comment by zillionare** [comment]
> 
my bad. I should access the app by address and port listened by waved, which is 192.168.100.112:10101, not the uvicorn one.
