### ISSUE TITLE
GitHub Actions for Tagged Releases of Example Apps

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1335]
#### Is your feature request related to a problem? Please describe
We turn the example apps that come with Wave (Dashboards, Tour, Theme Generator) into App Bundles that can be deployed in an H2O AI Cloud environment. This is a manual process today that happens for each Wave release and currently we're making the new bundle but it's not a specific tagged release or in S3. This can make getting these apps into the platform slow and cumbersome. 

#### Describe the solution you'd like
When there is a new version of H2O Wave, we would like the tagged release to also contain `.wave` bundles for
* A Tour of Wave
* Dashboards
* Theme Generator

#### Describe alternatives you've considered
Continue the manual process

#### Additional context
Today, we have repos with Makefiles to make the Tour and Dashboard apps - maybe we continue to use those or maybe they can be retired. 
https://github.com/h2oai/wave-dashboards
https://github.com/h2oai/wave-tour

**Comment by mturoci** [comment]
@mtanco can you please provide all the necessary assets for `Theme generator` app? Similar to the 2 repos you linked for Tour and Dashboards.
