### ISSUE TITLE
Let ui.text_annotator respect \n and \r in text

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/wave#1358]
#### Is your feature request related to a problem? Please describe

Currently, `ui.text_annotator` strips off any `\n` `\r` in the text prior to rendering. This makes formatted texts to appear in a single line and additionally results in wrong character level offsets for the annotations (possible bug). 

#### Describe the solution you'd like

Let `ui.text_annotator` respect `\n` and `\r` in text for rendering and character offset calculations. To help the annotation process, this could be made visible by showing acutal `\n` or invisible by adding newlines. 

The issue probably extends to all invisible characters.

**Comment by vopani** [comment]
+1 for this, very useful to polish the component.

**Comment by marek-mihok** [comment]
Thanks for the request! @pascal-pfeiffer @vopani could you please check whether my implementation [here](https://github.com/h2oai/wave/pull/1612#issue-1360363854) is as you imagine?
