### ISSUE TITLE
lable_fill_colour is not getting applied for line plot

### ISSUE THREAD

**Issue by Nayananga** [h2oai/wave#1367]
#### Wave SDK Version, OS

(e.g. 0.20.0, macOS)

#### Actual behavior

I want to change the `label_fill_color` attribute of a line plot, But the label fill color sticks with the same color regardless of the value set.

#### Expected behavior

label fill color should change according to the value set in the Mark class

#### Steps To Reproduce

1. use code example [here](https://wave.h2o.ai/docs/widgets/plots/line#custom-labels)
2. set `label_fill_color='$blue'`
3. observe the same label fill color 
<img width="739" alt="Screenshot 2022-04-21 at 00 05 56" src="https://user-images.githubusercontent.com/25351304/164299578-bf6542db-d73a-4b80-ac45-c354e1fa7f2e.png">

**Comment by mturoci** [comment]
Can you verify this is a problem on 0.21 as well?

I get this

<img width="592" alt="image" src="https://user-images.githubusercontent.com/64769322/164392253-b5c10a92-041d-4be7-80d3-cce5ca45ff38.png">

using

```py
# Plot / Line / Labels/ Stroked
# Customize label rendering: add a subtle outline to labels to improve readability.
# #plot
# ---
from h2o_wave import site, data, ui

page = site['/demo']


page['example'] = ui.plot_card(
    box='1 1 4 5',
    title='Line, labels',
    data=data('year price', 9, rows=[
        ('1991', 3),
        ('1992', 4),
        ('1993', 3.5),
        ('1994', 5),
        ('1995', 4.9),
        ('1996', 6),
        ('1997', 7),
        ('1998', 9),
        ('1999', 13),
    ]),
    plot=ui.plot([
        ui.mark(type='line', x_scale='time', x='=year', y='=price', y_min=0,
                label_fill_color='$blue',
                label='=${{intl price minimum_fraction_digits=2 maximum_fraction_digits=2}}')
    ])
)
page.save()
```

**Comment by Nayananga** [comment]
For the new wave 0.21.0 version, property works fine
<img width="707" alt="Screenshot 2022-04-23 at 00 58 37" src="https://user-images.githubusercontent.com/25351304/164781568-e195127b-ee8d-4a12-8c2b-e2209ad74664.png">
