### ISSUE TITLE
Allow alignment for ui.text

### ISSUE THREAD

**Issue by huangxin168** [h2oai/wave#1370]
#### Is your feature request related to a problem? Please describe

I am using HO2 wave to make a web app which need to collate the text to captured subtile images:

![image](https://user-images.githubusercontent.com/76834219/164392627-081655ab-b92b-43fc-9cf4-5139e68e5bc0.png)

but textbox dont have a centered alignment option yet.

#### Describe the solution you'd like

Need start/end/center alignment options for text input applications.

#### Describe alternatives you've considered

(A clear and concise description of any alternative solutions or features you've considered.)

**Comment by mtanco** [comment]
While being implemented, you can use `html` as needed:

```python
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):

    q.page["form"] = ui.form_card(
        box="1 1 4 4",
        items=[
            ui.text("TEST"),
            ui.text("<center>TEST</center>"),
        ]
    )

    await q.page.save()
```

**Comment by mtanco** [comment]
@mturoci looks like the interest is `ui.textbox` rather than text. 

@huangxin168 can you share if you would like the textbox to be in the center of a card or if you would like the text itself to be in the center of a textbox (this second one seems a little unusual to me)

**Comment by huangxin168** [comment]
@mtanco  I would like the text itself to be in the center of a textbox(the second one)

**Comment by mturoci** [comment]
Hm... we will probably not support alignment for `ui.textbox`. It would be odd if `ui.textbox` had suddenly different alignment than the rest of form elements (dropdowns, comboboxes etc.)

However, if you really want it, you can use custom CSS to style it the way you want.
See:
https://wave.h2o.ai/docs/examples/meta-inline-stylesheet/ for an example.

Leaving the issue open though as `ui.text` alignment might be of interest to other people.

**Comment by huangxin168** [comment]
@[mturoci](https://github.com/mturoci) Thanks for you suggestion.
style = '''
textarea {
  text-align:center;
}
'''
page['meta'] = ui.meta_card(box='', stylesheet=ui.inline_stylesheet(style))

**Comment by mturoci** [comment]
For anyone willing to contribute:

* Find the file that requires the change.
* Add a new `align` attribute with possible values 'start' | 'end' | 'center' | 'justify'.
* Run `make generate` from the root of the project.
* Make alignment work.
* Test your changes against a custom python example.
* Update docs.

**Comment by dbranley** [comment]
Hello Wave,

I have a solution for this issue to allow control of text alignment in ui.text.

As requested in the ticket, I have added a new `align` prop in `text.tsx`. The possible values are `start`, `end`, `center`, and `justify`, with a default of `start`. This new prop is then passed down through the `style` prop for `Fluent.Text`. The code change in `ui/src/text.tsx` looks like this:

```{typescript}
  /** The alignment of the text content. Defaults to 'start'. */
  align?: 'start' | 'end' | 'center' | 'justify'
```

```{typescript}
    <Fluent.Text data-test={name} variant={toTextVariant(size || 'm')} style={{ textAlign: align || 'start'}} block className='w-text'>
```

I then ran the make generate target to update the generated python and R code to reflect this new attribute in files, such as `py/h2o_wave/h2o_wave/ui.py`.

I created a new unit test in `text.test.tsx`, where it tests each of the possible values for the new prop, along with confirming it defaults to `start`. Here is a snipit from the test:

```{typescript}
const textAlignPropValues: Text['align'][] = ['start', 'end', 'center', 'justify']
```

```{typescript}
  it('Renders Text with the align prop', () => {
    const { queryByTestId, rerender } = render(<XText {...textProps} />)
    expect(queryByTestId(name)).toBeInTheDocument()
    expect(queryByTestId(name)).toHaveAttribute('style','text-align: start;')     
    textAlignPropValues.forEach(textAlignPropValue => {
      rerender(<XText {...textProps} align={textAlignPropValue} />)
      expect(queryByTestId(name)).toBeInTheDocument()
      expect(queryByTestId(name)).toHaveAttribute('style','text-align: '+textAlignPropValue+';')      
    })
  }) 
```

I have updated the documentation in `website/widgets/form/text.md` with a new section called `Alignment`. I ran the make targets to regenerate the documentation artifacts and you can see a screen shot of that here:

![doc_issue_1370](https://github.com/h2oai/wave/assets/61979454/9bb188e8-6614-4b2a-a78f-0b5c5936935d)

I also created a new custom python example to try out the new `align` attribute available for `ui.text`. Here is what that code looks like:

```{python}
# Form / Text / Alignment
# Use #text align to control alignment of text.
# #form
# ---
from h2o_wave import site, ui

text = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nesciunt ab commodi pariatur fugiat sapiente?'

page = site['/demo']

page['example'] = ui.form_card(
    box='1 1 3 7',
    items=[
        ui.separator('Align - default'),
        ui.text(text),
        ui.separator('Align - start'),
        ui.text(text, align=ui.TextAlign.START),
        ui.separator('Align - end'),
        ui.text(text, align=ui.TextAlign.END),
        ui.separator('Align - center'),
        ui.text(text, align=ui.TextAlign.CENTER),
        ui.separator('Align - justify'),
        ui.text(text, align=ui.TextAlign.JUSTIFY),
        ui.separator('Various sizes - align center'),
        ui.text_xl('Extra large text', align=ui.TextXlAlign.CENTER),
        ui.text_l('Large text', align=ui.TextLAlign.CENTER),
        ui.text_m('Medium text', align=ui.TextMAlign.CENTER),
        ui.text_s('Small text', align=ui.TextSAlign.CENTER),
        ui.text_xs('Extra small text', align=ui.TextXsAlign.CENTER),
        
    ],
)
page.save()
```

And here is a screen shot of the new example:

![output_example_issue_1370](https://github.com/h2oai/wave/assets/61979454/2dc29ec7-bcc3-439f-b21e-055707c9dc70)

**Question for you:** Should I include the new example in the PR when I submit that? In my local environment, I have this at `py/examples/text_alignment.py`. But I'm not sure if I should commit this along with the other changes, or just use for my own testing.

I have a branch in my fork of the project and will be submitting a PR once I hear back about what to do with `text_alignment.py`. Let me know if this looks ok. Thanks!

**Comment by mturoci** [comment]
> Should I include the new example in the PR when I submit that? In my local environment, I have this at py/examples/text_alignment.py. But I'm not sure if I should commit this along with the other changes, or just use for my own testing.

Feel free to include in the PR. Thanks!
