### ISSUE TITLE
ui.text doesn't allow to have `_` in the beginning and end of the text content at the same time.

### ISSUE THREAD

**Issue by senalw** [h2oai/wave#1375]
Wave SDK Version : 0.20.0
OS : MacOS Monterey

In wave text component `ui.text_xl(content="_test_", width="300px")` removes `_` from the text and visible as below when  `_` is there in the beginning and end of the text content at the same time.

<img width="532" alt="Screenshot 2022-04-22 at 10 46 04" src="https://user-images.githubusercontent.com/12801761/164610307-329a1f0b-9eb5-4d53-b627-f639fe8cbbf9.png">

Expected behaviour is to visible the text as `_test_`. 

**Steps To Reproduce**
1. Use wave text component with `_` as leading and trailing character of any text. It will be visible without `_` of the beginning and the end. 

**_Note: This is ok if we don't use `_` for any text as the leading and trailing character at the same time._**

**Comment by mturoci** [comment]
This is a markdown feature, not a bug. If a word is surrounded with `_`, it means to turn it to itallic (like in your pic). To prevent this, you need to escape the underscores so instead of `_word_` use `\_word_`.
