### ISSUE TITLE
Unnecessary scrollbar in ui.stats

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1376]
### Discussed in https://github.com/h2oai/wave/discussions/1368

<div type='discussions-op-text'>

<sup>Originally posted by **azim-b** April 20, 2022</sup>
broswer: Safari Version 15.2
Wave version 0.21.0

Issue: `ui.stats()` rendering a scroll bar. Example:

![image](https://user-images.githubusercontent.com/64787868/164319922-2b754ee3-345b-4ffb-8664-5f8284692971.png)

Example 2:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/64787868/164320394-40951a07-7158-49a9-8e47-92a24447ae80.png">

**Cannot** reproduce this in wave 0.20.0

**Can** partially reproduce this in wave v0.21.0 in Firefox.
By partially, I mean that the scroll bars are rendered and then immediately disappear.</div>

### Repro

```py
q.page['body'] = ui.form_card(box='body',items=[
        # without inset
        ui.separator('Without inset'),
        ui.stats(justify='center',items=[
            ui.stat(label='H2O AI Health', value='AI4Good', icon='HealthSolid', icon_color='Red'),
        ]),
        # with inset set
        ui.separator('With inset'),
        ui.stats(justify='center', inset=True, items=[
            ui.stat(label='H2O AI Health', value='AI4Good', icon='HealthSolid', icon_color='Red'),
        ])
    ])
```

**Comment by azim-b** [comment]
@mturoci any ETA for this fix? all `ui.stat()`s are rendering the scroll bar, so we may have to downgrade h2o_wave to v0.20.0 for the first external release of one of our recent H2O AI Cloud apps.

**Comment by mturoci** [comment]
> so we may have to downgrade h2o_wave to v0.20.0

If you don't use a lot of 0.21 features then this is the way to go. If yes, we may do a patch release next week.

>  for the first external release of one of our recent H2O AI Cloud apps.

When is the planned release?

@marek-mihok @aalencar can one of you please have a look at this one?

**Comment by aalencar** [comment]
@mturoci sure, I will take a look.
