### ISSUE TITLE
Allow using TableColumn.link for multiline tables

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1379]
via @srini-x 

## Goal

![image](https://user-images.githubusercontent.com/64769322/164720473-84a36e20-5a16-4890-be02-815880846f33.png)

## Proposal

If `Tablecol.link` is specified explicitly, render it regardless of selection type. Leave the behavior as is otherwise. Note that these links should populate q.args, not open external HTTP URLS.

**Comment by lo5** [comment]
Is this issue asking for something different from https://github.com/h2oai/wave/issues/428?

**Comment by mturoci** [comment]
This issue is dealing with setting `q.args` (in multiselect table context).
#428 asks for allowing to handle external URLs (http://example.com)

**Comment by mturoci** [comment]
Update: Since #428 adds support for Markdown, this feature can be implemented via [markdown text submission](https://github.com/h2oai/wave/pull/316) that submits q.args.

Leaving this issue open since there is 1 minor bug that needs fixing. Content like `The quick brown [fox](?fox) jumps over the lazy [dog](?dog)` works, but pure links like `[fox](?fox)` do not.

**Comment by mturoci** [comment]
The above markdown proposal may not work for everyone as it submits `q.args.<md-link-name> = True` - requires handling 20 different q.args for 20 rows instead of `q.args.<table-name> = <row-name>`. Will allow specifying `TableColumn.link=True` even when multiple selection is chosen. Not sure why we originally implemented it with this constraint.
