### ISSUE TITLE
OIDC - Additional Parameters to the OIDC Provider 

### ISSUE THREAD

**Issue by aravind-viswanathan** [h2oai/wave#1380]
#### Is your feature request related to a problem? Please describe

We have a IDP Proxy (Keycloak) setup with IDP configured. There is a default IDP already configured and is taken as default for all login requests to the realm.  For the new application, we would need to configure a new IDP and this would be used exclusively by this application. In Keycloak,  we can ask for a particular IDP by sending the login request with the param _kc_idp_hint_. 

For example - https://<base url>auth/realms/mlops/protocol/openid-connect/auth?kc_idp_hint=<alias_name>

This would be similar to _domain_hint_ parameter as part of Azure AD (in order to determine the tenant) and would help in cases where the user wouldn't necessarily know which IDP needs to be chosen. 

#### Describe the solution you'd like

Ability for us to add a param through additional configuration options. For example: H2O_WAVE_OIDC_PARAMS=kc_login_hint:oidc, <param2>:<value>

or something similar which would allow us to send additional params to the IDP Proxy. 

#### Describe alternatives you've considered

Creating a different realm and setting the default authentication provider for this realm. This leads to multiple realms to be maintained.

**Comment by lo5** [comment]
If I understand correctly, in summary, you're asking for a mechanism where you can specify a set of key-value pairs to be passed to the OIDC provider? 

Are all the key-value pairs passed as URL arguments, or can there be situations where this might be different?

**Comment by aravind-viswanathan** [comment]
Yes, thats definitely another way to put it. 

These need to be passed as part of the authorize GET requests mostly and hence would be URL query params.

**Comment by aravind-viswanathan** [comment]
Hello @lo5 , 

Can you please let us know the tentative timeline might expect this feature?

Thanks

**Comment by lo5** [comment]
@aravind-viswanathan - Can you please try out nightly and verify?

Set `H2O_WAVE_OIDC_AUTH_URL_PARAMS` or pass `-oidc-auth-url-params`:

```
-oidc-auth-url-params string
    additional URL parameters to pass during OIDC authorization, in the format "key:value", comma-separated, e.g. "foo:bar,qux:42"
```

**Comment by mwysokin** [comment]
@lo5 Would it be possible to backport the feature to 0.x branch? @VijithaEkanayake told me that it'll be only part of 1.x My motivation is that since we're in a semi-emergency needing to use 1.0.0 would cause a big delay with providing it to the customer. Since `0.21.1` will need to be released because of a regression could we make it part of that release? It'd really, really help us out 🙏

**Comment by VijithaEkanayake** [comment]
> @VijithaEkanayake told me that it'll be only part of 1.x My motivation is that since we're in a semi-emergency needing to use 1.0.0 would cause a big delay with providing it to the customer. 

@mwysokin I apologize if there is any miscommunication happened. I meant told that the fix will be in the next wave release.
@lo5 It would be really helpful for us to have a patch release with this fix.

**Comment by lo5** [comment]
We can cut a new minor or patch release - no issues.

I just need confirmation that this feature worked for you.
