### ISSUE TITLE
textbox's scrollbar and text overflow when height is set

### ISSUE THREAD

**Issue by huangxin168** [h2oai/wave#1385]
#### Actual behavior

```python
from h2o_wave import site, ui

page = site['/demo']

page['example'] = ui.form_card(
    box='1 1 4 2',
    items=[ui.textbox(name='textbox_multiline', label='Multiline textarea',
                      value='Test\nTest\nTest\nTest\nTest\n',
                      multiline=True,
                      height='50px'
                      )]
)

page.save()
```
when height= is set, textbox resize makes scrollbar and text overflow.
![image](https://user-images.githubusercontent.com/76834219/164913137-726c9c0d-ffeb-4197-86e2-b2182bb9f70e.png)

#### Expected behavior

no overflow

**Comment by mturoci** [comment]
Thanks for reporting @huangxin168! Unfortunately, I am unable to reproduce the issue. What are the versions of Wave and browsers you use?

**Comment by huangxin168** [comment]
@[mturoci](https://github.com/mturoci)

Chrome 101.0.4951.54 （64bit）
h2o-wave    0.21.0
