### ISSUE TITLE
Multiline Textbox for Code

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1388]
#### Is your feature request related to a problem? Please describe
Multiline textboxes often display code and let the end user write or modify the code. Today, all text is the default font

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/4793561/165176183-e3bfef23-c6e6-44d9-96ee-07e1e2e36f10.png">

#### Describe the solution you'd like
Ideally, being able to select a language for syntax highlighting would be optimal.

#### Describe alternatives you've considered
A flag to make the font monospace

**Comment by mturoci** [comment]
Instead of building this out ourselves, I would direct people to [this blog post](https://medium.com/@unusualcode/integrating-vscode-editor-into-h2o-wave-2c075a303974).
