### ISSUE TITLE
connection error occasionally

### ISSUE THREAD

**Issue by zillionare** [h2oai/wave#1405]
#### Wave SDK Version, OS

0.21.0, ubuntu 20.04

#### Actual behavior

start the app via vscode debug:

```
        {
            "name": "app",
            "type": "python",
            "request": "launch",
            "program": "${command:python.interpreterPath}/../wave",
            "python": "${command:python.interpreterPath}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "args": [
                "run",
                "alpha.app"
            ],
            "env": {
                "PYTHONPATH": "/apps/alpha/"
            }
        },
```
sometimes this will occur:

{"error":"request failed: Post \"http://127.0.0.1:8000\": dial tcp 127.0.0.1:8000: connect: connection refused","host":"http://127.0.0.1:8000","route":"/","t":"app"}

and a "wave live" logo is displayed at browser, instead of correct page.
#### Expected behavior

no connection error, and the page can be rendered correctly.

should you need more info, feel free to ask. Thanks!

**Comment by zillionare** [comment]
(alpha) root@ubuntu:/apps/alpha# netstat -nap |grep wave
tcp6       0      0 :::10101                :::*                    LISTEN      594365/./waved      
tcp6       0      0 192.168.100.112:10101   192.168.100.14:49353    ESTABLISHED 594365/./waved      
tcp6       0      0 127.0.0.1:10101         127.0.0.1:55826         ESTABLISHED 594365/./waved      
tcp6       0      0 192.168.100.112:10101   192.168.100.14:49357    ESTABLISHED 594365/./waved 

(alpha) root@ubuntu:/apps/alpha# netstat -nap |grep 8000
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      594328/python

**Comment by lo5** [comment]
Looks like your Wave app hanged.

Specifically, when you access your app via the browser, the browser calls the Wave server, and the Wave server in turn calls your app. 

From the error you posted above, it looks like your app was busy or blocked. 

Hard to say what caused this without looking at your application's code.

**Comment by zillionare** [comment]
sorry I may doesn't put myself clear, but at the moment my app is just launched, and doesn't have chance to run any logic.

If I reboot the machine, then start debug again, everything is fine (I mean with debug mode). But if it hands during debug, it will hardly recover, event I stop debug mode and re-launch.

**Comment by lo5** [comment]
OK that makes things a bit more clear - thank you for the additional information.

If the browser tries to connect to the app before it's ready, then yes, the Wave server will assume the app is unresponsive, and not retry.

Are you initializing the database connections in an `on_startup` handler? See https://wave.h2o.ai/docs/apps#lifecycle

**Comment by zillionare** [comment]
yes @lo5 the initialization is done at on_startup:
```

async def on_client_connected(q: Q) -> None:
    q.user.theme = q.user.theme or "ember"
    # If no active hash present, render research.
    if q.args["#"] is None:
        await research_view(q)


async def on_startup():
    cfg4py.init(get_config_dir())
    await omicron.init()


async def on_shutdown():
    await omicron.stop()



@app("/", on_startup=on_startup, on_shutdown=on_shutdown)
async def serve(q: Q):
    if not q.client.initialized:
        await on_client_connected(q)
        q.client.initialized = True

    if q.events.change_symbol:
        print("js events:", q.events.change_symbol.on_symbol_hint)
    # Handle routing.
    await handle_on(q)
```

**Comment by lo5** [comment]
Hmm. I wonder if we should make the app advertise itself after `on_startup()` has completed:

https://github.com/h2oai/wave/blob/master/py/h2o_wave/server.py#L229-L232

Do you mind switching the order of those two callbacks and check if your problem goes away?

**Comment by zillionare** [comment]
I didn't get what you mean by "switching the order of those two callbacks" @lo5

**Comment by zillionare** [comment]
not 100% sure, but seems like if I launch web browser after I see "INFO:     Application startup complete.", then there's no connection refused error.

**Comment by zillionare** [comment]
I guess this might caused by my system's file handle limit. I'm using vscode over ssh, it will used up many many file handle. After I extend system's open file handle limit, the issue almost never occurs.

closed.
