### ISSUE TITLE
Make dropdown menus with labels 1 row tall

### ISSUE THREAD

**Issue by codeananda** [h2oai/wave#1415]
#### Is your feature request related to a problem? Please describe

Dropdown menus with `label='some label'` are more than 1 row tall.

#### Describe the solution you'd like

Make dropdown menus with labels 1 row tall (adjust vertical centering?)

#### Describe alternatives you've considered

I've been making them 2 rows tall and overlaying a plot on top to cover the white space. This is hacky.

Code to reproduce + screenshots

```python
# filename: dropdown.py
from h2o_wave import main, app, Q, ui


@app("/")
async def serve(q: Q):

    q.page["dropdown_one"] = ui.form_card(
        box="1 1 3 1",
        items=[
            # Add dropdown menu
            ui.dropdown(
                name="choice",
                label="One Row High - A Bit Too Small",
                choices=[
                    ui.choice(name="one", label="One"),
                    ui.choice(name="two", label="Two"),
                ],
            )
        ],
    )

    q.page["dropdown_two"] = ui.form_card(
        box="1 2 3 2",
        items=[
            # Add dropdown menu
            ui.dropdown(
                name="choice",
                label="Two Rows High - Way Too Much",
                choices=[
                    ui.choice(name="one", label="One"),
                    ui.choice(name="two", label="Two"),
                ],
            )
        ],
    )
    await q.page.save()

```
![2022-05-12 17 05 55](https://user-images.githubusercontent.com/51246969/168034716-cf4edfb7-8bc3-4df6-9d0d-b04bd46494e6.gif)

**Comment by lo5** [comment]
Why not put both dropdowns into one form card?

**Comment by codeananda** [comment]
I am stressing that having a dropdown one row high + a label looks funny.  I included two dropdowns to make this point clear. The question isn't about how to best display two dropdown menus.

**Comment by lo5** [comment]
Different components in Wave have different heights. Optimizing the height to make one solitary dropdown look perfect is not going to bode well for other components. 

The [grid layout](https://wave.h2o.ai/docs/layout#grid-layout) system that you're using is optimized for displaying pixel-perfect dashboards, like the one you see [here](https://wave.h2o.ai/docs/getting-started). The widgets there fit perfectly.

If you want more control over layout, use the [flex layout](https://wave.h2o.ai/docs/layout#flex-layout) system.

In general, people use the grid layout system to put something together quickly, hammer out the page flow and UX, then switch to the flex layout system to polish things up.
