### ISSUE TITLE
Getting 403 error

### ISSUE THREAD

**Issue by THESHAMIK** [h2oai/wave#1422]
#### Wave SDK Version, OS

Installed through 
pip install h2o-wave (after creation of a new virtual env in anaconda)
Already h2o is installed & working fine with python.
$ wave fetch
pip install -r examples/requirements.txt
http://localhost:10101/tour ==> This triggers NO error. Here i the o/p

(aqua_h2o) C:\Users\shamik.bhattacharya\wave>wave run examples.tour
params: []2022/05/17 10:22:00 #
2022/05/17 10:22:00 # ┌────────────────┐ H2O Wave
2022/05/17 10:22:00 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ 0.21.1 20220512131635
2022/05/17 10:22:00 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
2022/05/17 10:22:00 # └────────────────┘
2022/05/17 10:22:00 #
2022/05/17 10:22:00 # {"address":":10101","base-url":"/","t":"listen","web-dir":"D:\\Anaconda3\\envs\\aqua_h2o\\www"}
[32mINFO[0m:     Will watch for changes in these directories: ['C:\\Users\\shamik.bhattacharya\\wave']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m11652[0m] using [36m[1mstatreload[0m
----------------------------------------
 Welcome to the H2O Wave Interactive Tour!

 Go to http://localhost:10101/tour
----------------------------------------
[32mINFO[0m:     Started server process [[36m2160[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
2022/05/17 10:22:32 # {"addr":"[::1]:49534","route":"/tour","t":"ui_add"}

When I open http://localhost:10101/tour
I get blank white page with just wave logo:

Then I created hello.py file & run it .Here I get 403 error as pasted here:

Traceback (most recent call last):
  File "hello_1.py", line 14, in <module>
    page.save()
  File "D:\Anaconda3\envs\aqua_h2o\lib\site-packages\h2o_wave\core.py", line 567, in save
    self.site._save(self.url, p)
  File "D:\Anaconda3\envs\aqua_h2o\lib\site-packages\h2o_wave\core.py", line 632, in _save
    raise ServiceError(f'Request failed (code={res.status_code}): {res.text}')
h2o_wave.core.ServiceError: Request failed (code=403): 

<body><div class="message-container">
    <div class="logo"></div>
    <h1>403 Forbidden: incorrect proxy service was requested</h1>
    <p>The webserver reported that an error occurred while trying to access the website. Please return to the previous page.</p>
    <table><tbody>

#### Actual behavior

When I open http://localhost:10101/tour ==> opens blank white page with wave logo 

#### Expected behavior

When I open http://localhost:10101/tour  == should open real page 

#### Steps To Reproduce

1. Create a vitual new env in Anaconda
2. Pip install h2o. Working fine with python
3. Pip install h2o-wave
4. wave fetch
5. pip install -r examples/requirements.txt
6. Upto here all ok with no error.

**Comment by mturoci** [comment]
Hi @THESHAMIK

the Anaconda and pip combination seems to be a bit odd. Can you please try using only standard python within virtualenv and pip as suggested in the [docs](https://wave.h2o.ai/docs/installation)? Also, make sure there are no `H2O_WAVE_*` env variables set and your first installation is clean.

Also please look at [how to format code in GH comments](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) as the logs you pasted are very difficult to read now.

**Comment by THESHAMIK** [comment]
I feel this is not right way of closing based on assumptions. Anyway this problem is just now solved by me by taking proxy out. The moment its taken out all working fine. Thanks.
