### ISSUE TITLE
Make post_logout_redirect_uri configurable

### ISSUE THREAD

**Issue by henrycs** [h2oai/wave#1448]
#### Wave SDK Version, OS
h2o-wave, 0.21.1, Ubuntu 20.04, Keycloak 10.0.2 (docker), Chrome 100.0.4896.127

#### Actual behavior
We test OAuth in wave app with Keycloak 10.0.2, it's OK for login testing, but we cannot logout user session using "_auth/logout", Keycloak reports "invalid redirect uri" after we call "_auth/logout", we can see the session still exists in Keycloak Web console.
URL to logout session generated by wave:
http://192.168.100.201:8080/auth/realms/master/protocol/openid-connect/logout?id_token_hint=xxxxxxxxxx&post_logout_redirect_uri=192.168.100.201%3A10101
I try to replace post_logout_redirect_uri with "http://192.168.100.201%3A10101/demo", and execute this call manually in browser, everything is OK, session removed from Keycloak, the browser redirect to login page again.

#### Expected behavior
Session logout and we can login again (including session in Keycloak)

#### Steps To Reproduce
1. start Keycloak instance follow the guide: https://wave.h2o.ai/docs/development#run-keycloak
2. configure wave app:
"H2O_WAVE_OIDC_CLIENT_ID": "wave",
"H2O_WAVE_OIDC_CLIENT_SECRET": "1d43a43c-165a-4e83-bfd1-722dc5b1bf8a",
"H2O_WAVE_OIDC_END_SESSION_URL": "http://192.168.100.201:8080/auth/realms/master/protocol/openid-connect/logout",
"H2O_WAVE_OIDC_PROVIDER_URL": "http://192.168.100.201:8080/auth/realms/master",
"H2O_WAVE_OIDC_REDIRECT_URL": "http://192.168.100.201:10101/_auth/callback"
3. start wave app, open browser, access the URL of our app, login
4. click logout button:  ui.link(label='Logout', path='_auth/logout', target=''),

Log and error messages:
Keycloak console:
09:37:31,990 WARN  [org.keycloak.events] (default task-4) type=LOGOUT_ERROR, realmId=master, clientId=null, userId=null, ipAddress=192.168.100.19, error=invalid_redirect_uri, redirect_uri=192.168.100.201:10101
Message in browser after logout URL called: invalid redirect uri
URL in browser address bar:
http://192.168.100.201:8080/auth/realms/master/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGeWJEbllwWmtxMUJkRnZHNDdCRmRyNldyelhIRV93UDV1Z0VXYXlRSFRJIn0.eyJleHAiOjE2NTM2NDQzMDcsImlhdCI6MTY1MzY0NDI0NywiYXV0aF90aW1lIjoxNjUzNjQ0MjQ3LCJqdGkiOiI0NWU5MjE1MS1jOWQ4LTQ1MWYtYWFjZS04ODZlMjQ1NmE3NjkiLCJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMDAuMjAxOjgwODAvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoid2F2ZSIsInN1YiI6IjliYjBjOTkxLTFjZTgtNDU4OS1hYjI0LTBmYTM2ZmQ0OTkzNCIsInR5cCI6IklEIiwiYXpwIjoid2F2ZSIsIm5vbmNlIjoiYmM3MDg0MGMiLCJzZXNzaW9uX3N0YXRlIjoiOTVjMDBhN2ItNTE0ZC00NTJjLTk2NDEtODA2NmFlNmY1Njc5IiwiYWNyIjoiMSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiaGVucnkifQ.WlMnc7cQNrIqPF-XzRxYCFgdsTgVdgj1qb_bZKSZ1mAUVX8swEY8LKQynj6IUHdWQ-dB0fjLiNcX9ss6FCOtXgIaMDkQ6VjFbO1-_nSLv8HBnHWDgQXhrEF37pMeKA3AkattvkQwFgBVq4rtk7in-RPKHespxnDPoNEFJKHRSLtcgv-mQZvRRRP7SjFIF7XsgWHBIBtMWU-_V1ML5u9ccYKGZpX5fha6c7a93kqLZ8LMaMVQXLR_q8Js7kPnmSMzkPi0NTXFPTAs0Y-shAzaITAWGfwFZQPU29kKgCQFA4ukCItxz3bpi9RAdOw9MDSdsgAxXFryMCFuMu6TgWh-8Q&post_logout_redirect_uri=192.168.100.201%3A10101

**Comment by mturoci** [comment]
Let's add `oidc-post-logout-redirect-url` (server param) and `H2O_WAVE_OIDC_POST_LOGOUT_REDIRECT_URL` (env var) server config options for the highest flexibility - cc @lo5

**Comment by bandaider** [comment]
Also recommend adding the `_auth/logout` bit to the Security documentation.
