### ISSUE TITLE
Image annotator box dragging anomalies

### ISSUE THREAD

**Issue by gaborfodor** [h2oai/wave#1461]
#### Wave SDK Version, OS

wave 0.22 macOS 12.3

#### Actual behavior
Using `ui.image_annotator` unexpected sudden dragging boxes around the edges could resize them or create new ones.

#### Expected behavior

* Boxes should keep their original size during dragging
* Dragging should not create new boxes

#### Steps To Reproduce
https://user-images.githubusercontent.com/5063584/171141105-da3135a6-05cf-48c7-b2b8-7d0345c67726.mov

**Comment by aalencar** [comment]
@gaborfodor I couldn't reproduce it. Could you provide the repro code and the image you used?

**Comment by gaborfodor** [comment]
@aalencar 
Probably the simplest is to reproduce it with the demo code https://wave.h2o.ai/docs/examples/image-annotator

**Comment by mturoci** [comment]
It seems like this happens only during when the canvas boundary is hit repeatedly.

**Comment by aalencar** [comment]
I managed to reproduce this time and it doesn't have to be done repeatedly. See the video:

https://user-images.githubusercontent.com/15820796/180192491-c2db462c-ee10-4aca-811a-7e560b876229.mov
