### ISSUE TITLE
flickering when updating vega_card

### ISSUE THREAD

**Issue by roema** [h2oai/wave#1475]
#### Wave SDK Version, OS

0.22.0 / 0.21.0 Arch Linux

#### Actual behavior

When updating a vega_card, it flickers.
Lineplot shifts the curve into the past.

#### Expected behavior

No flickering. Occurs only since version 0.21.0.

#### Steps To Reproduce

1. Create page with vega_card and lineplot
2. update data with page.save()
3. See flicker

```python
        rsrp_spec = """
        {
          "description": "A simple bar plot with embedded data.",
          "mark": "bar",
          "encoding": {
            "x": {"field": "Cell", "type": "ordinal"},
            "y": {"field": "dBm", "type": "quantitative"}
          }
        }
        """
        self.q.page.add(
            "lte_rsrp_bar_plot",
            ui.vega_card(
                box=ui.box(zone="top_left", order=1),
                title="RSRP",
                specification=rsrp_spec,
                data=data(("Cell", "dBm")),
            ),
        )

        v = self.q.page.add(
            "lte_rsrq_line_plot",
            ui.plot_card(
                box=ui.box(zone="middle_2", order=1),
                title="RSRQ",
                data=data("cell seconds power"),
                plot=ui.plot(
                    [
                        ui.mark(
                            type="line",
                            x_scale="linear",
                            x="=seconds",
                            y="=power",
                            curve="step",
                            color="=cell",
                        )
                    ]
                ),
            ),
        )
```

https://user-images.githubusercontent.com/9306994/171797109-e60548b1-1bd5-4ed0-88fb-8b7aaa21e8da.mov

https://user-images.githubusercontent.com/9306994/171812741-03e8bcd9-b907-48f7-b6fa-d5bc4bd0beb3.mov

Also lineplot have some troubles since 0.21

https://user-images.githubusercontent.com/9306994/171812887-5012aecc-02bb-4447-acef-2b1cefb602c7.mov

https://user-images.githubusercontent.com/9306994/171812956-5515e196-2c26-4ab6-beb6-f05c16324298.mov

**Comment by mturoci** [comment]
Thanks for filling the issue @roema!

Can you please provide runnable min repro code with consistent data? Your video cases use different data which may not be optimal. Looking at the https://wave.h2o.ai/docs/examples/plot-vegalite-update/, everything seems to be fine.

re line plots: Min repro code needed as well.

**Comment by roema** [comment]
Thanks @mturoci for your fast message!

I have tested the example and it works with one chart. If i define more then one, all charts flickering

https://user-images.githubusercontent.com/9306994/171825981-f4b28faa-127f-45cc-a634-b1c0ee59aa08.mov

https://user-images.githubusercontent.com/9306994/171825993-0b29cef9-22e7-4567-b45c-4ecb830f7536.mov

I will check line plot too.
.

**Comment by mturoci** [comment]
Perfect, that's helpful.

**Comment by roema** [comment]
So now i have tested line plot.
We plotting realtime data from LTE basestations. 
Sometimes the number of base stations received changes, so i have modified the minimal example like this

```python
last = 0

# Generate random datum between 1 and 100
def rnd():
    return random.randint(1, 15)

def poll():
    data = []
    global last
    for cnt in range(0 + last, 512 + last):
        data.append(("0", ("%d" % (cnt)), rnd()))
        data.append(("1", ("%d" % (cnt)), rnd()))
    last = last + 512
    return data
    
def poll_new():
    data = []
    global last
    for cnt in range(0 + last, 512 + last):
        data.append(("0", ("%d" % (cnt)), rnd()))
        data.append(("1", ("%d" % (cnt)), rnd()))
        data.append(("2", ("%d" % (cnt)), rnd()))
    last = last + 512
    return data   

@app('/')
async def create(self):



	vis = page.add('example', ui.plot_card(
		box='1 1 12 5',
		title='Line',
		data=data('cell seconds power', rows=poll()),
		plot=ui.plot([ui.mark(type='line', curve="step", color="=cell",  x_scale='linear', x='=seconds', y='=power', y_min=0)])
	))

	while True:
		time.sleep(1)
		# Update the plot's data rows
		vis.data = poll_new()

		page.save()
```
We init the plot with 2 and updating the plot with 3 stations, but the line plot freezing, no data where be shown.

On waved 0.20 we have init the line plot like this

```python
        for n in range(0, 2):
            globals()["chan%d" % n] = [(("%d" % (n)), 0, 0)]

        u = self.q.page.add(
            "lte_rsrp_line_plot",
            ui.plot_card(
                box=ui.box(zone="middle_1", order=0),
                title="RSRP",
                data=data("cell seconds power", rows=chan0+chan1),
                plot=ui.plot(
                    [
                        ui.mark(
                            type="line",
                            x_scale="linear",
                            x="=seconds",
                            y="=power",
                            curve="step",
                            color="=cell",
                        )
                    ]
                ),
            ),
        )

        u.data = chan0 + chan1
```
Thanks for your help!

**Comment by mturoci** [comment]
@roema I managed to fix the vega perf issue, but I am not clear on what is the problem with line plots. Can you please give me a runnable min repro that would exhibit different behavior against 0.20?

**Comment by roema** [comment]
@mturoci, Thanks for you work!!

Yes, i would create a runnable repro and create an new issue!

**Comment by mturoci** [comment]
Feel free to test the vega perf fix in our nightly and let me know if the fix is sufficient.
