### ISSUE TITLE
Dropdown list weird when many items

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#149]
**Q SDK Version, OS**
0.5.0 (I think) q8s.h2o.ai - see Telco Churn App v 0.1.0

**Actual behavior**
drop down list looks weird and moves to the left when there are too many items for a certain resolution

This is on my 14" Mac 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/4793561/94050656-6bdabc00-fd8b-11ea-96f6-a21ea5fa3167.png">

This is the same page but I moved to my additional monitor which is larger / different resolution (I guess)
![image](https://user-images.githubusercontent.com/4793561/94050830-a3e1ff00-fd8b-11ea-8259-d54dc9d67fca.png)

When I had 100 items in my drop down list I saw the same behavior on both screens

**Expected behavior**
Don't move location when there are lots of items

**Steps To Reproduce**
I have not figured out the exact repo steps in regards to how many items is "too many" for a screen

**Comment by lo5** [comment]
@mturoci if this is the default behavior of the dropdown and it's unrelated to the enclosing card or layout, it's not worth trying to address this. LMK.

**Comment by mturoci** [comment]
@lo5 Agree, just wanted to find a possible fix as this seems to bother people (1 other duplicate issue). As for me, I am fine with default Fluent behavior. Closing this with a note that this can be used if more people saw this as a bug.
