### ISSUE TITLE
Table with Search Bar has wastage of space

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#1492]
#### Is your feature request related to a problem? Please describe
A table with a search bar leads to a large wasted space between the bar and the table.

#### Describe the solution you'd like
A much smaller gap to utilize maximum space.

<img width="526" alt="Screenshot 2022-06-09 at 6 26 12 PM" src="https://user-images.githubusercontent.com/8954217/172853914-e1ddda8c-0b8e-4692-87dc-757bc50efeb0.png">

**Comment by itzelmald** [comment]
Hello, I would like to work on this issue.

**Comment by aalencar** [comment]
Hi @itzelmald,

Thank you for the help! If you haven't done so yet, please take a look at [Contribution Guidelines](https://github.com/h2oai/wave/blob/master/.github/CONTRIBUTING.md) before proceeding and let us know if you need any help with it.

**Comment by itzelmald** [comment]
Hello, I am new to open source and was wondering in which files I could find this issue?

**Comment by tavarescarolina** [comment]
Hello, can i do it?

**Comment by mturoci** [comment]
It's all yours @tavarescarolina. Good luck!

**Comment by mturoci** [comment]
The isue is up for grabs again for anyone interested.

**Comment by JacksonIsaac** [comment]
Isn't this already fixed in the previous merged PR ?

**Comment by mturoci** [comment]
There is no merged PR. You are free to take this up.

**Comment by JacksonIsaac** [comment]
Oke, thanks. Will take this up :)
