### ISSUE TITLE
Spellcheck doesn't show until click

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#1499]
#### Wave SDK Version, OS
v0.22.0 on MacOS

#### Actual behaviour
A textbox with `spellcheck=True` doesn't underline the errors until the textbox is clicked.

#### Expected behaviour
The errors in the textbox should be underlined when the card is rendered (even if textbox is not clicked on).
Or else provide a way/option to enable it to show errors without clicking the box.

#### Steps To Reproduce
Any textbox with `spellcheck=True`.

#### Additional comments
A bit related to https://github.com/h2oai/wave/issues/606

**Comment by mturoci** [comment]
There is not much we can do other than ugly hacks. The spellcheck attr is not configurable beyond telling browser whether to spellcheck or not. Note that you cannot even control what lang it's spellchecking against even from JS. The intention for the attr presence in Wave was to just turn it off when needed. The behavior you are experiencing is the one browsers think is the [best UX](https://bugzilla.mozilla.org/show_bug.cgi?id=799475).

However, if you really want to achieve the proposed behavior you can use this piece of custom JS:

```js
// Grab a reference to textarea.
const textArea = document.querySelector('textarea[data-test="<wave_name_attr>"]')
// Focus to trigger spellcheck.
textArea.focus()
// Remove focus.
textArea.blur()
```

**Comment by vopani** [comment]
Cool, thanks!
cc: @leecming82
