### ISSUE TITLE
Allow lower values in Spinbox

### ISSUE THREAD

**Issue by ybabakhin** [h2oai/wave#1525]
#### Wave SDK Version, OS

0.21.1, Ubuntu

#### Actual behavior

Setting minimum and step values to 1e-7 in `ui.spinbox` does not work, as all the changes are giving either 0 or 1e-7 value:

https://user-images.githubusercontent.com/25034016/176399405-cd27814d-ac5e-429b-9647-beac9b2b4bc9.mov

With 1e-6 min and step values everything looks good:

https://user-images.githubusercontent.com/25034016/176399502-8f34a9d0-e5d1-4931-8929-124a97f0414b.mov

#### Expected behavior

Allow lower values in `ui.spinbox`

#### Steps To Reproduce

1. Create a `ui.spinbox` with 1e-7 as min and step values
2. Try changing the value

**Comment by pascal-pfeiffer** [comment]
I would also appreciate the ability to choose smaller values than 1e-6.
Current learning rates for fine-tuning LLMs are often in the 1e-7 range and the spinbox would be the best fit to do such things in a H2O Wave UI. The current lower limit of 1e-6 makes this impossible.

![image](https://github.com/h2oai/wave/assets/1069138/d69beaaf-f652-4408-abf5-29d7cdb4e52f)

**Comment by psinger** [comment]
@mturoci any plans for this to be addressed or any workaround?
also running into it

**Comment by mturoci** [comment]
@marek-mihok please prioritize.
