### ISSUE TITLE
Choice Group alignment ignored

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1526]
#### Wave SDK Version, OS
0.22.0

#### Actual behavior
Choice group is rendering horizontally, regardless of the `inline` value. 

#### Expected behavior
Choice group should be able to be vertical or horizontal

#### Steps To Reproduce
See the documentation screen shots here: https://wave.h2o.ai/docs/widgets/form/choice_group/
where even when inline is not set we have grid format not vertical

**Comment by mturoci** [comment]
Should be fixed by https://github.com/h2oai/wave/commit/7d290e1b2243202bdf51ba3e847b52cd4be3dafc. @mtanco can you please verify this in nightly?
