### ISSUE TITLE
Ability to turn off SSL cert verification when doing requests from Wave server (e.g. Keycloak)

### ISSUE THREAD

**Issue by fousasg** [h2oai/wave#1547]
#### Is your feature request related to a problem? Please describe

When WAVE server is running with keycloak which uses self-signed certificates it returns the following error:
```
panic: failed connecting to OIDC provider: Get "https://192.168.4.38:8443/auth/realms/master/.well-known/openid-configuration": x509: cannot validate certificate for 192.168.4.38 because it doesn't contain any IP SANs

goroutine 1 [running]:
github.com/h2oai/wave.Run({{0x401f3d, 0x9}, {0x4013ba, 0x7}, {0x401048, 0x6}, {0x40074e, 0x1}, {0x10d2468, 0x17}, ...})
	/home/odisseas/wave/server.go:101 +0x1aa0
main.main()
	/home/odisseas/wave/cmd/wave/main.go:256 +0x166c
```

#### Describe the solution you'd like

It would be helpful if it would be possible to turn off SSL cert verification

**Comment by mturoci** [comment]
cc @lo5 for discussion. Shall we allow disabling this for every Wave server HTTP request or just special-case it for Keycloak? Also, we need to make sure to put a big red warning about not using this in prod.
