### ISSUE TITLE
Path support for image annotator

### ISSUE THREAD

**Issue by Nischaydnk** [h2oai/wave#1553]
#### Is your feature request related to a problem? Please describe

I'm planning to build a generic annotator app for images. Currently, wave only supports bounding box annotation (rectangle). For the segmentation part, there is no way to annotate masks. Introducing that in the image annotator could be a great addition. 

#### Describe the solution you'd like

path support (polygon) can be introduced to support annotating segmentation masks.

cc @mturoci

**Comment by mturoci** [comment]
Resolved by https://github.com/h2oai/wave/pull/1643
