### ISSUE TITLE
Table component does not show multi spaces

### ISSUE THREAD

**Issue by ShehanIshanka** [h2oai/wave#1554]
#### Wave SDK Version

0.21.1

#### Actual behavior

Multi spaces are shown as a single space. 
Front spaces are not shown.

#### Steps To Reproduce

```python
from h2o_wave import ui, main, Q, app

@app("/")
async def serve(q: Q) -> None:
    q.page['example'] = ui.form_card(box='1 1 3 3', items=[
        ui.table(
            name='table',
            columns=[
                ui.table_column(name='name', label='Name')
            ],
            rows=[
                ui.table_row(name='row1', cells=['John    Doe']), # Multi space
                ui.table_row(name='row2', cells=['  Alice   Smith']), # Front space
                ui.table_row(name='row3', cells=['Bob     Adams']),
            ]
        )
    ])

    await q.page.save()
```
<img width="479" alt="Screenshot 2022-07-22 at 11 31 01" src="https://user-images.githubusercontent.com/29954570/180373465-cf189fb4-7c5f-40b9-b797-b2941a96549d.png">

**Comment by mturoci** [comment]
This is how HTML works by default. See [explanation](https://stackoverflow.com/questions/433493/why-does-html-require-that-multiple-spaces-show-up-as-a-single-space-in-the-brow). If you really want multiple spaces to be shown, you can use [markdown cell](https://wave.h2o.ai/docs/widgets/form/table#markdown-support) with `<pre>` tag.
