### ISSUE TITLE
Plot Legend list arrows are broken

### ISSUE THREAD

**Issue by MartinBarus** [h2oai/wave#1562]
#### Wave SDK Version, OS

Mac, wave 22

#### Actual behavior

When there is a plot with legend and too many line plots, the legend allows for scrolling (yellow arrows).

These arrows work one way (next), but no the other way (previous) so once you scroll to last portion of legend, you cannot get back to the first portion of it

<img width="611" alt="Screenshot 2022-07-29 at 10 18 51" src="https://user-images.githubusercontent.com/6991522/181716940-c858f8a6-6b32-42dd-b5a8-b506d0600e46.png">

#### Steps To Reproduce

Create plot with many Line plots
```py
from h2o_wave import main, app, Q, ui, data


@app('/')
async def serve(q: Q):
    rows = [
        [0, "plot_label_1", 0],
        [0, "plot_label_2", 10],
        [0, "plot_label_3", 20],
        [100, "plot_label_1", 0],
        [100, "plot_label_2", 10],
        [100, "plot_label_3", 20],
        [0, "plot_label_4", 40],
        [0, "plot_label_5", 50],
        [0, "plot_label_6", 60],
        [100, "plot_label_4", 40],
        [100, "plot_label_5", 50],
        [100, "plot_label_6", 60],
    ]
    d = data(fields=["step", "type", "val"], rows=rows, pack=True)

    viz = ui.visualization(
        plot=ui.plot(
            [
                ui.mark(
                    type="line",
                    x_title="step",
                    x_scale="linear",
                    y_scale="linear",
                    x="=step",
                    y="=val",
                    color="=type",
                )
            ]
        ),
        data=d,
        interactions=["brush"],
        height="calc((100vh - 275px)*0.42)",
        width="560px",
    )

    q.page["charts"] = ui.form_card(box='1 1 20 20', items=[viz])

    await q.page.save()
```

**Comment by mturoci** [comment]
This is a bug in the underlying plotting library, tracked in https://github.com/antvis/G2/issues/2549.

Reasoning: G2 lib supports 2 types of renderers - canvas and SVG. Wave uses SVG to leverage the power of CSS variables for theming. Unfortunately, the legend pagination is broken for this type of renderer.
