### ISSUE TITLE
Color picker extension 

### ISSUE THREAD

**Issue by dott1718** [h2oai/wave#1600]
Currently, it’s possible to either have a color_picker or a predefined list of color choices (swatch picker). It would be great to combine these features and give the user the ability to choose another color outside of the predefined colors. A preferred choice would be to have three dots or a dropdown icon at the far right of the swatch picker, that would popup the usual color picker for a new user choice. For downward compatibility, this feature should be a toggle for devs (e.g. allow_custom=False) which is evaluated when choices are specified.

**Comment by mturoci** [comment]
Can you elaborate on why would this be needed?

Citing my comment in the design doc:

_If the user picks an arbitrary color, isn't it also expected that they will choose it also? In which case adding it to the swatch picker seems unnecessary.
Btw this may already be possible using inline=True color picker and updating the swatch picker choices accordingly._

**Comment by dott1718** [comment]
The suggestion in a nutshell is to allow inline=True and choices=[] to work when provided at the same time.

The use case we work on is a screen where a user can add "classes", name them and assign colors, therefore choices=[] works well to quickly pick a new color for each class. But with large number, the colors will repeat.

![image](https://user-images.githubusercontent.com/12784356/188449338-2198bed9-0f49-4268-aab2-87d96232ba74.png)

So having both a predefined list of colors for a quick choice and a color picker would give the desired flexibility. But I can see how color picker alone can be a workaround in this case.

**Comment by mturoci** [comment]
I see your point, but I believe that most of the time people don't really care for the color as long as it's different enough from the others. I would suggest generating the swatch colors dynamically and make sure they do not include already existing colors. For example Github has similar UX when it comes to picking tag color:

https://user-images.githubusercontent.com/64769322/189291967-64c5792d-530e-4e64-b502-63e91c465a7d.mov

IMO this is the best UX, wdyt?

**Comment by dott1718** [comment]
Yes, fully agree - it is just about getting a new color different from the others. A button to generate a new one would be even better than the original suggestion. Thank you @mturoci !
