### ISSUE TITLE
[Feature] : Add Language Translator 

### ISSUE THREAD

**Issue by DeshanHarshana** [h2oai/wave#1610]
Most of the time when we are going to create a dashboard using wave, it is good to create it in different languages for understanding different people more clearly. Instead of creating different components for different languages, it is easy to add language JSON files manually.

For example, in angular, we use ngx-translate for doing this task. If we can make a library like that we can use simple pipe(|) for phrases that we need to translate. Then it uses a relevant language JSON file and converts our phrase to the language that we chose.

**Comment by mturoci** [comment]
Hi @DeshanHarshana, seems like [python-i18n](https://pypi.org/project/python-i18n/) is what you are after.
