### ISSUE TITLE
Add Github star count to docs page

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1619]
Add a big star count [Github button](https://buttons.github.io/) to https://wave.h2o.ai/ (probably under Get started button).

**Comment by BBentleyDev** [comment]
Hi there, can I work on this issue?

**Comment by aalencar** [comment]
> Hi there, can I work on this issue?

Sure!

**Comment by BBentleyDev** [comment]
I'm new to opensource development and was hoping for some assistance setting up the development environment. I'm following the installation instructions in wave/website/README.md. When I run the setup command I get the following error:


git clone --depth 1 --branch v0.8.0 https://github.com/h2oai/wave-ml.git 
h2o_wave_ml
Cloning into 'h2o_wave_ml'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 42 (delta 3), reused 19 (delta 1), pack-reused 0
Unpacking objects: 100% (42/42), 2.33 MiB | 3.99 MiB/s, done.
Note: switching to 'c823b58db11c364d1dd904ec9d1165c417663065'.

You are in 'detached HEAD' state. You can look around, make experimental 
changes and commit them, and you can discard any commits you make in thisstate without impacting any branches by switching back to a branch.      

If you want to create a new branch to retain commits you create, you may 
do so (now or later) by using -c with the switch command. Example:       

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

python3 -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/py/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

make: *** [Makefile:18: setup] Error 1


So I try the "sudo apt install python3.8-venv" command it recommends and get this error:


Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python3.8-venv
0 upgraded, 1 newly installed, 0 to remove and 47 not upgraded.
Need to get 5448 B of archives.
After this operation, 27.6 kB of additional disk space will be used.     
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.4
Err:1 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 python3.8-venv amd64 3.8.10-0ubuntu1~20.04.4
  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/p/python3.8/python3.8-venv_3.8.10-0ubuntu1~20.04.4_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


Any assistance would be greatly appreciated! I'm on Windows using WSL.

**Comment by aalencar** [comment]
I'm on MacOS and things can vary greatly, but I will try to help you out. 

Have you run `run apt-get update` as suggested?

**Comment by aalencar** [comment]
You have to clone this repo https://github.com/h2oai/wave

**Comment by BBentleyDev** [comment]
Thanks for the help! I've gotten to the npm start command and now get the following error:

> website@0.0.0 start
> docusaurus start

[INFO] Starting the development server...
[ERROR] Loading of version failed for version current
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- widgets/content/article
- widgets/content/breadcrumbs
- widgets/content/footer
- widgets/content/frame
- widgets/content/header
- widgets/content/image
- widgets/content/markdown
- widgets/content/markup
- widgets/content/navigation
- widgets/content/post
- widgets/content/preview
- widgets/content/profile
- widgets/content/tabs
- widgets/content/tall_article_preview
- widgets/content/tall_info
- widgets/content/template
- widgets/content/toolbar
- widgets/content/wide_article_preview
- widgets/content/wide_info
- widgets/form/button
- widgets/form/checkbox
- widgets/form/checklist
- widgets/form/choice_group
- widgets/form/color_picker
- widgets/form/combobox
- widgets/form/copyable_text
- widgets/form/date_picker
- widgets/form/dropdown
- widgets/form/expander
- widgets/form/facepile
- widgets/form/file_upload
- widgets/form/frame
- widgets/form/image
- widgets/form/image_annotator
- widgets/form/inline
- widgets/form/label
- widgets/form/link
- widgets/form/links
- widgets/form/markup
- widgets/form/menu
- widgets/form/message_bar
- widgets/form/overview
- widgets/form/persona
- widgets/form/picker
- widgets/form/progress
- widgets/form/range_slider
- widgets/form/separator
- widgets/form/slider
- widgets/form/spinbox
- widgets/form/stats
- widgets/form/stepper
- widgets/form/table
- widgets/form/tabs
- widgets/form/template
- widgets/form/text
- widgets/form/text_annotator
- widgets/form/textbox
- widgets/form/time_picker
- widgets/form/toggle
- widgets/form/vega_visualization
- widgets/form/visualization
- widgets/overlays/dialog
- widgets/overlays/notification
- widgets/overlays/notification_bar
- widgets/overlays/side_panel
- widgets/overview
- widgets/plots/area
- widgets/plots/interactions
- widgets/plots/interval
- widgets/plots/line
- widgets/plots/overview
- widgets/plots/path
- widgets/plots/point
- widgets/plots/third-party/altair
- widgets/plots/third-party/bokeh
- widgets/plots/third-party/d3
- widgets/plots/third-party/matplotlib
- widgets/plots/third-party/plotly
- widgets/plots/third-party/vega
- widgets/plots/third-party/vegalite
- widgets/stat/large_bar_stat
- widgets/stat/large_stat
- widgets/stat/small_series_stat
- widgets/stat/small_stat
- widgets/stat/tall_gauge_stat
- widgets/stat/tall_series_stat
- widgets/stat/tall_stats
- widgets/stat/wide_bar_stat
- widgets/stat/wide_gauge_stat
- widgets/stat/wide_pie_stat
- widgets/stat/wide_series_stat

Available document ids are:
- api/core
- api/db
- api/graphics
- api/h2o_wave_ml/index
- api/h2o_wave_ml/ml
- api/h2o_wave_ml/types
- api/h2o_wave_ml/utils
- api/index
- api/metadata
- api/routing
- api/server
- api/test
- api/types
- api/ui
- api/ui_ext
- api/version
- apps
- architecture
- arguments
- background
- backup
- browser-testing
- buffers
- change-log
- cli
- color-theming
- configuration
- contributing
- custom-css
- deployment
- development
- examples/all
- examples/article
- examples/background
- examples/background-executor
- examples/background-progress
- examples/breadcrumbs
- examples/button
- examples/buttons
- examples/card-menu
- examples/checkbox
- examples/checklist
- examples/checklist-inline
- examples/checkpoint
- examples/choice-group
- examples/color-picker
- examples/combobox
- examples/copyable-text
- examples/counter-broadcast
- examples/counter-global
- examples/counter-multicast
- examples/counter-unicast
- examples/dashboard
- examples/date-picker
- examples/date-picker-trigger
- examples/db
- examples/db-todo
- examples/dropdown
- examples/facepile
- examples/file-stream
- examples/file-upload
- examples/file-upload-compact
- examples/footer
- examples/form
- examples/form-frame
- examples/form-frame-path
- examples/form-markup
- examples/form-template
- examples/form-visibility
- examples/frame
- examples/frame-path
- examples/glider-gun
- examples/graphics-clock
- examples/graphics-hilbert
- examples/graphics-path
- examples/graphics-primitives
- examples/graphics-spline
- examples/graphics-turtle
- examples/hash-routing
- examples/hash-routing-parameters
- examples/header
- examples/hello-world
- examples/http-client
- examples/image
- examples/image-annotator
- examples/index
- examples/issue-tracker
- examples/label
- examples/layout
- examples/layout-responsive
- examples/layout-size
- examples/link
- examples/links
- examples/markdown
- examples/markdown-data
- examples/markdown-submit-text
- examples/markdown-table
- examples/markup
- examples/menu
- examples/message-bar
- examples/meta-dialog
- examples/meta-dialog-closable
- examples/meta-icon
- examples/meta-inline-script
- examples/meta-inline-script-callback
- examples/meta-inline-stylesheet
- examples/meta-notification
- examples/meta-notification-bar
- examples/meta-notification-bar-closable
- examples/meta-redirect
- examples/meta-refresh
- examples/meta-script
- examples/meta-script-callback
- examples/meta-side-panel
- examples/meta-side-panel-closable
- examples/meta-stylesheet
- examples/meta-theme
- examples/meta-title
- examples/meta-tracking
- examples/ml-dai
- examples/ml-dai-autodoc
- examples/ml-dai-categorical
- examples/ml-dai-instances
- examples/ml-dai-parameters
- examples/ml-dai-save
- examples/ml-h2o
- examples/ml-h2o-algo
- examples/ml-h2o-categorical
- examples/ml-h2o-parameters
- examples/ml-h2o-save
- examples/ml-h2o-shap
- examples/nav
- examples/persona
- examples/picker
- examples/picker-selection
- examples/pixel-art
- examples/plot-altair
- examples/plot-app
- examples/plot-area
- examples/plot-area-groups
- examples/plot-area-line
- examples/plot-area-line-groups
- examples/plot-area-line-smooth
- examples/plot-area-negative
- examples/plot-area-range
- examples/plot-area-smooth
- examples/plot-area-stacked
- examples/plot-axis-title
- examples/plot-bokeh
- examples/plot-bokeh-callbacks
- examples/plot-bokeh-script
- examples/plot-d3
- examples/plot-events
- examples/plot-events-disabled
- examples/plot-events-routing
- examples/plot-form
- examples/plot-histogram
- examples/plot-interaction-brush
- examples/plot-interaction-drag-move
- examples/plot-interaction-zoom
- examples/plot-interval
- examples/plot-interval-annotation
- examples/plot-interval-annotation-transpose
- examples/plot-interval-groups
- examples/plot-interval-groups-transpose
- examples/plot-interval-helix
- examples/plot-interval-labels
- examples/plot-interval-polar
- examples/plot-interval-polar-stacked
- examples/plot-interval-range
- examples/plot-interval-range-transpose
- examples/plot-interval-stacked
- examples/plot-interval-stacked-grouped
- examples/plot-interval-stacked-grouped-transpose
- examples/plot-interval-stacked-transpose
- examples/plot-interval-theta
- examples/plot-interval-theta-stacked
- examples/plot-interval-transpose
- examples/plot-line
- examples/plot-line-annotation
- examples/plot-line-groups
- examples/plot-line-labels
- examples/plot-line-labels-custom
- examples/plot-line-labels-no-overlap
- examples/plot-line-labels-stroked
- examples/plot-line-smooth
- examples/plot-matplotlib
- examples/plot-pandas
- examples/plot-path
- examples/plot-path-point
- examples/plot-path-smooth
- examples/plot-plotly
- examples/plot-point
- examples/plot-point-annotation
- examples/plot-point-custom
- examples/plot-point-groups
- examples/plot-point-map
- examples/plot-point-shapes
- examples/plot-point-sizes
- examples/plot-polygon
- examples/plot-schema
- examples/plot-schema-transpose
- examples/plot-step
- examples/plot-step-after
- examples/plot-step-before
- examples/plot-theme
- examples/plot-vega
- examples/plot-vegalite
- examples/plot-vegalite-flex
- examples/plot-vegalite-form
- examples/plot-vegalite-update
- examples/post
- examples/preview
- examples/profile
- examples/progress
- examples/progress-update
- examples/range-slider
- examples/routing
- examples/routing-predicates
- examples/separator
- examples/site-async
- examples/slider
- examples/spinbox
- examples/spinbox-trigger
- examples/stat-large
- examples/stat-large-bar
- examples/stat-small
- examples/stat-small-series-area
- examples/stat-small-series-interval
- examples/stat-table
- examples/stat-tall-gauge
- examples/stat-tall-series-area
- examples/stat-tall-series-interval
- examples/stat-wide-bar
- examples/stat-wide-gauge
- examples/stat-wide-pie
- examples/stat-wide-series-area
- examples/stat-wide-series-interval
- examples/stepper
- examples/swatch-picker
- examples/tab
- examples/tab-delete
- examples/table
- examples/table-download
- examples/table-filter
- examples/table-filter-backend
- examples/table-groupby
- examples/table-groups
- examples/table-markdown
- examples/table-markdown-pandas
- examples/table-menu
- examples/table-pagination
- examples/table-pagination-download
- examples/table-pagination-filter
- examples/table-pagination-groups
- examples/table-pagination-h2o3
- examples/table-pagination-minimal
- examples/table-pagination-pandas
- examples/table-pagination-search
- examples/table-pagination-sort
- examples/table-search
- examples/table-select
- examples/table-sort
- examples/table-tags
- examples/tabs
- examples/tags
- examples/tall-article-preview
- examples/tall-info
- examples/tall-stats
- examples/template
- examples/template-data
- examples/text
- examples/text-annotator
- examples/text-sizes
- examples/textbox
- examples/textbox-trigger
- examples/theme-generator
- examples/time-picker
- examples/todo
- examples/toggle
- examples/toolbar
- examples/toolbar-routing
- examples/upload
- examples/upload-async
- examples/upload-download
- examples/upload-frame
- examples/upload-ui
- examples/wide-article-preview
- examples/wide-info
- examples/wide-plot
- examples/wizard
- expressions
- files
- getting-started
- graphics
- guide
- icons
- installation
- installation-8-20
- javascript
- layout
- logging
- migrating-0
- migrating-0-8
- pages
- plotting
- realtime
- routing
- scripts
- security
- state
- tutorial-beer
- tutorial-counter
- tutorial-hello
- tutorial-monitor
- tutorial-todo
- wave-ml
- wavedb
    at Object.checkSidebarsDocIds (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/utils.js:181:19)
    at addDocNavigation (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:207:19)
    at doLoadVersion (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:106:55)
    at async loadVersion (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:113:28)
    at async Promise.all (index 0)
    at async Object.loadContent (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:121:33)
    at async /mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:35:25
    at async Promise.all (index 0)
    at async loadPlugins (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:34:27)
    at async load (/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave/website/node_modules/@docusaurus/core/lib/server/index.js:76:58)
[INFO] Docusaurus version: 2.1.0
Node version: v16.17.0

Any assistance on this would be greatly appreciated!

**Comment by aalencar** [comment]
After cloning the repo, did you run `make all` in the root folder?

**Comment by mturoci** [comment]
Hey @BBentleyDev, it's indeed the best if you could run `make all` to prepare for every aspect of Wave development. However, it's also perfectly fine with starting small. I updated [docs installation instructions](https://github.com/h2oai/wave/blob/master/website/README.md#installation), hope it can help :) Feel free to comment here in case you need any further assistance.

**Comment by YashasviChaurasia** [comment]
@BBentleyDev 
Feel free to reach out.
I am willing to help you with this issue.

**Comment by BBentleyDev** [comment]
Thanks for all the assistance! I tried following the new instructions linked above and got the 'make generate' command, when I run it I get the following error:

./venv/bin/python showcase.py
make[1]: Entering directory '/mnt/c/Users/bentl/OneDrive/Desktop/100Devs/open-source-practice/wave'
go run cmd/wave/main.go -web-dir ./ui/build -debug -editable -proxy -public-dir /assets/@./assets
Cannot connect to Wave server, retrying...
Cannot connect to Wave server, retrying...
Cannot connect to Wave server, retrying...
Done
Traceback (most recent call last):
  File "showcase.py", line 231, in <module>
    main()
  File "showcase.py", line 209, in main
    raise Exception('Could not connect to Wave server.')
Exception: Could not connect to Wave server.
make: *** [Makefile:14: generate] Error 1

**Comment by BBentleyDev** [comment]
Following the instructions in the main contributing docs I was able to get the wave server running on local host. So I went back to the instructions in the website readme, and when running the generate command get the following error:


╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo playwright install-deps                           ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
make: *** [Makefile:14: generate] Error 1


When I run the suggested command I get:

sudo: playwright: command not found

**Comment by mturoci** [comment]
Interesting, never seen that before (probably windows issue). The reason the command is not found is that you need to be within a python virtual env and the corresponding folder first:

```sh
cd tools/showcase
source venv/bin/activate
sudo playwright install-deps
```

This also assumes you have run `make setup` within `tools/showcase` before thus having the `venv` folder created.

**Comment by mturoci** [comment]
Hi @BBentleyDev any updates? Feel free to use [Discord server](https://discord.gg/GsyvWgzevv) for more real-time help. In case of inactivity I will free up this issue for other to grab.

**Comment by YashasviChaurasia** [comment]
@mturoci 
Kindly allow me to work on this if this issue is freed up.
I would like to work on this.
Thank you

**Comment by Mukul-svg** [comment]
Hi, I would like to work on this issue. Also since I'm a beginner please explain about it a bit.

**Comment by mturoci** [comment]
Hi @Mukul-svg. Unfortunately, this issue is already taken by @BBentleyDev and in case he will abandon it, @YashasviChaurasia will take over. Feel free to grab some other good first issue though :)

**Comment by Mukul-svg** [comment]
Sure, Thank you very much for replying.

**Comment by mturoci** [comment]
@YashasviChaurasia you are good to go. I will reopen your previous PR so you can continue to work there.

**Comment by BBentleyDev** [comment]
Sorry for the delay, I could not get it to work on my machine. Good luck moving forward!

**Comment by mturoci** [comment]
Since 4 days have passed, this issue is up for grabs again for anyone who would like to work on it.

**Comment by rubyruins** [comment]
Hi @mturoci, I'd like to contribute to wave and have the server set up and running. Can I work on this issue for Hacktoberfest?

**Comment by mturoci** [comment]
Go for it @rubyruins! You have 4 days for completion before this issue becomes up for grabs again. Good luck!

**Comment by JacksonIsaac** [comment]
Would like to work on this next :)

**Comment by JacksonIsaac** [comment]
@mturoci Wasn't sure where you wanted the star count to be exactly, but I have placed it under the Introduction section of Getting started. Let me know how it looks and if we want to move it somewhere around
