### ISSUE TITLE
Download table content with icons as CSV

### ISSUE THREAD

**Issue by shamilh2o** [h2oai/wave#1626]
#### Is your feature request related to a problem? Please describe

I was using default download feature in the wave tables. In my table it contains some icons which I need to display in downloaded CSV file as it is. But it shows some other characters in cells where those icons placed. 

Table UI:
![image](https://user-images.githubusercontent.com/101506482/190659721-92c6e9d7-7ccd-4f87-ac39-7488dc97d9bc.png)

Expected cell in downloaded CSV:
![image](https://user-images.githubusercontent.com/101506482/190659883-53783bdc-9a25-48a0-be26-7c2f0ab596af.png)

Currently receiving output:
![image](https://user-images.githubusercontent.com/101506482/190660059-0cfc23d0-7e6f-4988-a958-19761eff2b25.png)

#### Describe the solution you'd like

Contain icons used in wave table cells as it is in the downloaded CSV file. 

#### Describe alternatives you've considered

Use separate button to download CSV after including meaningful text instead of icons. But this not includes icons as it is. Just replacing icons with meaningful names. 

#### Additional context

Discussion is in https://github.com/h2oai/wave/discussions/1624
cc: @mturoci

**Comment by mturoci** [comment]
Implementation notes: [table download function](https://github.com/h2oai/wave/blob/6c51267b5359fb09da8a342cfe47a277c17dbeae/ui/src/table.tsx#L576) creates blob that doesn't keep unicode chars and needs to be rewritten as described [here](https://stackoverflow.com/questions/18249290/generate-csv-for-excel-via-javascript-with-unicode-characters).

**Comment by InfasMohammed** [comment]
Hi, can I take up this issue?

**Comment by mturoci** [comment]
Hi @InfasMohammed. Sure, it's yours.

**Comment by InfasMohammed** [comment]
![image](https://user-images.githubusercontent.com/87384090/193511740-cf4fd9a7-d188-4df2-a9db-9f38181a6bd6.png)
i have this issue

**Comment by mturoci** [comment]
Please follow the [dev setup instructions in contribution guidelines](https://wave.h2o.ai/docs/contributing/#development-setup). Once done, run the `table.py` example as it's relevant to this issue.

Note that your 4 days have already passed though which means this issue is again up for grabs for anyone interested. You may continue to work on it on your own if you want though.

**Comment by InfasMohammed** [comment]
I will continue

**Comment by JacksonIsaac** [comment]
Is this issue still up for grabs ? I have the wave server running

**Comment by mturoci** [comment]
Yes, go for it @JacksonIsaac!

**Comment by JacksonIsaac** [comment]
I tried the changes, and tested by changing the examples/table files to have a unicode object. It works, but I would like to reproduce the same above scenario.

Any ideas on how I can reproduce the above please ?

**Comment by mturoci** [comment]
You need to create a table with '❌' and '✅' as described [here](https://github.com/h2oai/wave/discussions/1624#discussioncomment-3660796).

**Comment by JacksonIsaac** [comment]
Figured it out, thanks :) I spent hours on this, just to realize I myself had a bug in my example unicode :D
