### ISSUE TITLE
Offer more control over item placements on cards 

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#1644]
This is a feature request based on the following discussion: [Is it possible to put items to bottom of a card?](https://github.com/h2oai/wave/discussions/1641)

It would be nice if we had a general mechanism to place items on certain areas on a card. Personally, I would at least find these 2 options useful:
- be able to center elements on a card
- allow to put elements at the bottom of a card (but could also be useful for "top right" etc.)

**Comment by mturoci** [comment]
Maybe [this](https://github.com/h2oai/wave/pull/1737) is what is needed?
