### ISSUE TITLE
Tags are hard to read with certain default colors

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#1647]
#### Wave SDK Version, OS

wave 0.23.1

#### Actual behavior

For example `yellow` with theme `h2o-dark` :

![grafik](https://user-images.githubusercontent.com/6949295/193032459-938dd5d5-fc57-4cc9-bbdc-00de84efd17d.png)

#### Expected behavior

- better readability

#### Steps To Reproduce

Use `ui.tag` with `color="yellow"`

**Comment by mturoci** [comment]
Edit: looking at the docstring - `If not specified, black or white will be picked based on correct contrast with background` this is what should already happen so it's a bug after all. Thanks for reporting! The solution still stands though.

**Comment by Far0n** [comment]
> Edit: looking at the docstring - `If not specified, black or white will be picked based on correct contrast with background` this is what should already happen so it's a bug after all. Thanks for reporting! The solution still stands though.

yeah, that's what confused me, because when I pass a "custom yellow" the font becomes black and hence readability is fine:
![grafik](https://user-images.githubusercontent.com/6949295/193035480-d21740dd-7ab6-4803-84f0-55fa8a10049e.png)

**Comment by mturoci** [comment]
Most likely you hit an edge case for our [contrast function](https://github.com/h2oai/wave/blob/badd8a9191283bcb0927a88dfc3b82ef00774a92/ui/src/theme.ts#L76).

**Comment by Far0n** [comment]
fyi: with #fdfd2d (color picked from screen):
![grafik](https://user-images.githubusercontent.com/6949295/193036408-833a242a-fac8-4d02-ab9b-d3bb65273d70.png)

**Comment by mturoci** [comment]
For whoever ends up taking this: We can try replacing the current contrast function with `Fluent.isDark` and see if it handles the edge cases better.

**Comment by mturoci** [comment]
After a closer look at the code, the root cause was that we were only expecting hex, RGB or Wave palette colors (prefixed with `$`).

Will add support for all kinds of valid CSS colors.
