### ISSUE TITLE
Table: hidden searchable column 

### ISSUE THREAD

**Issue by epa095** [h2oai/wave#1650]
#### Is your feature request related to a problem? Please describe

We use a table to present a list of datasets. Each has some metadata we want to show (e.g name and description), but also some metadata we don't want to show, but which we want to be searchable in the table search feature (e.g list of column names and column descriptions for the dataset). 

#### Describe the solution you'd like

A table column could have a 'visible' toggle. If false then the column is not rendered, but can still be searched. 

#### Describe alternatives you've considered
The current workaround is to set the column type to icon, which "works", except it raises many javascript warnings and is a ugly hack.

**Comment by mturoci** [comment]
Hi @epa095,

you can create your own custom search like in [this example](https://wave.h2o.ai/docs/examples/table-filter-backend/) just by using the table with the data you want to have displayed and a separate textbox that would act as search.

If you would need even more control around all the table aspects (sorting, filtering etc.), you might want to have a look at [paginated table](https://wave.h2o.ai/docs/examples/table-pagination/).

Note: If you built any interesting Wave apps, please do not hesitate and [share them with us](https://github.com/h2oai/wave/discussions/1632)!

**Comment by mturoci** [comment]
Closing as answered, feel free to reopen in case of any further questions.
