### ISSUE TITLE
Add social icons to docs page header

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1653]
Replace the current Github link with an icon and include icons for Twitter and Discord. Replace the theme-changing icon with a more compact one.

## Current

![image](https://user-images.githubusercontent.com/64769322/193553303-ecdd2915-3e33-4cdb-995d-23ed5926c42e.png)

## Desired result

<img width="343" alt="image" src="https://user-images.githubusercontent.com/64769322/193552747-bc9a27f0-d623-4f21-a204-ec0cc696d270.png">

inspiration from - https://www.frontendinterviewhandbook.com/

## Links

Github - https://github.com/h2oai/wave
Twitter - https://twitter.com/intent/follow?screen_name=h2o_wave
Discord - https://discord.gg/V8GZFAy3WM

**Comment by GhoulMac** [comment]
Hii I would like to work on the Issue

**Comment by mturoci** [comment]
@i-m-karanagarwal since you arrived first, the issue will be assigned to you. You have 4 days for completion before the issue becomes up for grabs again.

@GhoulMac please direct any question regarding the installation to our [Discord server](https://discord.gg/mzw3Cd6v)

**Comment by mturoci** [comment]
@i-m-karanagarwal the documentation site is in `website` folder.
