### ISSUE TITLE
Alignment of table values

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#1659]
#### Is your feature request related to a problem? Please describe
Allowing different alignments of values in a table can beautify UI in some use-cases.

#### Describe the solution you'd like
Allow user to left / center / right align the values of a column (something like `justify` in `ui.table_column` with default='left' so nothing breaks / changes in UI of existing apps).

#### Additional context
This is purely for nicer UI, especially in scenarios when some of the table cell elements are markdown (where content can be center-aligned), it'll make it more consistent visually.

**Comment by Pooja444** [comment]
@mturoci I would like to work on this issue, can it be assigned to me, please? I have worked on the issue https://github.com/h2oai/wave/issues/1577 and now I have a good knowledge of how to develop UI changes so it'll probably help with this issue 😁

**Comment by mturoci** [comment]
Please go ahead @Pooja444!

**Comment by RedJOe-0608** [comment]
I'd like to contribute to this issue! Can I work on it?

**Comment by mturoci** [comment]
Hi @RedJOe-0608, this issue is currently taken by @Pooja444 but feel free to pick some other issue - there are still many left.

**Comment by Pooja444** [comment]
Thanks for assigning this to me @mturoci, I have raised a PR for this issue - https://github.com/h2oai/wave/pull/1670
This issue was awesome and I had fun contributing to it! Please review and let me know if I need to make any changes, thank you!
