### ISSUE TITLE
Support multiple spaces in components

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#1666]
#### Is your feature request related to a problem? Please describe
Components like `ui.stat` convert multiple spaces to single space.

#### Describe the solution you'd like
Support multiple spaces.

#### Describe alternatives you've considered
Detailed discussion here: https://github.com/h2oai/wave/discussions/1665

#### Additional context
It should be supported for all components where it's relevant.

**Comment by David-Egan** [comment]
I can pick this up if possible and explore replicating the HTML behavior with &nbsp;

**Comment by mturoci** [comment]
After a bit [more digging](https://stackoverflow.com/questions/46223593/why-is-nbsp-not-working) I found that using `\u00A0` as an extra space works even today.

```py
q.page['example'] = ui.tall_stats_card(
    box='1 1 2 4',
    items=[
        ui.stat(label='PARAMETER \u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0 NAME', value='125%'),
        ui.stat(label='PARAMETER NAME', value='578 Users'),
        ui.stat(label='PARAMETER NAME', value='25K')
    ]
)
```
