### ISSUE TITLE
Adjust Wave table search bar position 

### ISSUE THREAD

**Issue by shamilh2o** [h2oai/wave#1671]
#### Is your feature request related to a problem? Please describe

By default the search bar in a wave table is located in left hand corner. When the group by feature enabled it goes to right hand corner as shown in below images. 
![image](https://user-images.githubusercontent.com/101506482/196090928-033244cb-62de-4f5e-9919-9502cb0b3173.png)
![image](https://user-images.githubusercontent.com/101506482/196090943-b40f6b15-d687-46f8-bc67-a186e859a7ad.png)

I need a control to locate the search bar from our own. (left hand side or right hand side). I am looking to maintain consistency over the pages which are shown above and I like to keep search bar in right hand corner even I am not using group by feature. 

#### Describe the solution you'd like

Enable an API to adjust the positions of those search bar and group by dropdown.  

#### Describe alternatives you've considered

--

#### Additional context

If there is any alternative solution available happy to know it. Thank you.

**Comment by mturoci** [comment]
Instead of introducing an API switch for this, let's keep the searchbar always on the left side and group by on the right side.

**Comment by shamilh2o** [comment]
> Instead of introducing an API switch for this, let's keep the searchbar always on the left side and group by on the right side.

Yah that's even better. Thanks.

**Comment by aksy2512** [comment]
Hi, I would like to work on this issue

**Comment by mturoci** [comment]
It's all yours @aksy2512!

**Comment by buhaytza2005** [comment]
Can I give it a try? I looked at the code and seems as simple as swapping the order in the stack.

**Comment by mturoci** [comment]
Go ahead @buhaytza2005! It is simple, but not that simple. You need to cover cases when table is:

* both searchable and groupable
* only searchable
* only groupable

and make sure the corresponding widgets are always in the same place, no matter what.
