### ISSUE TITLE
Ability to have external links in tables

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1673]
#### Is your feature request related to a problem? Please describe
A table could have information where the end user may want to click to an external link - today this this could possibly be worked around using the `link` flag, the url as the row name, and the meta feature - but it only works if there is exactly one link per row and you never want users to be able to select rows or click rows and stay in-app

#### Describe the solution you'd like
Here is a list of possible solutions:

1. Add a `url` option to the the datatype of a column
2. Allow for html in table cells: `'<a href="https://example.com">https://example.com</a>'` is currently printed as is
3. Automatically know when things are links like `ui.text` does
4. 

#### Describe alternatives you've considered

The following would work for use cases where there is exactly 1 URL per row, and you never wanted people to interact with the table and stay in-app.

```python
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):
    if q.args.my_linky_table is not None and len(q.args.my_linky_table) > 0:
        q.page["meta"] = ui.meta_card(box="", redirect=q.args.my_linky_table[0])

    q.page["form"] = ui.form_card(
        box="1 1 4 4",
        items=[
            ui.table(
                name="my_linky_table",
                columns=[
                    ui.table_column(name="id", label="ID", link=False),
                    ui.table_column(name="link", label="Link", link=True),
                ],
                rows=[
                    ui.table_row(name="http://example.com", cells=["1", "Visit Website"])
                ]
            ),
        ]
    )
    
    await q.page.save()
```

**Comment by mturoci** [comment]
Table already supports markdown which might be what you are after - https://wave.h2o.ai/docs/widgets/form/table/#markdown-support.

**Comment by mturoci** [comment]
Closing as already completed.
