### ISSUE TITLE
Input Type shows "Text" in the dataset uploading field

### ISSUE THREAD

**Issue by KishaniKandasamy** [h2oai/wave#1675]
#### Wave SDK Version, OS
h2o_wave=0.22.0
Mac OS =  12.4

#### Actual behavior
I am trying to test the eScorer wave app. 
When testing the uploading dataset, the input type shows "**Text**" - The input type should be "File". 
(But  I am able to upload the dataset manually  when I am using the app.)
<img width="1781" alt="1" src="https://user-images.githubusercontent.com/53715187/197930723-cd724f8e-f13e-4757-b976-009d8cc2f1ab.png">

#### Expected behavior
The input type would be "File" So It could be tested 

#### Steps To Reproduce

1. Do this
2. Do that
3. Do something else

**Comment by mturoci** [comment]
Hi @KishaniKandasamy,

the file upload input for you to use is right below the textfield. We use textfield to show the uploaded filenames.

![image](https://user-images.githubusercontent.com/64769322/197978138-03f33d84-f1a2-46ee-a92c-5de5405edaf9.png)

**Comment by KishaniKandasamy** [comment]
Thanks @mturoci
