### ISSUE TITLE
Wave Studio App to Downloads page

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1677]
Bundle the .wave studio app and host it at https://s3.us-west-2.amazonaws.com/oss-apps.h2o.ai/index.html

**Comment by mturoci** [comment]
Seems like it's already [there](https://s3.console.aws.amazon.com/s3/object/oss-apps.h2o.ai?region=us-west-2&prefix=wave-studio/wave-studio-0.23.0.wave), just needed to add it to the `index.html`.
