### ISSUE TITLE
Tables Become Incorrectly Grouped in Meta/Dialog (Wave v0.16 --> v0.22+)

### ISSUE THREAD

**Issue by chelseanbr** [h2oai/wave#1687]
#### Wave SDK Version, OS
H2O Wave v0.22+ on macOS

#### Actual behavior
This is for Tables (ui.table) inside a Meta/Dialog. When upgrading Wave v0.16 --> v0.22+, Tables behave differently inside a Meta/Dialog when using "Group by."
(When the table is moved outside of the dialog and back to the main page/form, however, the table works as expected.)

For H2O Wave v0.22+, the issue happens when using "Group by" in a dialog table, selecting a group, and doing an action on it.
For example, in screenshot 1 below, I've Grouped by the column "Group" and selected the top group "Tap". 
![1](https://user-images.githubusercontent.com/29825155/200078718-f7eb83c9-c05e-4594-8488-97ebda091821.png)

When I do an action (with a bottom white button), the items get jumbled so the grouping becomes incorrect. See how items under "Tap" have changed and were incorrectly placed there in screenshot 2 below:
![2](https://user-images.githubusercontent.com/29825155/200078742-81abb09e-0cf1-489a-8c71-3e926a18dfd2.png)

***It only happens when using "Group by," so when selecting normally without the grouping, there's no such issue.***

#### Expected behavior
In Wave v0.16.0, the table used to be reset automatically and ungrouped, so there'd be no inconsistencies like this as shown below:

Wave v0.16.0 - Using "Group by" in a table, selecting a group, and doing an action on it:
![3](https://user-images.githubusercontent.com/29825155/200078733-813266a7-c16f-491b-814d-41263a4b55b2.png)

Wave v0.16.0 - The result after the action is that the table would be reset automatically and ungrouped so there's no incorrect grouping: 
![4](https://user-images.githubusercontent.com/29825155/200078753-1f0e1491-5ded-425c-a523-cbee385f7ca9.png)

#### Steps To Reproduce
Please see "Actual behavior" above.

**Comment by mturoci** [comment]
Thanks for reporting @chelseanbr! @marek-mihok please have a look at this once you have time.
