### ISSUE TITLE
Enhance docs search experience

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1727]
#### Is your feature request related to a problem? Please describe

Current search works, but its results could be ordered better. E.g. if I search for a table I get

<img width="631" alt="image" src="https://user-images.githubusercontent.com/64769322/205017179-595b6d17-7cba-4004-b965-16a3e4ade182.png">

It would be better if **Widgets** section was prioritized since it's more documented than the **Examples** section, thus provides a more thorough info.

Similar when I search for _color_, I get **blog** results first instead of the **guide** ones.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/64769322/205017688-42d13f64-be34-4a13-928a-2d4e384df5be.png">

**Comment by nhadlaw** [comment]
Me and my teammate @SiddharthParatkar would like to work on this issue

**Comment by nhadlaw** [comment]
Which file would this be located under?

**Comment by mturoci** [comment]
Thanks for your interest @nhadlaw! This issue is not suited for external contributors as it requires access to [Algolia](https://www.algolia.com/) to properly develop and test against. I suggest picking a different issue if interested.

**Comment by mturoci** [comment]
Configured at https://crawler.algolia.com/ by setting a negative [pageRank](https://docsearch.algolia.com/docs/record-extractor#pagerank) to `examples` pages so that the widget pages are always on top.
