### ISSUE TITLE
Add spinner attribute to ui.progress

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1747]
via @shihan007 

Wave currently supports only [loading bar progress](https://wave.h2o.ai/docs/widgets/form/progress/). However, it would be great if we allowed for [Spinner version](https://developer.microsoft.com/en-us/fluentui#/controls/web/spinner) as well.

![image](https://user-images.githubusercontent.com/64769322/206710781-46f0d9e5-9ea1-4cc0-bd8c-98122b263eea.png)

## Implementation steps

* Implement the necessary changes in `progress.tsx`.
* Run `make generate` to generate python/R API.
* Update `progress.py` example.
* Update `progress.md` docs.

**Comment by yashh-dev** [comment]
I will create a fork and start working on this
will link the repo here..

**Comment by tuhinmallick** [comment]
Is this issue still open, if yes i would like to work on it

**Comment by mturoci** [comment]
Hey @tuhinmallick. We already have #1771 PR for this one, but feel free to pick any other good first issue :)
