### ISSUE TITLE
Events not fired for the notification_bar

### ISSUE THREAD

**Issue by senalw** [h2oai/wave#1763]
#### Wave SDK Version, OS

Wave 0.24.1, MacOs

#### Actual behavior

When I click the close button of the notification bar, it's suppose to trigger `dismissed` event which is defined in the `events=[dismissed]`. 

#### Expected behavior
But actual behaviour is `dismissed` event is not firing, but notification bar getting closed from the UI when I click on close 'X' button in notification bar. 

Because of this issue, notification bar appears for every events in the event loop as it's not setting to `q.page["meta"].notification_bar = None` in the dismissed event. 

https://user-images.githubusercontent.com/12801761/207831095-ae26c065-5b5f-4030-ba01-5d42858a4efc.mov

#### Steps To Reproduce
You can run the following code to create the issue:

```py
@app('/')
async def serve(q: Q):
    if not q.client.initialized:
        # Create an empty meta_card to hold the notification bar
        q.page['meta'] = ui.meta_card(box='')
        # Display a button to show the notification bar
        q.page['form'] = ui.form_card(box='1 1 2 4', items=[
            ui.button(name='show_notification_bar', label='Show notification bar'),
            ui.button(name="show_side_panel", label="Show side panel")
        ])
        q.client.initialized = True

    # Was the show_notification_bar button clicked?
    if q.args.show_notification_bar:
        # Create a notification bar
        q.page['meta'].notification_bar=ui.notification_bar(
            text='You can close me!',
            name="my_bar",
            # Get notified when the notification bar is dismissed.
            events=['dismissed'],
        )
    if q.args.show_side_panel:
        q.page["meta"].side_panel = ui.side_panel(
        title="",
        items=[ui.text("Side panel text")],
        name="side_panel",
        events=["dismissed"],
        closable=True,
    )

    # Did we get events from the notification bar?
    if q.events.my_bar:
        # Was the notification bar dismissed?
        print("events triggered")
        if q.events.my_bar.dismissed:
            # Delete the notification bar
            print("dismissed")
            q.page['meta'].notification_bar = None

    if q.events.side_panel:
        if q.events.side_panel.dismissed:
            print("side panel dismissed")
            q.page["meta"].side_panel = None

    await q.page.save()
```

**Comment by mturoci** [comment]
Thanks for filling the issue!

Unfortunately, I cannot repro either on 0.24.1 or 0.24.2. Can you try `0.24.2` and see if the problem persists? Also, I would need more details about:

* Your browser.
* Your python version.
* How you run your app.

**Comment by senalw** [comment]
> Thanks for filling the issue!
> 
> Unfortunately, I cannot repro either on 0.24.1 or 0.24.2. Can you try `0.24.2` and see if the problem persists? Also, I would need more details about:
> 
> * Your browser.
> * Your python version.
> * How you run your app.

@mturoci I'm sorry! it's my fault as my wave daemon was pointed to 0.21.1 version when I'm doing this. That was the issue and it's perfectly working with right daemon version.  
Sorry for the inconvenience occurred. We can close this issue.

**Comment by mturoci** [comment]
No problem @senalw, glad it got resolved! :)
