### ISSUE TITLE
Dropdown's choices don't dock to dropdown

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/wave#177]
**Q SDK Version, OS**
(e.g. 0.6.0, Mac)

**Actual behavior**
 Dropdown menu is offset for a wide form card

**Expected behavior**
Dropdown menu should be shown directly under drop down

**Steps To Reproduce**
This is the code I have:
```
main_box = '4 2 0 -1'    
q.page['menu'] = ui.form_card(
        box=menu_box,
        items=[]
    )
```
which gives
![Screen Shot 2020-09-29 at 1 06 25 PM](https://user-images.githubusercontent.com/10055668/94612810-7d730680-0258-11eb-8588-9849797ed278.png)

**Comment by mturoci** [comment]
Closing as duplicate.
