### ISSUE TITLE
Allow for no selected tab in tabs group

### ISSUE THREAD

**Issue by johannes-becker-otto** [h2oai/wave#1776]
#### Is your feature request related to a problem? Please describe

My application is starting to have too many tabs. At the same time tabs are nice to switch back and forth. My first approach was to add a menu.
Thanks to v 0.24.0 adding labels to menus this even looks quite smooth.
But now, when I use a link from the menu I get the following situation where the tab marking doesn't match the rest
![image](https://user-images.githubusercontent.com/97096714/210323980-4394ac5c-81b3-43bc-b579-55664fa7f98b.png)

#### Describe the solution you'd like

I found old threads about similar discussion (two sets of tabs) and understand that there is no complete solution.
My suggestion would be that if you set for ui.tabs value=None then none of the tabs is highlighted.
This would probably be practical for a few scenarios (e.g. you have a Welcome page that is not part of your tabs).

**Comment by mturoci** [comment]
Makes sense (although not sure if for your scenario), will be done as part of #1154.

However, as for the UX standpoint, you should always let your users know where they currently are within the navigation hierarchy. This means there should be always exactly 1 active tab at all times.

**Comment by johannes-becker-otto** [comment]
"This means there should be always exactly 1 active tab at all times."
I agree, the underlying problem is a mix of navigations (part tabs, part menu).
Will have to rethink that part as well...

**Comment by mturoci** [comment]
If you have too many nav items, maybe it will be better to replace the header with a [sidenav](https://wave.h2o.ai/docs/widgets/content/navigation/) which can accommodate more items.

**Comment by mturoci** [comment]
@marek-mihok please verify if this is resolved with the recent changes for #1154. If yes, close this one.

**Comment by marek-mihok** [comment]
@mturoci the current implementation (even after #1154) is that you must have 1 tab selected at a time. When the value is set to `None`, the first tab is being highlighted as a default.
