### ISSUE TITLE
Add support for time columns in ui.table()

### ISSUE THREAD

**Issue by tkmaker** [h2oai/wave#178]
**Q SDK Version, OS**
0.6.0

**Actual behavior**
Included a timestamp column and see errors creating a card. 

`TypeError: Object of type Timestamp is not JSON serializable`

Works fine if I exclude the timestamp column

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**Steps To Reproduce**
1. Do this
2. Do that
3. Do something else

**Comment by mtanco** [comment]
For any pandas-users who find this issue, you can use the following to format your timestamp as expected:
```python
fake["timestamp"] = fake["timestamp"].apply(lambda d: pd.Timestamp(d).isoformat())
```
