### ISSUE TITLE
Allow specifying height and direction for ui.inline

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1780]
Some users might want to display form items in the middle of the card (e.g. login form). Wave currently provides a `ui.inline` which has `align` and `justify` attributes that could be of help.

However, the current `ui.inline` container only stretches as far as its content. We would need to make it stretch to either custom height (`px`, `vh`, `rem` CSS units) or to fill all the remaining space of the card (by specifying `1` for example).

And since the `ui.inline` is currently a horizontal container only, we might also want to introduce either a differently named component with the same abilities but vertical direction or add a `direction` attr to the existing `ui.inline`.

cc @lo5 for discussion

**Comment by n-srinidhi** [comment]
Hi!Is there any update on this feature?

**Comment by mturoci** [comment]
https://github.com/h2oai/wave/pull/1820. Will be part of the next release.
