### ISSUE TITLE
Setting Integer value for the value and aux_value of a Stat Series Card

### ISSUE THREAD

**Issue by n-srinidhi** [h2oai/wave#1781]
Wave  Version 0.24.2, Windows

Not able to directly set the `value` field of a Stat Series Card to an integer value. Currently, it is necessary to specify `aux_value` even if it is not required for the particular use case. Trying to set an integer values gives me a blank page. Following is the reproducible code:

```
user_stat=ui.wide_series_stat_card(
    box='u_stat',
    title='Users Logged in',
    value='5',
    aux_value='',
    plot_data=data(fields=['date','count'], rows=[['22-11-24', 1], ['22-11-25', 2], ['22-11-26', 3]]),
    data={'22-11-26': 3},
    plot_type='area',
    plot_value='count',
    plot_color='$blue',
    plot_zero_value=0,
    plot_curve='linear',
)
```
I have also opened a [discussion](https://github.com/h2oai/wave/discussions/1778) regarding this and got a temporary work around. However, It would be useful if we can set integer values to the `value` field in the stat card and  make the `aux_value` optional

**Comment by mturoci** [comment]
Fixed in https://github.com/h2oai/wave/commit/0c13f33ba7828ed4e9642de176c1736eb8a8378c. Will be available in tomorrow's nightly for you to check.
