### ISSUE TITLE
Customize Login Form for Third Party Authentication Server

### ISSUE THREAD

**Issue by n-srinidhi** [h2oai/wave#1793]
Hi! Currently h2o.ai Wave supports authentication for Login via OIDC which means you need to either run your own auth server or reuse some existing one. Referring to the [discussion](https://discord.com/channels/1022255416454946906/1058238973362851910) on Discord
 Right now, Its not possible to customize the login pages, But if it is implemented in subsequent versions it will be super useful! While designing a web app using Wave, not being able to customize the login pages kind of breaks the whole consistent display across the  web app. Thanks!

**Comment by n-srinidhi** [comment]
Hi! Is there any update on when this will be available?Thanks!

**Comment by mturoci** [comment]
Hey @n-srinidhi. There is `H2O_WAVE_OIDC_SKIP_LOGIN` option to skip directly to your OIDC provider login form (no need to click through the ugly Wave screen with a single button). The customizations then depend on the particular provider. 

Closing as completed since there is not much left to do.

**Comment by n-srinidhi** [comment]
@mturoci So Is it possible for me to design a fancy login form using Wave and use an OIDC server backend for authentication?

**Comment by mturoci** [comment]
Yes and no. Keycloak login page can be customized (a quick google search yielded https://www.baeldung.com/keycloak-custom-login-page), but since no OIDC provider is built using Wave, you can only use HTML/CSS.
