### ISSUE TITLE
TLS handshake error logged for self-signed SSL cert.

### ISSUE THREAD

**Issue by MaksymSofer** [h2oai/wave#1805]
#### Wave SDK Version, OS
OS:
Ubuntu 20.04.5

Waved:
DEV 20230121020107 (pr for handling headers)
24.2

#### Actual behavior
Browser is able to open wave page with blinking wave icon
"wave run app" not able to connect to waved with exception;
```
2023/01/21 22:48:06 http: TLS handshake error from 127.0.0.1:55814: EOF
```
#### Expected behavior

"wave run app" talk to waved
browser talk to waved 

#### Steps To Reproduce
Per docs HTTPS supposed to be setup in the following way:
1. generate the key with openssl = Done
2. execute waved with : ```waved -tls-cert-file domain.crt -tls-key-file domain.key``` - done
(i copied to files to my project directory)
3. execute ```wave run --no-autostart app```

Plus:
PLEASE - provide \ document how to run waved on different ip \ port

**Comment by mturoci** [comment]
> PLEASE - provide \ document how to run waved on different ip \ port

https://wave.h2o.ai/docs/configuration/#how-to-start-a-wave-app-on-a-different-port

> execute waved with : waved -tls-cert-file domain.crt -tls-key-file domain.key - done
(i copied to files to my project directory)

Seems like your paths are incorrect, they need to be relative to the waved location, not relative to the project. Can you either try using abs paths or putting the files next to the waved and let me know if worked?

**Comment by mturoci** [comment]
In that case, you need to set `H2O_WAVE_ADDRESS` to tell your app the URL of your Wave server, defaults to `http://localhost:10101`, but should be set to `https` instead.

```sh
H2O_WAVE_ADDRESS="https://127.0.0.1:10101" wave run app
```

Or whatever https URL you are using for your waved.

Need to update docs to prevent confusion.

**Comment by MaksymSofer** [comment]
Corrected my previous comment to be more precise.
I will try to with these parameters

**Comment by MaksymSofer** [comment]
waved require root permissions when port specified :(

i set both variables
H2O_WAVE_ADDRESS
H2O_WAVE_LISTEN

started waved as root , otherwise:
```
{"error":"listen tcp :443: bind: permission denied","t":"listen_tls"}
```

but wave still show this:
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [232626] using StatReload
2023/01/23 08:40:45 http: TLS handshake error from 127.0.0.1:46940: EOF
INFO:     Started server process [232629]
INFO:     Waiting for application startup.
2023/01/23 08:40:47 # {"host":"http://127.0.0.1:8000","route":"/","t":"app_add"}
INFO:     Application startup complete.
```

**Comment by mturoci** [comment]
> waved require root permissions when port specified

That's a UNIX default, not wave-related.

Any other random port should work fine. Seems like you can [tweak it](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443) if you want though.

**Comment by MaksymSofer** [comment]
I`m more interested in main issue

**Comment by mturoci** [comment]
Which one?

**Comment by MaksymSofer** [comment]
2023/01/23 08:40:45 http: TLS handshake error from 127.0.0.1:46940: EOF

**Comment by mturoci** [comment]
But this doesn't happen with root privileges, right?

The reason is that some ports (like 443 or 80) are standard ports on UNIX, thus if you want your machine to make it listen on any of those, you need to provide root access or configure it in a way it's not needed. This is true for any service you would want to make listen on these special ports - it's handled by the OS. Using any other non-standard port (like the default 10101) is supposed to work without root privileges. Please try it and get back with the results.

Steps:
1. Start waved on 10101 with the cert provided.
2. Start wave app with `H2O_WAVE_ADDRESS="https://127.0.0.1:10101"`.

**Comment by MaksymSofer** [comment]
sadly it does - the above comment https://github.com/h2oai/wave/issues/1805#issuecomment-1399980413
I executed with root permissions
and still wave on startup print out :
```
2023/01/23 08:40:45 http: TLS handshake error from 127.0.0.1:46940: EOF
```
the question - is this expected behavior?

**Comment by mturoci** [comment]
I see. Can you paste your terminal commands and their outputs?

**Comment by MaksymSofer** [comment]
```
root@backoffice:/home/azureuser/backoffice/venv# ./waved -tls-cert-file /home/azureuser/domain.crt -tls-key-file /home/azureuser/domain.key &
[1] 232406
root@backoffice:/home/azureuser/backoffice/venv# 2023/01/23 08:36:40 #
2023/01/23 08:36:40 # ┌────────────────┐ H2O Wave
2023/01/23 08:36:40 # │  ┐┌┐┐┌─┐┌ ┌┌─┐ │ DEV 20230121020107
2023/01/23 08:36:40 # │  └┘└┘└─└└─┘└── │ © 2021 H2O.ai, Inc.
2023/01/23 08:36:40 # └────────────────┘
2023/01/23 08:36:40 # ┌─────────────────────────────────────┐
2023/01/23 08:36:40 # │  Running at https://localhost:443/  │
2023/01/23 08:36:40 # └─────────────────────────────────────┘
2023/01/23 08:36:40 # {"address":":443","base-url":"/","t":"listen","web-dir":"/home/azureuser/backoffice/venv/www"}
```

```
(venv) azureuser@backoffice:~/backoffice$ venv/bin/wave run server.py &
[1] 232626
(venv) azureuser@backoffice:~/backoffice$ 443
INFO:     Will watch for changes in these directories: ['/home/azureuser/backoffice']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [232626] using StatReload
2023/01/23 08:40:45 http: TLS handshake error from 127.0.0.1:46940: EOF
INFO:     Started server process [232629]
INFO:     Waiting for application startup.
2023/01/23 08:40:47 # {"host":"http://127.0.0.1:8000","route":"/","t":"app_add"}
INFO:     Application startup complete.
```

**Comment by MaksymSofer** [comment]
enviroment variables are set for both user and root via export

**Comment by MaksymSofer** [comment]
```
azureuser@backoffice:~/backoffice$ printenv | grep H2O
H2O_WAVE_LISTEN=:443
H2O_WAVE_ADDRESS=https://172.18.1.5:443
```

**Comment by mturoci** [comment]
Seems like you are running Wave server and Wave app on different machines, right?

**Comment by MaksymSofer** [comment]
nope this is the same machine, i`m testing configuration before containerezation so i need to ensure that it will be able to use specific IP (vm has only two interfaces lo0 and eth0 - the stated IP is on eth0)

**Comment by mturoci** [comment]
Okay, seems like it works on my Mac, so will need to investigate further on Ubuntu. Will get back once I figure it out. Thanks for reporting!

**Comment by mturoci** [comment]
Just to further clarify, can you actually see your wave app in the browser?

**Comment by MaksymSofer** [comment]
yes, but load times increased like a threefold

**Comment by mturoci** [comment]
Well, TLS has to do a 3-way handshake which answers kinda answers that.

So to sum it up, everything works, the only problem is the warning you are getting, right?

**Comment by MaksymSofer** [comment]
now, after you shared the knowledge of variables only issues is warning - correct

**Comment by mturoci** [comment]
Do you use self-signed or CA-signed cert?

**Comment by MaksymSofer** [comment]
yes, per the manual generated with openssl

**Comment by mturoci** [comment]
I see. Just checked our appstore cloud environment and it seems like if regular CA-signed cert is used, no error is logged and everything works just fine so might be that. Giving this low-prio then. Please let me know if you run into this even with a normal signed cert.

**Comment by MaksymSofer** [comment]
I think we can mark this as expected behavior and just add to docs

**Comment by MaksymSofer** [comment]
@mturoci 
the documentation you committed is much better , thank you!
