### ISSUE TITLE
Copy text using copy icon

### ISSUE THREAD

**Issue by shihan007** [h2oai/wave#1809]
![image](https://user-images.githubusercontent.com/38729017/214293721-a64b0705-f0ed-467a-9dfe-415e62d7d64f.png)

It is important for users to copy their IDs by clicking on copy icon next to it. Right now we cannot do that using wave

**Comment by mturoci** [comment]
https://wave.h2o.ai/docs/widgets/form/copyable_text/

**Comment by shihan007** [comment]
@mturoci We cannot use this component for mentioned scenario since it does feel editable to the user.
