### ISSUE TITLE
Display image in a graphics_card

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1817]
via @DeeJaayArgh

### Discussed in https://github.com/h2oai/wave/discussions/1816

<div type='discussions-op-text'>

<sup>Originally posted by **DeeJaayArgh** January 30, 2023</sup>
I was looking in the docs about displaying an image in a ui.graphics_card and didn't find a good example.  I've been able to display a png file in an image_card but I'd like to get it in a ui.graphics_card to use as part of a scene.  Is this possible?</div>

### Description

Add new `image` (for base64) and `path` for regular image URLs to the existing `graphics_card`. If any of those 2 attributes is specified,  render the image as a card background. Graphics drawing should happen "on top of the image".

**Comment by theVJagrawal** [comment]
Can I work on this issue? I am pretty new to open source stuff

**Comment by mturoci** [comment]
Sure, go ahead @theVJagrawal!

**Comment by dohrisalim** [comment]
Are you still working on this issue @theVJagrawal?
@mturoci could you give us more information about this issue so we can get started on a fix? What file should we make changes in?

**Comment by mturoci** [comment]
You can go ahead @dohrisali.

> What file should we make changes in?

Try to make some due diligence yourself first. All the necessary info should be in the issue description. In case you have any further questions, drop them here.

**Comment by Pratyakshshiv** [comment]
@mturoci  is this issue still open if yes can you please assign this to me?

**Comment by mturoci** [comment]
All yours @Pratyakshshiv, go ahead.

**Comment by Pratyakshshiv** [comment]
> All yours @Pratyakshshiv, go ahead.

Thanks can you please guide me which file i have to make this changes to i tried to find the graphics_card which was mentioned in the description but looks like it's not a file.

**Comment by mturoci** [comment]
See the [contributing guide](https://github.com/h2oai/wave/blob/main/.github/CONTRIBUTING.md) first.

**Comment by mturoci** [comment]
Any updates @Pratyakshshiv?

**Comment by Gingaaa** [comment]
Hey I have worked on around 7-8 company based project, but never countribute to open source this is my first time can you assign me this task.

**Comment by mturoci** [comment]
Go ahead @Gingaaa. No assignment necessary :)

**Comment by nishitiwari22** [comment]
I am a beginner in open source and I really want to contribute to this task, may I?

**Comment by mturoci** [comment]
No need to ask for permission. Go ahead :) If you are new, I recommend going through [Contributing guide](https://github.com/h2oai/wave/blob/main/.github/CONTRIBUTING.md) first.

**Comment by bharateshwq** [comment]
This issue seems to be open,
i will start to work on it

**Comment by dbranley** [comment]
Hi, I submitted a PR for this change request. Let me know how it looks and if you would like any changes. Thanks!
