### ISSUE TITLE
bug: Plot tooltip display additional fields that are not present in the data 

### ISSUE THREAD

**Issue by dulajra** [h2oai/wave#1836]
via https://github.com/h2oai/wave/discussions/1832

#### Wave SDK Version, OS

0.24.2

#### Actual behavior

There are 2 issues on the tooltip. 

1. When the plot type is `interval` the ranged data (`x_min - x_max`) is included in the plot tooltip. But only `x_min`, `x_max` and `y` are present in data. 

<img width="1415" alt="plot tooltip" src="https://user-images.githubusercontent.com/12434380/218739039-94b4aaf7-625a-4bf4-89e5-061d1cf94120.png">

2. Both x1 and x2 have the timestamp and are in the same format. Here are some sample data. 

```
09 = {tuple: 3} ('2023-02-14T07:24', '2023-02-14T07:30', 50000)
10 = {tuple: 3} ('2023-02-14T07:30', '2023-02-14T07:35', 50000)
```

But on the tooltip, the time part is not visible only for x1.

#### Expected behavior

1. Only the fields in data should be visible in the plot tooltip. 
2. Both x1 and x2 in the tooltip should display both the date and time as in the data. 

#### Steps To Reproduce

Sample code

```
ui.visualization(
        plot=ui.plot(
            [
                ui.mark(
                    type="interval",
                    x='={{intl x_min type="time" dateStyle="short" timeStyle="short" }}',
                    x1='={{intl x_min type="time" dateStyle="short" timeStyle="short" }}',
                    x2='={{intl x_max type="time" dateStyle="short" timeStyle="short" }}',
                    x_scale="time",
                    x_title=histogram.x_label,
                    y_min=0,
                    y="=y",
                    y_title=histogram.y_label,
                    fill_color=SHOE_WAX,
                    stroke_color=IRON,
                    label_overlap="hide",
                )
            ]
        ),
        data=data(
            fields=["x_min", "x_max", "y"],
            pack=True,
            rows=[('2023-02-14T06:45', '2023-02-14T06:48', 0), ('2023-02-14T06:48', '2023-02-14T06:54', 0), ('2023-02-14T06:54', '2023-02-14T07:00', 0), ('2023-02-14T07:00', '2023-02-14T07:06', 0), ('2023-02-14T07:06', '2023-02-14T07:12', 0), ('2023-02-14T07:12', '2023-02-14T07:18', 0), ('2023-02-14T07:18', '2023-02-14T07:24', 0), ('2023-02-14T07:24', '2023-02-14T07:30', 15310), ('2023-02-14T07:30', '2023-02-14T07:36', 60000), ('2023-02-14T07:36', '2023-02-14T07:42', 24690), ('2023-02-14T07:42', '2023-02-14T07:45', 0)],
        ),
    )
```

**Comment by marek-mihok** [comment]
Tracked in #1841. 

@dulajra, regarding the second point

> Both x1 and x2 in the tooltip should display both the date and time as in the data.

just remove this line `x='={{intl x_min type="time" dateStyle="short" timeStyle="short" }}',`, for `type='interval'` plots should be `x1` and `x2` enough. cc: @mturoci

**Comment by mturoci** [comment]
> just remove this line x='={{intl x_min type="time" dateStyle="short" timeStyle="short" }}',

Why should it be removed?

**Comment by marek-mihok** [comment]
I'm sorry, I take it back. There's no need to remove it. Thanks @mturoci. 
Fix for both of addressed issues will be available in the next release.
