### ISSUE TITLE
Feature Request: Ability to render popup window based on an event

### ISSUE THREAD

**Issue by VijithaEkanayake** [h2oai/wave#1842]
#### Is your feature request related to a problem? Please describe
We have a requirement to render pop a window similar to the shared image based on a button click for multiple use cases. Can we introduce a popup component to wave SDK?

<img width="598" alt="Screenshot 2023-02-14 at 19 08 55" src="https://user-images.githubusercontent.com/112595851/220031927-8c7f7a6a-8a34-420a-a8a2-239ccfbd6d6a.png">

Here is a sample UX design we have,

https://user-images.githubusercontent.com/112595851/220032595-918d5fec-c21b-4d87-8cbb-207720d0b62f.mov

**Comment by vopani** [comment]
How is it different from `ui.dialog`?

**Comment by VijithaEkanayake** [comment]
@vopani We don't have a searchable popup component. If we use `ui.dialog` we have to manually implement this search I guess. The requested popup dialog component is exactly similar when a user click on a dropdown with `popup=always ` option.

**Comment by mturoci** [comment]
>Here is a sample UX design we have,

I recommend avoiding rendering more than 1 popup at the same time.

From https://www.nngroup.com/articles/popups/:

> Showing multiple popups one after another: Displaying multiple popups on top of each other makes your site look unprofessional, desperate, and disorganized. It also overwhelms users and forces them to spend effort to close each one. If your site uses many different types of popups, test the implementation to avoid presenting users with multiple popups at a time.

> we have to manually implement this search

Since the search can have many different looks and needs, it's best when done by yourself. Wave should provide you with everything you need - dialog, textbox, items list.
