### ISSUE TITLE
Support passing different date time string to table column with time datatype

### ISSUE THREAD

**Issue by VijithaEkanayake** [h2oai/wave#1846]
#### Is your feature request related to a problem? Please describe
Table column datatype with time doesn't accept custom data time string. for example we cannot pass string `28/01/2022 12:45:51` as an input to a table cell with time datatype. It renders as InvalidDate. 

When working with paginated tables we need to download table content as a csv file and date column values needs to be in this format `%d/%m/%Y %H:%M:%S`. Due to this limitation we cannot use same method to render paginated table rows and downloadable dates with above format.

#### Describe the solution you'd like
If we can provide date format as an input to table column definition would be beneficial for all the developers.

**Comment by mturoci** [comment]
> Table column datatype with time doesn't accept custom data time string. for example we cannot pass string 28/01/2022 12:45:51 as an input to a table cell with time datatype

Yes, this is by design currently. #1840 should help with that a bit, but still will not allow for custom hardcoded format due to internationalization reasons.

> When working with paginated tables we need to download table content as a csv file and date column values needs to be in this format %d/%m/%Y %H:%M:%S. Due to this limitation we cannot use same method to render paginated table rows and downloadable dates with above format

If you use paginated tables, you are in control of the download as well, meaning you can provide any CSV (with whatever format) you like. See https://wave.h2o.ai/docs/examples/table-pagination-download/.

**Comment by VijithaEkanayake** [comment]
> If you use paginated tables, you are in control of the download as well, meaning you can provide any CSV (with whatever format) you like. See https://wave.h2o.ai/docs/examples/table-pagination-download/.

@mturoci I was able to implement download table data based on the format that I needed. However, what worries me is, we cannot use the same data conversion logic for the table and the downloadable data. Looking forward to having that support in wave SDK.

**Comment by mturoci** [comment]
>Looking forward to having that support in wave SDK.

Not gonna happen due to internationalization reasons as stated in the prev comment.

>we cannot use the same data conversion logic for the table and the downloadable data

If you use paginated table and want to go for bad UX intentionally, then you can render your dates as strings since sorting needs to be handled server side anyway.

**Comment by VijithaEkanayake** [comment]
> Not gonna happen due to internationalization reasons as stated in the prev comment.
My bad, I misread your previous comment. I understand the complexities of supporting it. We'll introduce our own way to handle table content downloads. Thanks a lot.
