### ISSUE TITLE
Dashboard demo app: Render links within header directly

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#1867]
Render particular dashboard links in header directly, without the need of clicking on hamburger menu.

Current state:

![image](https://user-images.githubusercontent.com/64769322/222690737-67b7d20c-dff7-43cd-b0b7-12319a25a35c.png)

Desired state:

Header with [links](https://wave.h2o.ai/docs/widgets/content/header#with-links) or tabs + h2o logo present.

The app is located [here](https://github.com/h2oai/wave/tree/master/py/demo).

## Dev instructions

After [setting up the dev env](https://wave.h2o.ai/docs/contributing#development-setup) and running `make run` to start the server, run `cd py && ./venv/bin/wave run demo.app` from the project root in a separate terminal.

**Comment by dthiagarajan7** [comment]
@mturoci Hello! I'm new to open-source and would love to take up this issue. Could you please assign it to me?

**Comment by woohyoung** [comment]
Can I work on this issue please? I am new to open source stuff but I'd like to give it a try. Thank you.

**Comment by dthiagarajan7** [comment]
@woohyoung Hi, sorry but this issue has already been assigned to me. There are plenty of other open issues under the "good first issue" label that you could take a look at. Thanks.

**Comment by woohyoung** [comment]
Oh I see. Thanks for the reply.

**Comment by mturoci** [comment]
@dthiagarajan7 any progress on this one or can I open up this issue for others?

**Comment by dthiagarajan7** [comment]
@mturoci Hi, thank you for checking in. Yes, I have made some progress and was planning on finishing up and submitting the pull request (most likely) this weekend. Apologies for the delay. I'm a full-time student and had actually claimed this issue as part of an assignment for my software engineering class.

Please let me know if this is at all time sensitive so I can pursue this with more urgency.

**Comment by dthiagarajan7** [comment]
@mturoci Thank you for giving me the opportunity to work on this issue! I have submitted the pull request at #1934

**Comment by dthiagarajan7** [comment]
@mturoci Thank you for giving me the opportunity to work on this issue! I have submitted the pull request at #1935
