### ISSUE TITLE
Wave Apps: Feature Deprecation Python 3.7

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1873]
This is for updating the app.toml files of the following apps in this repo:
- [ ] Tour of Wave
- [ ] Wave University
- [ ] Dashboards 
- [ ] Themegenerator

https://github.com/h2oai/cloud-platform/issues/31

Python 3.10 will be the default runtime for apps in HAIC 23.04 and in 23.07 Python 3.7 will no longer be available. As a best practice, core apps should pin the runtime rather than using the system default. 

- [ ] Set the `RuntimeVersion` to  deb11_py310_wlatest for Python 3.10 (this will be the new default) in the 23.04.0 release in June
- [ ] Upload your app to cloud-dev to ensure it works as expected
- [ ] Let the #ai-app-store slack channel know if anything breaks so we can prioritize ensuring your app will work for customers when the new python release is set in June
- [ ] Create a new release of your app that explicitly sets the runtime rather than relying on the default

**Comment by mturoci** [comment]
As a side note, we might want to deprecate 3.7 for Wave as well, since it's not going to be maintained by Python core team anyway.

@mtanco is the runtime `deb11_py310_wlatest` supported as of today? (prior to 23.04).

**Comment by mtanco** [comment]
> As a side note, we might want to deprecate 3.7 for Wave as well, since it's not going to be maintained by Python core team anyway.
Yes, good idea

> @mtanco is the runtime deb11_py310_wlatest supported as of today? (prior to 23.04).
No, it's only in prerelease
