### ISSUE TITLE
Test Tour of Wave with Path-Based Routing

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#1875]
When deployed in H2O's AI App Store, apps can choose to do Path-Based routing or Domain based routing. The previous default was domain based, but more and more customers are moving to path-based to reduce costs and improve security. Tour of Wave does not have a preference set in the app.toml file and does whatever the system has as a default. Because this app relies so heavily on routing, I want to ensure it does work well in a path-based environment, and that we set this as the default if there are no issues. 

**Requirements:**
- [ ] Add the following line to your `app.toml` `[Runtime]` section: `RoutingMode = "BASE_URL"`
- [ ] Test that your app works as expected when published to an AI App Store

**Comment by marek-mihok** [comment]
I went through all the tour examples in path-based environment and here is a list of the examples which does not work as expected (I also attach recordings demonstrating the issue: Left tab - path-based; right tab - domain-based environment):

- `meta_title.py` and `meta_icon.py`

https://user-images.githubusercontent.com/23740173/234093257-5add48a4-973a-469b-a6ef-d78ef5be1e8e.mov

- `counter_broadcast.py`, `counter-multicast.py` and `counter-unicast.py`

https://user-images.githubusercontent.com/23740173/234095286-b054c4a3-76c4-460e-a209-b540d14ca788.mov

- `site_async.py`

https://user-images.githubusercontent.com/23740173/234095644-bd6d6af3-7781-4671-bf26-9f4e7dc22891.mov
