### ISSUE TITLE
Dropdown button

### ISSUE THREAD

**Issue by dott1718** [h2oai/wave#1887]
#### Is your feature request related to a problem? Please describe

A new UI component - a dropdown button similar to e.g. bootstrap https://getbootstrap.com/docs/4.0/components/dropdowns/

![image](https://user-images.githubusercontent.com/12784356/224831937-564f677f-91aa-4ea0-a4ec-70ff2f73e30c.png)

#### Describe the solution you'd like

A dropdown button to group several related actions under a single UI element.

**Comment by lo5** [comment]
The button function can probably accept an optional list like this: https://nitro.h2o.ai/guide/buttons/#add-a-menu

**Comment by mturoci** [comment]
@dott1718 one more alternative is to use [ui.menu](https://wave.h2o.ai/docs/widgets/form/menu/#with-label).
