### ISSUE TITLE
Authentication cookies are blocked on Same Site requests. Breaks D3 example

### ISSUE THREAD

**Issue by gaduimovich** [h2oai/wave#189]
<img width="1659" alt="Screen Shot 2020-10-01 at 1 08 20 PM" src="https://user-images.githubusercontent.com/6355715/94840904-3b2bff80-03e7-11eb-8c25-e57ec33944ca.png">

Since we secure the endpoints iframes and scripts that are done using `site.upload` can't use the session cookie to authenticate. 

Breaks Insights, NLP and D3 Demo

It will continue to work in firefox and safari, just not chrome.

**Comment by mturoci** [comment]
@gaduimovich seems like 9027cc91142157ea2055be05a064b71b209c1131 accidentally fixed this one as well by replacing data url with a blob object URL that is not treated as same origin. Is it safe to close this one then?

cc @lo5

**Comment by mturoci** [comment]
Closing as per the comment above.
