### ISSUE TITLE
Unexpected exception thrown by ensure_fresh_token

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#1908]
#### Wave SDK Version, OS

wave 0.25.2

#### Actual behavior

`ensure_fresh_token[_sync]` fails with `'NoneType' object has no attribute 'encode'` if called locally.

#### Expected behavior

`ensure_fresh_token[_sync]` returns `None` instead (according to its type annotion `-> Optional[str]`)

**Comment by mturoci** [comment]
Hey @Far0n, do you have OIDC setup properly for your wave server? This exception is thrown when there are no tokens to be refreshed.

**Comment by Far0n** [comment]
> Hey @Far0n, do you have OIDC setup properly for your wave server? This exception is thrown when there are no tokens to be refreshed.

Yeah, so it happens locally (as expected). It would be a bit more convenient if it would just return None in this case to avoid environment checks across the app before using the token_provider. That is, to not having to use something like:

```python
def get_token_provider(q: Q) -> Optional[Callable]:
   return None if not config.is_cloud else q.auth.ensure_fresh_token_sync
```

And since return type is annotated as Optional I thought it might be a bug as I don't think it will ever return None at the moment (returns either token or raises exception would be my guess).

**Comment by mturoci** [comment]
> happens locally (as expected)

I assume this means it happens locally when no OIDC is configured. If OIDC is configured, it shouldn't matter where the app is running. Correct me if this is not the case.

> It would be a bit more convenient if it would just return None in this case

Agree, I assume there are multiple apps that may face a similar problem - local env is different from prod.

Will add a check whether we have any tokens and turn to NOOP if not. Thanks for the heads up!

**Comment by Far0n** [comment]
> I assume this means it happens locally when no OIDC is configured

exactly

> Agree, I assume there are multiple apps that may face a similar problem - local env is different from prod.

Yes, but I could understand the argument that it might shadow real issues (bad OIDC configuration vs none available).

**Comment by mturoci** [comment]
> it might shadow real issues (bad OIDC configuration vs none available).

#1711 displays a warning in this case so should be good.
