### ISSUE TITLE
Add optional os and arch params to wave fetch command

### ISSUE THREAD

**Issue by romarioZ1000** [h2oai/wave#1910]
#### Wave SDK Version, OS

alpine 3.6

#### Actual behavior

![1](https://user-images.githubusercontent.com/67051805/228540948-c58273d7-a446-4315-b318-10173e776a23.PNG)

#### Expected behavior

<img width="415" alt="2" src="https://user-images.githubusercontent.com/67051805/228541455-c28344ad-64f3-4fc7-a9b3-87e24e57f555.PNG">

#### Steps To Reproduce

1. Do this - wave fetch

2.  Downloading https://github.com/h2oai/wave/releases/download/v0.25.2/wave-0.25.2-any-amd64.tar.gz

3. See error - urllib.error.HTTPError: HTTP Error 404: Not Found

4. do this - wget https://github.com/h2oai/wave/releases/download/v0.25.2/wave-0.25.2-any-amd64.tar.gz

5. see error - Connecting to github.com (140.82.121.3:443)
wget: server returned error: HTTP/1.1 404 Not Found

6. do this - wget https://github.com/h2oai/wave/releases/download/v0.25.2/wave-0.25.2-linux-amd64.tar.gz

7. Connecting to github.com (140.82.121.4:443)
ssl_client: write: Broken pipe
Connecting to objects.githubusercontent.com (185.199.108.133:443)
saving to 'wave-0.25.2-linux-amd64.tar.gz'
wave-0.25.2-linux-am   6% |*******                                                             wave-0.25.2-linux-am 100% |*********************************************************************************************************| 22.6M  0:00:00 ETA
'wave-0.25.2-linux-amd64.tar.gz' saved

Where need change link?
Thank you!

**Comment by mturoci** [comment]
Hey @romarioZ1000, can you add more info about your OS, python and pip versions? It seems like `pip` couldn't determine your OS type and went with `any`. Since we only release [OS-specific versions](https://github.com/h2oai/wave/releases/tag/v0.25.2), the fetch call returns 404.

**Comment by romarioZ1000** [comment]
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.4
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

pip:
pip 22.1.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)

Python:
Python 3.10.10

can i manual install from tar.gz?

**Comment by mturoci** [comment]
Thanks!

Since we cannot rely on pip downloading the proper platform-specific wheel file during `pip install h2o-wave`, we can at least show a warning informing the user what's going on. Additionally, new optional params will be introduced to `wave fetch` command, called platform/os and arch to let user pick the OS and architecture for wave fetch.

> can i manual install from tar.gz?

Yes, `wave fetch` is just a convenient way for fetching (downloading) and unzipping.
