### ISSUE TITLE
Add support for newlines and/or markdown in chatbot_card

### ISSUE THREAD

**Issue by ledell** [h2oai/wave#1927]
Currently, the `chatbot_card` ignores newlines, so text returned from the ChatGPT API is hard to read.   Optionally, the card could also support markdown for further visibility (and to support showing code).

Output (which contains newlines) looks something like this:

<img width="766" alt="Screen Shot 2023-04-12 at 7 40 00 PM" src="https://user-images.githubusercontent.com/4073698/231662907-b187f642-6f72-45de-b0de-71eaa70b7372.png">

**Comment by ledell** [comment]
@mturoci The raw text I have looks like this, so I added the three backticks on the beginning and end of the text so it would render as a code block.  However, it's rendering the second "```" for some reason:

Raw text:

```
In [21]: chatgpt_response_codeblock
Out[21]: '```# Importing required libraries\nimport h2o\nfrom h2o.automl import H2OAutoML\n\n# Initializing H2O cluster\nh2o.init()\n\n# Importing train and response datasets\ntrain = h2o.import_file("train.csv")\nresponse = h2o.import_file("response.csv")\n\n# Concatenating response column to train dataset\ntrain["response"] = response\n\n# Specifying response column name\nresponse_col = "response"\n\n# Excluding any columns that should not be used for model training\nexclude_cols = ["id"]\n\n# Initializing H2O AutoML with desired time and stopping metrics\naml = H2OAutoML(max_runtime_secs = 60, stopping_metric = "logloss")\n\n# Starting training process\naml.train(y = response_col, training_frame = train, exclude_columns = exclude_cols)\n\n# Printing the leaderboard (summary of model performance)\nlb = aml.leaderboard\nprint(lb)\n\n# Shutting down H2O cluster\nh2o.cluster().shutdown()```
```

I think that's a small bug?

Top looks good:
<img width="773" alt="Screen Shot 2023-04-14 at 9 19 56 AM" src="https://user-images.githubusercontent.com/4073698/232104614-1a9372e8-ed60-46b2-ab09-b40a0551133c.png">

Bottom with extra ```:
<img width="760" alt="Screen Shot 2023-04-14 at 9 36 06 AM" src="https://user-images.githubusercontent.com/4073698/232104669-2c89c54c-d8f1-4486-8aa8-9462e022b5ac.png">

It works as expected it I remove the second set of backticks.

**Comment by ledell** [comment]
After adding a newline to the end of the raw text before the "```", this resolves the problem, per @mturoci's suggestion.

<img width="772" alt="Screen Shot 2023-04-14 at 11 04 27 AM" src="https://user-images.githubusercontent.com/4073698/232122870-0673f30e-a561-42e9-b0b3-709c09e903a3.png">

**Comment by mturoci** [comment]
Glad it got resolved @ledell! This is a standard markdown behavior - Github markdown behaves exactly the same so I think adding the newline properly is the best we can do here.
