### ISSUE TITLE
Support message colours in chatbot_card

### ISSUE THREAD

**Issue by init27** [h2oai/wave#1929]
Right now the chat messages in `chatbot_card` stick to the app theme. It would be great if we can have the ability to change colours of the message bubbles.

TIA!

**Comment by mturoci** [comment]
Thanks for the suggestions @lo5, I didn't notice them until now.

#1998 changed the chatbot card layout to a more appropriate one, deprecating the need for custom colors I believe.

<img width="747" alt="image" src="https://github.com/h2oai/wave/assets/64769322/6fe3d334-a0cd-4bed-a677-eef00b1ba319">
<img width="748" alt="image" src="https://github.com/h2oai/wave/assets/64769322/f7ab3115-8a67-47e9-ac55-89adb7ce24d3">
<img width="749" alt="image" src="https://github.com/h2oai/wave/assets/64769322/1fed4e0a-aa93-4459-b71d-a2c36fd921d2">
