### ISSUE TITLE
Allow to replace messages in chatbot_card

### ISSUE THREAD

**Issue by psinger** [h2oai/wave#1944]
It would be great to allow replacing messages in a `chatbot_card` by indexing the queue. Currently, it is only possible to add messages.

**Comment by mturoci** [comment]
Hi @psinger. How is this different from #1928?

**Comment by psinger** [comment]
It is probably highly related, we can merge the two issues.
This one would refer to being able to also replace older ones and not only stream the latest one.

Any chance to prioritize these two issues? Thanks

**Comment by mturoci** [comment]
> This one would refer to being able to also replace older ones and not only stream the latest one.

I see. I plan to allow for complete control over messages so that user can decide whether to append or replace altogether. We can merge with #1928.

> Any chance to prioritize these two issues?

Will try my best to do so, but the soonest would be by the end of the next week if everything goes well.
