### ISSUE TITLE
Enable sort of filterable items in the table column

### ISSUE THREAD

**Issue by us8945** [h2oai/wave#1969]
#### Is your feature request related to a problem? Please describe

When ui.column has "filterable=True", the filterable items are displayed in the random order, which makes finding items to filter on hard.

#### Describe the solution you'd like

- Show filterable items in alphabetical order, allow for setting to set the order type and direction
- Enable search/filtering for filterable items. It will help in the situation when number of items is large

#### Describe alternatives you've considered

N/A

**Comment by mturoci** [comment]
The order can be controlled with `filters` attribute on a filterable table column. Works for paginated tables only, regular client side table should not need this as they are expected to have less data. For tables with a lot of data, pagination is required anyway.

**Comment by mturoci** [comment]
As of version `0.26.0`, the constraint above was removed and `filters` can be used for both paginated and client-side tables.
