### ISSUE TITLE
Allow show/hide functionality for passwords in ui.textbox()

### ISSUE THREAD

**Issue by n-srinidhi** [h2oai/wave#1977]
#### Is your feature request related to a problem? Please describe
While building Login Forms using h2o.ai Wave, There is a password property in `ui.textbox()`. However, unlike login forms on web apps on the internet, there is no option to make the icon of the field clickable in order to toggle between the show text and hide text option for the password field. 

#### Describe the solution you'd like
It would be nice to have an inbuilt functionality to show/hide the text being typed in password style textboxes. Or atleast make the icons within a textbox clickable so we it can be implemented through code. 

#### Describe alternatives you've considered
A simple [workaround](https://github.com/h2oai/wave/discussions/1976#discussioncomment-5914412) right now is to add a button alongside the textbox to toggle between showing and hiding the typed text. However, it isn't very flattering from a UX perspective, as the button is selected on hover and the boundaries of the textbox is also visible.

**Comment by i-m-karanagarwal** [comment]
I would like to work on this issue.
Please assign it to me.
