### ISSUE TITLE
Plots don't preserve sort order if data is passed after plot is created

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#199]
```py
from h2o_q import site, data, ui

page = site['/demo']

rows = [
    ('price', 0.99),
    ('longitude', 0.98),
    ('bathrooms', 0.94),
    ('lattitude', 0.78),
    ('bedrooms', 0.73),
    ('description', 0.47),
    ('manager_id', 0.46),
    ('features', 0.19),
    ('building_id', 0.14),
    ('created', 0.08),
    ('display_address', 0.05),
    ('street_address', 0.01),
    ('listing_id', 0.0),
]

v = page.add('example', ui.plot_card(
    box='1 1 4 5',
    title='Interval',
    data=data('feature importance'),
    plot=ui.plot([ui.mark(type='interval', x='=importance', y='=feature', x_min=0)])
))

v.data = rows

page.save()
```

**Comment by RajeshDhalange** [comment]
Is this issue is solved? or have any workaround?  It's not working in the latest release.  not preserving sort order

**Comment by mtanco** [comment]
@lo5 I am seeing this example in reverse order for h2o_wave==0.13.0
<img width="616" alt="image" src="https://user-images.githubusercontent.com/4793561/111196267-52683f00-857a-11eb-8fe1-79ba1052c62b.png">


(Also, need to add count to `data` for the plot to render: `data=data('feature importance', len(rows)),`)

**Comment by lo5** [comment]
@RajeshDhalange @mtanco - There's no bug here. It's working as expected.

This defaults to `size=0`, allocating a [dictionary buffer](https://wave.h2o.ai/docs/buffers#types-of-buffers):

    data=data('feature importance'),

Order-preservation is not guaranteed in dictionaries.

To preserve order, specify a size:

    data=data('feature importance', size=len(rows)),

A simpler way to achieve the same result is:

```py
from h2o_wave import site, data, ui

page = site['/demo']

page['example'] = ui.plot_card(
    box='1 1 4 5',
    title='Interval',
    data=data(
        fields='feature importance',
        rows=[
            ('price', 0.99),
            ('longitude', 0.98),
            ('bathrooms', 0.94),
            ('lattitude', 0.78),
            ('bedrooms', 0.73),
            ('description', 0.47),
            ('manager_id', 0.46),
            ('features', 0.19),
            ('building_id', 0.14),
            ('created', 0.08),
            ('display_address', 0.05),
            ('street_address', 0.01),
            ('listing_id', 0.0),
        ]
    ),
    plot=ui.plot([ui.mark(type='interval', x='=importance', y='=feature', x_min=0)])
)

page.save()
```

The ordering of items on the axes is consistent across axes (left-to-right for x, bottom-to-top for y). You can reverse the row to get the opposite effect.
