### ISSUE TITLE
URL with hash not rendered in new tab

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#211]
Hash routing works when changing the actual tab URL, but doesn't work in new tab.
Not: `/demo` without hash works as expected.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/64769322/96129885-79511500-0ef7-11eb-8cf8-b2541c1bbf0e.gif)

#### Actual behavior

A blank page is rendered when you want to visit a url with hash routing (ends with #some-hash).

#### Expected behavior

App should render even if the URL contains hash.

#### Steps To Reproduce

1. Run `examples.tab_routing`
2. Go to `http://localhost:10101/demo#menu/eggs`

**Comment by lo5** [comment]
@mturoci - I don't understand what the bug is. Can you please jot down an explanation using our bug report template?

**Comment by mturoci** [comment]
@lo5 issue description updated.
