### ISSUE TITLE
Primary button UI without label

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#2121]
#### Wave SDK Version, OS
0.26.0 on MacOS

#### Actual behaviour
Button is not primary if label is not set.

<img width="125" alt="Screenshot 2023-08-28 at 6 42 48 PM" src="https://github.com/h2oai/wave/assets/8954217/7b10386c-a5e2-4385-8778-db0e68ce3f4d">

eg: Button1 isn't primary.

#### Expected behaviour
Button1 should be primary.

#### Steps To Reproduce
```python
from h2o_wave import main, app, Q, ui


@app('/demo')
async def serve(q: Q):
    q.page['example'] = ui.form_card(
        box='1 1 4 10',
        items=[
            ui.button(name='button1', icon='Search', primary=True),
            ui.button(name='button2', label='Search', icon='Search', primary=True)
        ])

    await q.page.save()
```

**Comment by mturoci** [comment]
Thanks @vopani! Does using an empty string for the label work as a workaround?
