### ISSUE TITLE
Enhancing visibility of commands on certain cards

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#2127]
#### Is your feature request related to a problem? Please describe

Commands on plot cards (as an example) tend to have bad visibility (usual use case: switch plot type):
![grafik](https://github.com/h2oai/wave/assets/6949295/6396472c-2bea-40d6-92c9-0fa133732338)

#### Describe the solution you'd like

Some better visible UI element than the current kebab menu.

**Comment by Far0n** [comment]
would it be an idea to be able to choose an icon for commands, like maybe from common menu ones: https://www.behance.net/gallery/89736895/Know-Your-Menu-?

**Comment by mturoci** [comment]
> would it be an idea to be able to choose an icon for commands, like maybe from common menu ones:

@Far0n is this just a cosmetic request or would this solve some UX problem? Just asking because we might consider it if it's the latter, otherwise one needs to live with the Wave's opinionated nature.

**Comment by Far0n** [comment]
> @Far0n is this just a cosmetic request or would this solve some UX problem? Just asking because we might consider it if it's the latter, otherwise one needs to live with the Wave's opinionated nature.

I had visibility in mind, because the kebab one seems difficult to spot sometimes.

**Comment by mturoci** [comment]
Makes sense. I think this should be resolved with the fixed colors though. We could theoretically go for a hamburger, but that IMO usually means a big side menu is about to open. In fact, we use it for this exact scenario in the header IIRC. The kebab one is more subtle, but that's on purpose. It's just to add a small contextual menu after all so no need for high prominence.
