### ISSUE TITLE
Raise error if waved cannot find public/private dir

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#2130]
#### Is your feature request related to a problem? Please describe

Debugging public/private dir configuration is painful currently, because if the path is not correct, the operation fails silently and waved starts nonetheless.

#### Describe the solution you'd like

Notify the user about the inaccessible path during waved startup.

**Comment by kaitlyncliu** [comment]
Hi I would like to work on this!

**Comment by mturoci** [comment]
Go ahead and good luck then @kaitlyncliu!

**Comment by chickenleaf** [comment]
@mturoci is this still up for grabs?

**Comment by dbranley** [comment]
Hi, I submitted a PR for this change request. Let me know how it looks and if you would like any changes. Thanks!

**Comment by pascal-pfeiffer** [comment]
What is the reasoning process behind disallowing this?
Usually, one would check in the python app code and at startup if the required folder exists and if not it might be created. Especially with mounted devices, this now requires code outside of the app and even prior to startup.

**Comment by mturoci** [comment]
The original goal was to improve DX since specifying folders is a bit inconvenient (has to be relative to waved binary rather than main app file). This way, wrong path would be reported right away.

However, I didn't consider the usecase you mentioned above, which is totally valid, so lowering to warn makes sense.

Changed in https://github.com/h2oai/wave/commit/6ebfbf9b9f975fd3903f8a7606a3874165cee1db.
