### ISSUE TITLE
Emit event on table group open/collapse

### ISSUE THREAD

**Issue by n-srinidhi** [h2oai/wave#2133]
#### Is your feature request related to a problem? Please describe

The problem is described in this [discussion.](https://github.com/h2oai/wave/discussions/2131)

#### Describe the solution you'd like

I'd like to be able to update the table groups and rows without resetting the collapsed/expanded state of the table groups.

**Comment by UNAPZ** [comment]
I will try it.

**Comment by UNAPZ** [comment]
`from h2o_wave import main, app, Q, ui

@app('/demo')
async def serve(q: Q):
    if not q.client.initialized:
        # Initialize group collapse states
        q.client.group_collapsed_states = {"Bob": True, "John": False}

        await initialize_table(q)
        
        q.page['meta'] = ui.meta_card(box='', script=ui.inline_script(content='''
        document.querySelectorAll('.ms-GroupHeader-expand').forEach(btn => {
          btn.addEventListener('click', e => {
            const groupName = e.currentTarget.parentElement.parentElement.querySelector('.ms-GroupHeader-title > span').innerText
            wave.emit('table', 'group_change', groupName)
          })
        })
        '''))
        
        q.client.initialized = True
    else:
        # Check for group change event
        if q.events.table and q.events.table.group_change:
            group_name = q.events.table.group_change
            q.client.group_collapsed_states[group_name] = not q.client.group_collapsed_states[group_name]
            await initialize_table(q)

    await q.page.save()

async def initialize_table(q: Q):
    q.page['form'] = ui.form_card(box='1 1 -1 6', items=[
        ui.table(
            name='table',
            columns=[ui.table_column(name='text', label='Issues reported by')],
            groups=[
                ui.table_group("Bob", [
                    ui.table_row(name='row1', cells=['Issue1']),
                    ui.table_row(name='row2', cells=['Issue2'])
                ], collapsed=q.client.group_collapsed_states["Bob"]),
                ui.table_group("John", [
                    ui.table_row(name='row3', cells=['Issue3']),
                    ui.table_row(name='row4', cells=['Issue4']),
                    ui.table_row(name='row5', cells=['Issue5']),
                ], collapsed=q.client.group_collapsed_states["John"])],
            height='500px'
        )
    ])
` 
I used this logic to solve the problem. But do I need to develop new features for table.tsx? If the development can provide me with some necessary documentation or workarounds.

**Comment by UNAPZ** [comment]
I used your given logic to solve the problem. But do I need to develop new features for table.tsx? If the development can provide me with some necessary documentation or workarounds.

**Comment by dbranley** [comment]
I've submitted a [PR](https://github.com/h2oai/wave/pull/2402) for this feature request. Please let me know if you have any questions or would like me to make any changes. Thanks!
