### ISSUE TITLE
Do not send websocket ping/pongs during active traffic

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#2138]
Currently, waved sends ping/pong messages to keep the websocket connection alive. This however seems redundant when done during active traffic.

**Comment by codyharris-h2o-ai** [comment]
While yes it is redundant I do believe that it is a good check on the health of the connection - the ping/pong validates that both sides of the connection are working/behaving as expected (that the remote is actually receiving and understanding data, and that it isn't getting caught in a buffer somewhere).

**Comment by codyharris-h2o-ai** [comment]
Yep, I still believe the pingpongs have value even if there is traffic on the connection

**Comment by mturoci** [comment]
Got it, closing the issue then. Thanks for the inputs!
