### ISSUE TITLE
Allow actions on table

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#215]
via @pramitchoudhary 

Table needs to support various actions (edit, delete, view...). We should either:
* Make icon column clickable and set `q.args`.
* Create a ContextMenu column (similar to DAI) that would allow user to pick the desired action.

I personally prefer the first one. Discussion is welcome.

**Comment by lo5** [comment]
This is another option (from the `DetailsList` on office.com.
![Screenshot from 2021-03-22 18-45-49](https://user-images.githubusercontent.com/6334572/112080390-2717be00-8b3f-11eb-8e71-5977e583b768.png)

**Comment by shihan007** [comment]
@mturoci For model monitoring we need this feature. Adding a button, icon as action
![Screenshot 2022-03-21 at 14 45 25](https://user-images.githubusercontent.com/38729017/159262561-60328329-76da-43f6-9563-7f5b010c4831.png)

cc: @shereezhang @iamabhishekmathur @mtanco

**Comment by aalencar** [comment]
@shihan007 can you confirm if #897 solves this issue?

**Comment by shihan007** [comment]
@dulajra @VijithaEkanayake @Nayananga Can you confirm wether #897 solves adding action button to table?

**Comment by Nayananga** [comment]
@shihan007, We need a code example to try this out, @aalencar, could you please share a code example or documentation to try this out?

**Comment by aalencar** [comment]
Try this:
```py
commands = [
    ui.command(name='details', label='Details'),
    ui.command(name='delete', label='Delete'),
]

q.page['example'] = ui.form_card(box='1 1 3 3', items=[
    ui.table(
        name='table',
        columns=[ui.table_column(name='actions', label='Actions', cell_type=ui.menu_table_cell_type(name='commands', commands=commands))],
        rows=[ui.table_row(name='first_row', cells=[''])] 
    )
])
```

**Comment by aalencar** [comment]
@Nayananga did you manage to test it?

**Comment by shamilh2o** [comment]
@aalencar  I tested above sample code in both wave 0.21.0 and 0.21.1. It didn't work in both versions. Output is as below.

Error
Traceback (most recent call last):
  File "/Users/admin/Documents/TestProjects/Pycharm Basic Project 1/venv/lib/python3.8/site-packages/h2o_wave/server.py", line 320, in _process
    await self._handle(q)
  File "./app.py", line 15, in serve
    cell_type=ui.menu_table_cell_type(name='commands', commands=commands))],
AttributeError: module 'h2o_wave.ui' has no attribute 'menu_table_cell_type'

**Comment by aalencar** [comment]
@shamilh2o thanks for taking a look into it. You have to use the nightly version of Wave which includes this feature.
