### ISSUE TITLE
Allow single selection for table

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#216]
via @pramitchoudhary 

Currently, we only support multiple or none selection:
![image](https://user-images.githubusercontent.com/64769322/96243263-c5a65e80-0fa4-11eb-9fdd-3e5288a14bfb.png)

@lo5 was there a specific reason for this?

We could change the current `multiple` prop to `selection` and allow three values: `none`(default), `single` and `multiple`. This would be a breaking change though. Another option would be to simply add `single: B` in addition to `multiple`. The first option seems to be cleaner to me even for the price of a breaking change.

**Comment by lo5** [comment]
What's the use case for allowing only one row to be selected? Would a dropdown solve that problem?

**Comment by Far0n** [comment]
@lo5 @mturoci 
We have a use case for this in **Model Validation**: https://github.com/h2oai/model-validation/pull/111#issue-1378730439

The following would be great:
- single selection with trigger=True functionality and the same layout as the multi-selection table
- bonus: single selection with layout from non-selectable table, single left-click trigger no matter where on a row and some visual highlight of clicked aka selected row (something similar to what we currently do in our workaround, see link above)

**Comment by mturoci** [comment]
@lo5 we need to agree on how we want to do this since the current API is somewhat tangled. We currently have 2 ways of table value submissions:

* Doubleclicking / first col link click - submits values straightaway.
* Multiselection - disables ^^ and allows for multiple selection of rows that need a button for the followup submission.

We need to add a third way

* Single selection - same as multiselection, but allow only a single item to be selected at a time.

The reason this is not straightforward is that we expose `isMultiple` boolean that [turns on/off the table selection](https://github.com/h2oai/wave/blob/6c375ae7fa729c74f6cf70d45a60fd355beece9e/ui/src/table.tsx#L566) in general. If not set, no selection is available. One way we could make this is to allow single selection as default (instead of current no-selection) and change the default of `checkbox_visibility` from `on-hover` to `hidden`. Despite this being a soft breaking change, it would only impact people currently using `isMultiple` and default `checkbox_visibility` which should be minority.

Other solution could simply be adding a new `isSingle` attr, but it may be slightly confusing.

The last part that needs discussion is about value submissions. We can:

* add `trigger` and submit currently selected values on every selection change as suggested by @Far0n 
* Emit the selection changes as event.

wdyt?

**Comment by lo5** [comment]
I would prefer `isSingle`. It's a bit ugly, but at least it won't break the existing API. `isSingle` could mean "force single-select", just like `isMultiple` forces multiple-select.

**Comment by mturoci** [comment]
As discussed on a call, we will go with emitting a `select` event instead of introducing a `trigger` attr.

**Comment by mturoci** [comment]
We can introduce a new `value` attribute that would be only used if the single selection is set. Similar to the existing `ui.dropdown` API.
