### ISSUE TITLE
App won't run if it's name is provided in a relative form

### ISSUE THREAD

**Issue by AWRDev** [h2oai/wave#2160]
#### Wave SDK Version, OS

h2o-wave==0.26.3, Windows 10 build 19044

#### Actual behavior

App won't run if the path provided like ./app.py 
(Happens while using Terminal's Tab-autocomplete). Makes things inconvinient

#### Expected behavior

App runs independently of way how application name is provided: "app.py" or ".\app.py", etc.

#### Steps To Reproduce

1. Open terminal
2. Run `wave run .\app.py`
3. See error message `TypeError: the 'package' argument is required to perform a relative import for './app'`

**Comment by mturoci** [comment]
Thanks for the suggestion @AWRDev! The solution should be just a simple prefix trimming.
