### ISSUE TITLE
Integrate github workflows to automate the air-gapping process

### ISSUE THREAD

**Issue by sulhicader** [h2oai/wave#2163]
#### Description

Integrate workflows in [wave-template](https://github.com/h2oai/wave-template/tree/main/.github/workflows) repo to automate the air-gapping process of wave-university.

**Comment by mturoci** [comment]
@sulhicader can you elaborate? Wave University is already air-gapped IIRC.

**Comment by sulhicader** [comment]
There are some new flags introduced to h2o cli to generate air-gapped bundles of wave apps so those can be integrated in to replicated bundle. this [doc](https://github.com/h2oai/h2o-ai-cloud/blob/master/documentation/docs/developerguide/cli.md#airgapped-bundles) contains more info about it. github workflows in [wave-template](https://github.com/h2oai/wave-template/blob/main/.github/workflows/) automate the end to end process of building the docker images and publishing the docker images and helm charts to ECR which are generated from h2o cli command. This workflows should be integrated in the core wave apps listed in the [issue](https://github.com/h2oai/cloud-platform/issues/97)

**Comment by mturoci** [comment]
Closed via #2181
