### ISSUE TITLE
Like/Dislike and Events for ChatBot

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#2165]
#### Is your feature request related to a problem? Please describe
I would like my users to be able to share feedback about responses from chat bots. 

#### Describe the solution you'd like

Feedback: I would like to optionally turn on feedback for the GenAI responses in the form of a Thumbs Up / Thumbs Down buttons for each chat response that could be new events. As a developer, I would want to know the text and the button clicked (thumbs up or down). I would record the feedback but not make any change to the UI other than I would want the button to look selected.

#### Describe alternatives you've considered

(A clear and concise description of any alternative solutions or features you've considered.)

**Comment by mturoci** [comment]
cc @pramitchoudhary
