### ISSUE TITLE
Add `name` attribute to ui.stats

### ISSUE THREAD

**Issue by nipunchamikara** [h2oai/wave#2197]
#### Wave SDK Version, OS
1.0, MacOS

#### Actual behavior
I have a few widgets as items within a `form_card`, one of then being a `stats` widget. I want to reference it later in the code to update it. However, when I try to add a `name="stats"` argument, the IDE says it is an unexpected argument. When I try to run the Wave app, it throws the following error:
```Error: stats() got an unexpected keyword argument ‘name’```

This argument is also missing in some card widgets as well - [ui.py](https://github.com/h2oai/wave/blob/9897c98ed2d55eab7192680d51e80399fab67dd8/py/h2o_wave/h2o_wave/ui.py)

Is there any other to reference a widget other than the [square-bracket notation](https://wave.h2o.ai/blog/release-0.26#by-name-component-access).

#### Expected behavior
The widget can be referenced like most other widgets (by-name component access).

**Comment by mturoci** [comment]
Definitely something we need to add. Thanks for the suggestion @nipunchamikara!
