### ISSUE TITLE
Not enough contrast between notification bar background and close button in `h2o-dark` theme

### ISSUE THREAD

**Issue by nipunchamikara** [h2oai/wave#2241]
#### Wave SDK Version, OS

Wave v1.0.0
MacOS v14.3

#### Actual behavior

I'm currently working on a Wave App that has a light and dark mode, where it uses `default` and `h2o-dark` themes respectively. When using `h2o-dark`, the close button in notification bar is not discernible. It is visible when using the `default` theme.

- `default` theme:
  <img width="560" alt="image" src="https://github.com/h2oai/wave/assets/25861544/19d2756a-fabe-4eb1-a35e-5d7683ff733d">

- `h2o-dark` theme:
  <img width="560" alt="image" src="https://github.com/h2oai/wave/assets/25861544/44a8557e-348a-47f6-baf6-0807c927b0d0">

#### Expected behavior

Either the background of the notification bar should change with the theme, or the color of the close button should remain fixed. 

#### Steps To Reproduce

1. Set `q.page["meta"].theme` to `h2o-dark`
2. Set `q.page["meta"].notification_bar` to `ui.notification_bar` component

**Comment by mturoci** [comment]
Thanks for reporting @nipunchamikara!
