### ISSUE TITLE
Buttons as an input format for the chatbot widget

### ISSUE THREAD

**Issue by abaraldo** [h2oai/wave#2250]
### Buttons as an input format for the chatbot widget

I propose adding a feature that allows users to customize the output of the ui.chatbot widget into a form with interactive buttons.
This would enhance the user experience by providing a more interactive and accessible way to navigate the chatbot's responses.

![image](https://github.com/h2oai/wave/assets/37185885/f6d0523d-50a3-4a81-9670-eae658713130)

### Problem it Solves
Currently, the chatbot widget allows a [feedback interaction](https://github.com/h2oai/wave/issues/2165), but this new feature would be a generalization by having a customizable form with any buttons and options.
Sometimes, I would like the input from the user to be a closed answer within limited possibilities.

### Suggested Implementation
- Allow users to define the structure of the form and the labels on the buttons.
- Whenever the form is display as input option, the regular text input would de disabled

### Potential Benefits
- Enhances user engagement with a more interactive interface.
- Simplifies user interaction, especially for complex queries or multiple-choice questions.
- Makes the chatbot more accessible, particularly for users who prefer a guided interaction.

**Comment by mturoci** [comment]
@abaraldo would you be ok if we added a new list of  `ui.chat_prompt_suggestion` in which each would accept a string value (displayed under the last response) and upon clicking would fire an event for you to consume, append to the chat messages and start generating the answer?

**Comment by abaraldo** [comment]
> @abaraldo would you be ok if we added a new list of `ui.chat_prompt_suggestion` in which each would accept a string value (displayed under the last response) and upon clicking would fire an event for you to consume, append to the chat messages and start generating the answer?

I think that would be great! I could use that to bring suggestions or options for the user. Will it be possible to have multiple options at the same time?

**Comment by mturoci** [comment]
> Will it be possible to have multiple options at the same time

Yes, it's going to be a list.

**Comment by marek-mihok** [comment]
> and upon clicking would fire an event for you to consume, append to the chat messages and start generating the answer

@mturoci just an implementation detail - should appending to messages be done by user after obtaining the event or should it be done automatically with firing the event?
