### ISSUE TITLE
Changes in width handling since v0.26.3 makes handling of inline objects difficult

### ISSUE THREAD

**Issue by johannes-becker-otto** [h2oai/wave#2251]
Hi,

here's a minimal example of inline objects that add up to 100%
```
page["form"] = ui.form_card(
    box="1 1 4 2",
    items=[
        ui.inline(
            items=[
                ui.textbox(name="textbox1", label="Textbox 1", width="34%"),
                ui.textbox(name="textbox2", label="Textbox 2", width="33%"),
                ui.textbox(name="textbox3", label="Textbox 3", width="33%"),
            ]
        )
    ],
)
```

1.0.1
![image](https://github.com/h2oai/wave/assets/97096714/21b00482-e48e-43ad-a6f5-97ba2ff96636)

0.26.3 (actually the screenshots are taken with 0.22.0 but I realized I'm using 0.26.3 right now and it's still fine)
![image](https://github.com/h2oai/wave/assets/97096714/a65c99e6-d7da-4bed-9a12-7b81db8060cc)

Until version 0.26.3 100% remained the same total width no matter how crazy it gets
![image](https://github.com/h2oai/wave/assets/97096714/4b349738-3663-4cd2-b9d7-3dcb6941f70e)

After 0.26.3 the 100% become unreliable, here examples for 1.0.1 and 100% and 50%/50%
![image](https://github.com/h2oai/wave/assets/97096714/321afbc8-27dd-44b8-b10f-908f7d24a8c2)
![image](https://github.com/h2oai/wave/assets/97096714/c8cbf303-9621-4d02-9546-159f4771eba4)

All the best
Hannes

**Comment by mturoci** [comment]
cc @marek-mihok
