### ISSUE TITLE
Wave fetch 404 on linux

### ISSUE THREAD

**Issue by bstin** [h2oai/wave#2254]
#### Wave SDK Version, OS

1.0.1

#### Actual behavior

Running `wave fetch` throws 404 error trying to download `https://github.com/h2oai/wave/releases/download/v1.0.1/wave-1.0.1-manylinux1_x86_64-amd64.tar.gz`

That file doesn't exist. Opening in Firefox yields same 404

#### Expected behavior

Should download

#### Steps To Reproduce

1. Install `pip install h2o-wave`
2. `pip install h2o_wave_university`
3. Issue `wave fetch`

**Comment by mturoci** [comment]
Thanks for reporting! A workaround until fixed: `wave fetch --platform linux --arch amd64`.

**Comment by mturoci** [comment]
Already fixed in https://github.com/h2oai/wave/pull/2183. I just forgot to cherry-pick it to `1.0.1` when releasing. Will make sure to not forget in case I need to cut `1.0.2`.
