### ISSUE TITLE
Visited links in text always blue

### ISSUE THREAD

**Issue by g-eoj** [h2oai/wave#2281]
Visited links don't appear to use an custom coloring with templates (or maybe I have a bad template?). Makes it hard to read text after clicking on a link.

The blue link in this screen shot is a `ui.text` object that contains a url that was clicked.

<img width="1204" alt="Screenshot 2024-03-05 at 2 28 40 PM" src="https://github.com/h2oai/wave/assets/2815901/cf77460d-0963-48ad-b852-1e44136dbd77">

**Comment by mturoci** [comment]
Good catch. I guess we don't even handle those. @marek-mihok please make links use the current primary color.
