### ISSUE TITLE
Problem with wave tour image building because can find the h2o_wave latest version in PYPI 

### ISSUE THREAD

**Issue by sulhicader** [h2oai/wave#2288]
Latest release of h2o_wave can not install from the PYPI using pip for some time after publishing the library to PYPI. So getting the following error when building the runtime image for the wave tour app.

ERROR: Could not find a version that satisfies the requirement h2o_wave==1.1.1 (from versions: 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 1.0.0, 1.0.1, 1.0.2, 1.1.0)

https://github.com/h2oai/wave/actions/runs/8254859486/job/22580763018

**Comment by sulhicader** [comment]
@mturoci , Workflow (https://github.com/h2oai/wave/actions/runs/8527219621/job/23359294072)  for v1.1.2 wave release didn't give the error in https://github.com/h2oai/wave/actions/runs/8254859486/job/22579983568. Different I can see is, Release wave step in the failed workflow only took 21mins while the workflow for v1.1.2 release took 31mins.

**Comment by mturoci** [comment]
Seems like no longer an issue:

![image](https://github.com/user-attachments/assets/94e26d43-38e1-4137-ae25-4db8f4487286)

Will reopen once pops up again.
