### ISSUE TITLE
401 Unauthorized Error - Wave reload on quick code changes

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/wave#2337]
#### Wave SDK Version, OS

Wave 1.2.0 (but basically on all wave versions)
Ubuntu 22.04

#### Actual behavior

When I change code locally and run the wave server without `--no-reload`, it will automatically detect code changes and reload. Unfortunately, when using autosave, I get a 401 error very often doing so. Probably due to rapid changes in the files. In these cases, I need to change the code again or restart the wave server manually to recover.

```
INFO:     127.0.0.1:46888 - "POST / HTTP/1.1" 401 Unauthorized
```

#### Expected behavior

Handle quick changes in the code.

#### Steps To Reproduce

1. Run a wave server and application without `--no-reload` arg.
2. Make quick changes in the code and save often. Or use autosave.
3. Receive 401 error

**Comment by psinger** [comment]
Seeing the same issue.

**Comment by psinger** [comment]
@mturoci any chance to take a look at this please?
It is currently very cumbersome to develop with this issue always popping up after each code change and refresh.
