### ISSUE TITLE
wavedb not included in build releases (that I can see)

### ISSUE THREAD

**Issue by EnviralDesign** [h2oai/wave#2348]
I started off here in the docs:

https://wave.h2o.ai/docs/wavedb

It says `[Download the executable](https://github.com/h2oai/wave/releases) for your platform. No installation required.`

I click through to that url, which takes me to the releases, but there is no sign of a wavedb executable (I am on windows) anywhere, not in any windows archives or independent.

Where might I find this?

**Comment by EnviralDesign** [comment]
I followed the build instructions and it works great btw, One observation is that the resulting build file on windows 11 is a single file called `wavedb`, with no extension.

This is a valid windows exe file and runs fine! just needs to be renamed to `wavedb.exe`.

**Comment by mturoci** [comment]
Thanks for the reminder! Added into the latest release - https://github.com/h2oai/wave/releases/tag/v1.3.1.
