### ISSUE TITLE
ui.table / ui.progress_table_cell_type has floating point rounding issues

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/wave#2380]
#### Wave SDK Version, OS

wave 1.3.4

#### Actual behavior

![image](https://github.com/user-attachments/assets/32847516-7106-4fff-95ce-dee698e545c3)

#### Expected behavior

Clear visualization of 14%

#### Steps To Reproduce

1. Create a `ui.table` with a column set to cell type `ui.progress_table_cell_type`
2. Chose value "0.14" (this is one of the values that has issues)
3. See rounding issue in UI

**Comment by dbranley** [comment]
Hello, I've submitted PR [#2415](https://github.com/h2oai/wave/pull/2415) to resolve this issue. Let me know if it looks ok or if there's something else you need me to do. thanks!
