### ISSUE TITLE
Make app timeouts configurable

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/wave#2383]
A user of H2O LLM Studio is reporting timeout issues when starting H2O LLM Studio. https://github.com/h2oai/h2o-llmstudio/issues/822

I can personally confirm this error happing on me, too. Though, very rarely and I couldn't find any way to reproduce/force the error.

Stacktrace from the original issue:
![image](https://github.com/user-attachments/assets/e8663d5c-e6d1-407f-8851-a90da165bbc9)
![image](https://github.com/user-attachments/assets/8273b506-492b-4163-9730-d194a7e09947)
![image](https://github.com/user-attachments/assets/77f28654-593b-4d72-a97c-410a6fc4b827)

**Comment by mturoci** [comment]
Having waved logs as well would be helpful. For now, I can make timeouts configurable (instead of default 5s) and see if higher value helps, in which cause the cause is simply slow network.
