### ISSUE TITLE
Explain Hash-Change Navigation

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#252]
https://wave.h2o.ai/docs/api/ui
> The name of this item. Prefix the name with a '#' to trigger hash-change navigation.

The wording makes me thing that I have two choices to choice between:
1. Prefix with # for hash-change navigation
2. Dont prefix with # non non-hash-change navigation

I think that the # is required? maybe

If so can we say so more explicitly. 
If not can we detail 
* exactly what "hash-change navigation" means 
* what happens if you do or don't use it
* when you would want to or not want to use it

(Yes I could google this but this is a place in the docs which might be confusing to the generic data scientist turned developer persona)

**Comment by AdarshBajpai67** [comment]
hey is this issue still open?
if yes please do explain a bit more
