### ISSUE TITLE
Check type of items

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#279]
If you set `form_card.items` to a single item instead of a list, the application will break (white page) but the code will not break. This is 100% a user error but really hard to debug and an issue I have ran into a few times when I will have a list of a single item and so forget to put it in brackets and make it a list. Checking that .items is a list would be really nice error handling.

I have not had a chance to test in 0.9.X yet - but this was in 0.6.0 and 0.8.X

Reproduce:

Start with:
```
page = site['/demo']

page['example'] = ui.form_card(
    box='1 1 2 2',
    items=[
        ui.frame(content=html, height='100px')
    ]
)

page.save()
```

and change to
```
page = site['/demo']

page['example'] = ui.form_card(
    box='1 1 2 2',
    items=ui.frame(content=html, height='100px')
)

page.save()
```

**Comment by lo5** [comment]
The above code now raises:
```
ValueError: FormCard.items: want list of (<class 'h2o_wave.types.Component'>,), got <class 'h2o_wave.types.Component'>
```
