### ISSUE TITLE
Support loading and event-handing for arbitrary javascript libs

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#297]

**Comment by datajms** [comment]
Specifically, being able to use interactive tooltips in plots (lasso-select, mainly) and get the selected points in wave app environment would be a great plus!

For example:
![lasso-select](https://user-images.githubusercontent.com/23101469/115350503-7c360680-a1b5-11eb-9824-d9dae2d7cd70.gif)
- with [Bokeh](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html)
- with [plotly/dash](https://dash.plotly.com/interactive-graphing)
- but open to any plotting framework which would do the job.

**Comment by goldentom42** [comment]
The app @datajms refers to displays clusters to users and allow them to select/identify regions. 
With the points selected on the graph, the app tries to derive rules for that region.

**Comment by mmalohlava** [comment]
Similar problems: 
  - visual annotation library (something like: https://gitlab.com/vgg/via) - how can user process selected annotation in wave app
  - capture image in browser (camera/screnshot) - how can user process the image at backend

**Comment by lo5** [comment]
You can now load and raise events from arbitrary Javascript.

[This Bokeh example](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections), without modification:

![2021-05-17_18-49](https://user-images.githubusercontent.com/6334572/118578248-a9d48800-b740-11eb-88d0-9ec578093fa8.png)

Example source: https://github.com/h2oai/wave/commit/eb2ea689f07b2be57754c73a1b6f8ee2b3d6a813

Will be released in v0.16.

**Comment by lo5** [comment]
Documented here: https://wave.h2o.ai/docs/javascript
