### ISSUE TITLE
Cap max width of slider

### ISSUE THREAD

**Issue by brmscheiner** [h2oai/wave#308]
The slider currently expands to the full width of its container, which looks really awkward in a large card. For example:
![image](https://user-images.githubusercontent.com/9775178/99702899-43013b00-2a4b-11eb-9d68-8984b16df2cd.png)

Being able to explicitly set the size of the slider would be ideal, but a variant property with values like small / medium / large would also be fine.

**Comment by lo5** [comment]
Just set max-width for now.

**Comment by pramitchoudhary** [comment]
Will it be possible to extend this idea from drop-down widgets as well not sure if `text-box` already has such an option?

**Comment by mturoci** [comment]
FYI we have added a custom width control in #795 which will be available in the next release (0.18).
