### ISSUE TITLE
header_card should accept a clickable logo

### ISSUE THREAD

**Issue by brmscheiner** [h2oai/wave#310]
**Is your feature request related to a problem? Please describe.**
It should be possible to add a custom logo to an application's header. In many web apps, the logo also serves as a link back to the homepage, so it would also be nice to support this functionality. 

**Describe alternatives you've considered**
Perhaps I don't understand the `icon` argument. Is this in the docs somewhere? I'm assuming [these](https://developer.microsoft.com/en-us/fluentui#/controls/web/icon) are the options but I could be way off.

**Comment by lo5** [comment]
I'm not sure how useful this is. 
As of 0.11 the icon is replaced with a hamburger if you set the `nav=` attribute for a built-in navigation menu.

**Comment by vopani** [comment]
I think allowing a custom logo in a header card in some way will be useful.

Many websites / products have logo with name as heading and it's easier to associate that with a brand than to have a standard icon or no icon.

It is possible currently (as of v0.12) using separate cards, but is cumbersome and looks unnatural.

**Comment by lo5** [comment]
Related: #674
