### ISSUE TITLE
Drawable canvas component

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#313]
via @arnocandel 

Add a component similar to https://codepen.io/alperentalaslioglu/pen/yPGgvP that could export an image and send it to backend for further ML operations.

**Comment by lo5** [comment]
@arnocandel We have a [canvas_card](https://h2oai.github.io/wave/docs/api/ui#canvas_card) as of v0.13. What is the intended use? Allow users to annotate images?

**Comment by mturoci** [comment]
Closing as we already have https://wave.h2o.ai/docs/widgets/form/image_annotator/.
