### ISSUE TITLE
Document patterns for in-app routing

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#335]
Our routing examples on tour are not enough, because they are useful only when the main content is just one card, which is almost never the case for more complex apps. App developers came up with a pattern that uses `q.page.drop` in main event loop. This is, however, inefficient rendering-wise and causes the UI to look slow as the intro transitions fire on every user action.

My first proposal is to simply extend this pattern in a way that `q.page.drop` could take additional param `except_of` (name whatever you like it) that would take card keys that should never be destroyed. These are nav, footer, header... all the components that form the main app structure.

**Comment by lo5** [comment]
I don't see a strong reason to overload `q.page.drop()` or expose a special API for this. Book-keeping cards in your app is fairly simple - see https://github.com/h2oai/wave/issues/554#issuecomment-776148455

Converting to a docs issue. Let me know if you have questions.

**Comment by mturoci** [comment]
Solved by https://wave.h2o.ai/docs/routing.
