### ISSUE TITLE
Tab Text Not Vertically Centered

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#337]
This is a question not a bug per se. I noticed that the text in this tab isn't vertically centered. Is that expected? 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/4793561/100543570-beaa7700-3205-11eb-81bb-68ce1564a868.png">

https://github.com/h2oai/wave-apps/pull/10

**Comment by lo5** [comment]
Addressed: https://github.com/h2oai/wave/commit/565b6f60c604970bb9d83ab2cc2e2a83774073fe
