### ISSUE TITLE
iFrame with OpenID protected website cannot connect

### ISSUE THREAD

**Issue by LenaRampula** [h2oai/wave#361]
Wave 0.9.1, Mac

Passing MLOps URL to 
```ui.form_card(box='4 2 -1 -1', items=[ui.frame(mlops, height='80%')]```

The iframe renders the login page but after clicking the ```login with openID``` button in the frame it displays the attached ```cannot connect``` page.

Code of the app is here: https://github.com/h2oai/sales-engineering/tree/wave_guide/Lena/Wave/data_pump

<img width="1208" alt="Screenshot 2020-12-06 at 09 32 14" src="https://user-images.githubusercontent.com/54841062/101344018-2192b280-3885-11eb-922c-512062b204ea.png">
<img width="1204" alt="Screenshot 2020-12-06 at 09 32 58" src="https://user-images.githubusercontent.com/54841062/101344027-248da300-3885-11eb-91dc-8ec4426a0d22.png">

**Comment by mturoci** [comment]
The reason MLOPs was blocked is the presence of [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) header which is a good security practice.

Tested with an OIDC-enabled app without the above-mentioned header and works fine, thus closing.
