### ISSUE TITLE
Add disabled prop to nav_item

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#376]
Allow disabling a nav item.

Steps to follow:
1. Setup the project.
2. Find `nav.tsx`.
3. Implement needed feature.
4. run `make generate` from project root - this generates python API.
5. Use your newly implemented prop to showcase its capabilities.
6. Add unit tests.

**Comment by Gnoblin44** [comment]
Hello @mturoci, I am new to GitHub. How can I start on this project?

**Comment by mturoci** [comment]
Hi @Gnoblin44, thanks for interest and sorry for late response due to Christmas. For more info about contributing and starting with this project, please see [contributing.md](https://github.com/h2oai/wave/blob/master/website/docs/contributing.md).
