### ISSUE TITLE
Card Rendering Fails with Re-Sizing Safari Browser Window

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#377]
I don't know fully how to reproduce this bug or the extent of it - basically I have seen weird behavior with cards loading (or not loading) across several apps running both locally and in the H2O.ai Cloud. 

This has come up when I load an app with my safari browser about half screen size (because I am screen recording safari and PyCharm).

1. Sentiment Analysis App Running in H2O AI Cloud
I could not see all of the cards and there was no scroll, so I make safari full screen. The browser widened but the app did not:
![image](https://user-images.githubusercontent.com/4793561/101832653-a4697680-3aec-11eb-92e7-82df57ed5ef7.png)

2. Credit Risk App running locally (I am not sure if this app has responsive layout or not)
When half screen cards do not load, if I widen the browser they are appear and then stay after I narrow it
https://h2oai.slack.com/files/UFY03NQ4V/F01GUFGRJTW/screen_recording_2020-12-10_at_1.29.37_pm.mov

I will keep adding examples and details to this issue as they come up - I know this is pretty vague at this point but I'm not seeing a lot of rhyme or reason

**Comment by mturoci** [comment]
Hi @mtanco, could you please check if you can still reproduce these? I had no luck with repros.

1 seems like Safari didn't manage to expand correctly, not something we can fix. I couldn't repro this though.
2 I didn't manage to repro even with video provided. I couldn't find Credit Risk on HAC, so tried only locally.

https://user-images.githubusercontent.com/64769322/106458049-1d9f9d00-6490-11eb-85a9-b4e528d8a58b.mov

**Comment by lo5** [comment]
@mtanco Is this still relevant? If not, we can close.
