### ISSUE TITLE
Header Bar Changing Height

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#382]
Wave 0.10.0 running locally on OS X - app was recently refactored by @dulajra to responsive AI which may be related?

https://h2oai.slack.com/files/UFY03NQ4V/F01GRGDMBNF/screen_recording_2020-12-11_at_12.21.04_pm.mov?origin_team=T0329MHH6&origin_channel=CFF49UG65

**Comment by mtanco** [comment]
@mturoci I am running safari and 15in screen

**Comment by mturoci** [comment]
Thanks @mtanco! You have uncovered a hidden Safari bug in addition to the original one. I was able to repro this issue as well.
