### ISSUE TITLE
The Tour's Hello World example is using the old Q name

### ISSUE THREAD

**Issue by sizrailev** [h2oai/wave#393]
#### Wave SDK Version, OS

0.10.0 macOS

#### Actual behavior

The Hello World! example has a title "A simple example to get you started with Q." instead of "... with H2O Wave"

#### Expected behavior

A simple example to get you started with H2O Wave.

#### Steps To Reproduce

1. Start the tour

**Comment by lo5** [comment]
@sizrailev Thanks for reporting! Fixed in a couple of other places, too.
