### ISSUE TITLE
Tour not working on Windows 10

### ISSUE THREAD

**Issue by letsfigureout** [h2oai/wave#397]
#### Wave SDK Version, OS

0.10.0, Windows 10, Python 3.7.8

#### Actual behavior

When I try and run the tour, I get a NotImplementedError message in the console. The webapp fails to load also giving me the same error as in the console.

#### Expected behavior

I expected the tour to run

#### Steps To Reproduce

1. Created a new virtual environment (virtualenv)
2. Extracted the wave tarball 
3. Activate the newly created virtualenv and install dependencies (pip install -r examples\requirements.txt)
4. Start waved
5. Run the tour using "wave run --no-reload examples.tour"

```
(.venv) C:\code\python\h2oai\wave-0.10.0-windows-amd64>wave run --no-reload examples.tour
----------------------------------------
 Welcome to the H2O Wave Interactive Tour!

 Go to http://localhost:10101/tour        
----------------------------------------  
INFO:     Started server process [22080]  
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:51930 - "POST / HTTP/1.1" 200 OK
Unhandled exception
Traceback (most recent call last):
  File "c:\code\python\h2oai\wave-0.10.0-windows-amd64\.venv\lib\site-packages\h2o_wave\server.py", line 265, in _process
    await self._handle(q)
  File ".\examples\tour.py", line 197, in serve
    await show_example(q, catalog[route])
  File ".\examples\tour.py", line 166, in show_example
    await active_example.start()
  File ".\examples\tour.py", line 48, in start
    sys.executable, os.path.join(example_dir, self.filename)
  File "C:\Python\Python37\Lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\Python\Python37\Lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Python\Python37\Lib\asyncio\base_events.py", line 462, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

I did find these posts relating to asyncio and creating a sub-process in windows but I the suggestion there didn't work.

https://stackoverflow.com/questions/45699932/asyncio-stdout-failing
https://docs.python.org/3/library/asyncio-subprocess.html#windows-event-loop

**Comment by shaz13** [comment]
++ `wave run examples.tour` is not working on Windows 10

**Comment by srini-x** [comment]
https://docs.python.org/3.7/library/asyncio-platforms.html#subprocess-support-on-windows

`SelectorEventLoop` on Windows does not support subproceses. On Windows, `ProactorEventLoop` should be used instead:

```python3
import asyncio

asyncio.set_event_loop_policy(
    asyncio.WindowsProactorEventLoopPolicy())

asyncio.run(your_code())

```

**Comment by srini-x** [comment]
I made it work on my windows machine by doing the following. looks like a `uvicorn` issue.

when we do `wave run` the main event loop is created by uvicorn.
so, adding

```python
asyncio.set_event_loop_policy(
    asyncio.WindowsProactorEventLoopPolicy())
```
to https://github.com/encode/uvicorn/blob/master/uvicorn/loops/asyncio.py fixed the issue reported above.

but I got another error

```
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
```

based on the advice from here: https://github.com/appveyor/ci/issues/1995#issuecomment-589987565

I made the following changes to `tour.py` at [line 36](https://github.com/h2oai/wave/blob/adf740b73731f9e7d6e711be27cbe9a103213f27/py/examples/tour.py#L36)

```python
env = dict(
    SYSTEMROOT=os.environ.get('SYSTEMROOT'),
    H2O_WAVE_EXTERNAL_ADDRESS=f'http://{_app_host}:{_app_port}'
)
self.process = await asyncio.create_subprocess_exec(
    sys.executable, '-m', 'uvicorn', '--port', _app_port, f'examples.{self.name}:main', env=env,
)
```

and it all worked.

**Comment by MarcSkovMadsen** [comment]
I experienced this issue as well

**Comment by lo5** [comment]
Thank you for reporting - we have a solution; currently testing.

**Comment by lo5** [comment]
Thanks for your patience!

You should be able to get the tour working on Windows by replacing your `examples\tour.py` with this corrected file:
https://github.com/h2oai/wave/blob/master/py/examples/tour.py

We'll push this out in the next release.

**Comment by letsfigureout** [comment]
Thanks! Confirmed it now works.
