### ISSUE TITLE
Set up CI using Github actions

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#399]
**Goal**
Canonical CI set up and configuration using Github actions; automate steps outlined in https://github.com/h2oai/wave/blob/master/DEV.md#cut-a-release

**Comment by mturoci** [comment]
@lo5 wdyt about automated changelog off commits? Proposal:

* Squash each PR with appropriate changlelog message / introduce some format for PR title.
* Generate the changelog off `git log`

**Comment by lo5** [comment]
I'd love to do that, but we can only make it work if:
- Every commit message is end-user (app author) facing.
- Commits are not too granular (results in a verbose change log).

**Comment by mturoci** [comment]
Wouldn't this be resolved by squashing? You can pick a custom commit message for this it if I recall correctly.

**Comment by lo5** [comment]
I change almost every message when I squash. Even then, the commit log is far too verbose for *users* of wave and needs curation/pruning: https://github.com/h2oai/wave/commits/master

**Comment by mturoci** [comment]
I see, will investigate other possibilities / flows that might be interesting for us.

**Comment by dulajra** [comment]
Squashing will make the log more meaningful. But still, I also think it will contain messages that a user doesn't expect in a changelog. One suggestion I have here is,

- Maintain a `develop` branch and merge all the feature/bug fix/typos PR to `develop` daily.
- Merge `develop` branch to `main` squashing unwanted messages when we are ready for a release. 
- Generate changelog from `main` branch commit history

But yeah there will be some additional work here.
