### ISSUE TITLE
Provide a way to refresh OIDC tokens from Python client

### ISSUE THREAD

**Issue by geomodular** [h2oai/wave#410]
## Motivation

Currently, we refresh both `access` and `refresh` tokens based on a user interaction. i.e. If user interacts with UI the Python client always get a fresh tokens. There might be a situation where user wants to poll a service and updates UI accordingly but `access` token has limited lifespan and user interaction is not an option.

We might want some kind of mechanism, function to be able to refresh tokens if needed.

## Notes
- We don't have a common way to call a function from client that communicates with `go` server, therefore task is doable but not trivial.
- We clearly see the use case in motivation but might not be a real problem anytime soon since DAI and MLops API can use `refresh` tokens and maintain it.
- We need to think if it's alright to be able to refresh user tokens if user went away.

**Comment by mturoci** [comment]
Resolved by #1230
