### ISSUE TITLE
h2oai.github.io/wave/docs/examples dead links

### ISSUE THREAD

**Issue by 0100101001010000** [h2oai/wave#413]
h2oai.github.io/wave/docs/examples links are dead, for example if you click on Hello World! the link it targets is:

    https://h2oai.github.io/wave/docs/examples/examples/hello-world

however the actual link seems to be:

https://h2oai.github.io/wave/docs/examples/hello-world

seems like you've got an extra _examples_ in the href that shouldn't be there.

Minor UX issue but the more people look at your product the more important it'll get :)

**Comment by shaz13** [comment]
The link - [https://h2oai.github.io/wave/docs/examples/hello-world/](https://h2oai.github.io/wave/docs/examples/hello-world/) works fine for me.

**Comment by mturoci** [comment]
Thanks for reporting the issue @0100101001010000!
