### ISSUE TITLE
httpx.ConnectError: [WinError 10061] 

### ISSUE THREAD

**Issue by milen-prg** [h2oai/wave#421]
#### Wave SDK Version, OS

Wave 0.10.0, Windows 10Pro, Python 3.8 64bit

#### Actual behavior
 At try to start hello_world.py

httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively
refused it

**Comment by lo5** [comment]
This looks to me like a firewall issue on your machine. 

`waved.exe` is a HTTP server, needs to be unblocked in your Windows Defender Firewall settings.

**Comment by stellasawicki** [comment]
> This looks to me like a firewall issue on your machine.
> 
> `waved.exe` is a HTTP server, needs to be unblocked in your Windows Defender Firewall settings.

Hi, I'm using Python 3.9 and have exactly the same issue. However I can't locate `waved.exe` anywhere in the hierarchy of my venv. 
Do you have any suggestions? Thanks in advance.

**Comment by goldentom42** [comment]
@stellasawicki thanks for trying out H2O Wave. 
Did you download the latest release available at this link ? 
https://github.com/h2oai/wave/releases
In the assets section you will find the H2O wave release for your OS.
Open a new command terminal, untar the archive, cd into it and start `waved.exe`. This runs the web server that will render your app.
Let me know if that works for you.

**Comment by stellasawicki** [comment]
@goldentom42 Thank you. Of course it helped.

**Comment by milen-prg** [comment]
@goldentom42,
Thank you!
I download from
https://github.com/h2oai/wave/releases
Inside is waved.exe.

I start first the waved.exe.
Than (in other command line window) execute the hello_world.py
And on localhost:10101/hello - all works!

Thanks! Now I continue to study this new python package.

**Comment by goldentom42** [comment]
Great news @milen-prg and @stellasawicki.
Please let us know if you hit any other issues.
Thanks.

**Comment by Khalilsqu** [comment]
> @stellasawicki thanks for trying out H2O Wave.
> Did you download the latest release available at this link ?
> https://github.com/h2oai/wave/releases
> In the assets section you will find the H2O wave release for your OS.
> Open a new command terminal, untar the archive, cd into it and start `waved.exe`. This runs the web server that will render your app.
> Let me know if that works for you.

Do I need to follow this step for version '0.23.1'?
