### ISSUE TITLE
Add a master table of contents page for all examples

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#423]
The current gallery page displays only thumbnails and titles without descriptions. 

It would be good to have a parallel ToC that lists all examples along with their descriptions.

**Comment by dulajra** [comment]
@lo5 Did you mean to keep the Gallery page as it is and add a new TOC page with titles and short descriptions (only text - no images)? I hope we can reuse the same description already available in each component example here also.

**Comment by lo5** [comment]
@dulajra Exactly! This line: https://github.com/h2oai/wave/blob/master/py/sync_examples.py#L116 generates the ToC, but might need additional implementation/configuration in Docusaurus. Needs the `useBaseUrl` patch as well, similar to `make_gallery_thumbnail()`.
