### ISSUE TITLE
How do we persist site-content across ./waved restarts

### ISSUE THREAD

**Issue by pnsvk** [h2oai/wave#450]
Let me take this opp to appreciate your work for a moment. 
I was really shocked to see such a kick-ass framework (on the likes of Meteor.js in JS-Land) in the python / lang.-agnostic ecosystem.
Can't stop exploring every bit of the framework..

Can you please let me know how we could strategise persisting our site content to a backend of any kind ? (DB, Cloud filesystem, etc, for multiple ./waved running instances to have a common-ground)

I see, recovering from logging is a way (although it was mentioned, not production ready) - don't really see it as a formal and reliable way to load all of the pages.. (for ex: plots created, reports generated, etc.) -- This too would work only at a local level (not in a multi-containerized waved instances as mentioned above)

Only way I could think of, is to depend on wave-apps, and let them do all of it, letting "waved" mostly be a proxy.. 

My concern is more around wave-scripts.

**Comment by lo5** [comment]
@pnsvk Thanks for the kind words :)

At present, the only way to recover content is via the server log.

The Wave server is best thought of as a content-cache + web-server rolled into one. If additional persistence/reliability is desired, it's up to the app or script. 

The sweet-spot topology for Wave scripts is either:
`source -> wave-script -> wave-server -> web-browser`
or 
`source -> database -> wave-script -> wave-server -> web-browser`

**Comment by lo5** [comment]
> in a multi-containerized waved instances

We don't have replication or failover between multiple waved instances yet. I'm open to ideas.

**Comment by pnsvk** [comment]
Thank you for caring to respond on this. Will explore and get back if I find anything worth sharing here.
