### ISSUE TITLE
small_series_stat_card in wave app not in wave script

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#457]
#### Is your feature request related to a problem? Please describe

This feature request is not related to a problem. Actually, I don´t know how to do it. 

In several times I try to implement: `ui.small_series_stat_card()` in wave app. But I didn´t because it needed to updated by a `while True:` loop. So, I don´t know how to implement this wave component in wave app and not in wave script.

#### Describe the solution you'd like

Maybe if it´s possible to implement now. I need a example with pandas to understand how it´s works with dataframes. If do not possible to implement now. Could be implement `ui.small_series_stat_card()` wave component in wave app and not in wave script.

#### Describe alternatives you've considered

One solution, could be implemenet this component with pandas. In this way, it´s not needed a loop to update. Just needed at least two pandas series.

**Comment by lo5** [comment]
@sergiomora03 You can set a card's `plot_data` directly, like this:

```py
    q.page['total_users'] = ui.tall_series_stat_card(
        box='...',
        title='Total Users',
        value='68K',
        aux_value='Down 6%',
        plot_type='interval',
        plot_color='$blue',
        plot_category='date',
        plot_value='users',
        plot_zero_value=0,
        plot_data=data(
            fields=['date', 'users'],
            rows=[
              ('2020-12-18T05:41:32.355774Z', 45),
              ('2020-12-19T05:41:32.355774Z', 34),
              ('2020-12-20T05:41:32.355774Z', 75),
            ],
            pack=True,
        ),
    )
```

**Comment by sergiomora03** [comment]
I tried putting this:

```python
        q.page['total_users'] = ui.tall_series_stat_card(
        box='7 4 3 6',
        title='Total Users',
        value='68K',
        aux_value='Down 6%',
        plot_type='interval',
        plot_color='$blue',
        plot_category='date',
        plot_value='users',
        plot_zero_value=0,
        plot_data=data(
            fields=['date', 'users'],
            rows=[
              ('2020-12-18T05:41:32.355774Z', 45),
              ('2020-12-19T05:41:32.355774Z', 34),
              ('2020-12-20T05:41:32.355774Z', 75),
            ],
            pack=True,
        ),
    )
```

And I had this error:

```
Error
Traceback (most recent call last):
  File "c:\users\samora\anaconda3\lib\site-packages\h2o_wave\server.py", line 265, in _process
    await self._handle(q)
  File ".\app.py", line 219, in serve
    plot_data=data(
TypeError: 'DataFrame' object is not callable
```

what have I done wrong?

**Comment by mtanco** [comment]
@sergiomora03 can you confirm that your script has `from h2o_wave import data` ?

**Comment by sergiomora03** [comment]
I don´t have it!!

Thanks @mtanco 🤗
