### ISSUE TITLE
What's the docker deployment best practice?

### ISSUE THREAD

**Issue by occoder** [h2oai/wave#460]
I try to practice wave server in Ubuntu 20.04 docker-ce environment.
One container is used to hold wave server and the other one holds the script referencing the "hello"page.
In order to let these two containers see each other meanwhile let the host browser to verify the front end effect, I use "docker run --network host the_docker_image" command.
From the wave server terminal, I can see the message log coming from the script container.
But when I open the browser to check localhost:10101/hello, the browser shows me "404 page not found".
And it seems as long as "localhost:10101" is the prefix, the browser always gives me back "404 page not found".

I'm wondering if there is a canonical way to deploy wave server and script within docker environment?
Thanks for any advice.

**Comment by occoder** [comment]
Oh, I guess I've found the root cause.
The splash message shows the "webroot": "/www" which is supposed to be "webroot":"/root/wave/www" as docker takes /root as the default home.
That explains why the wave server lost the correct route.

**Comment by occoder** [comment]
If I enter the container in interactively mode instead of through container auto entrypoint and change directory to where waved executable resides and manually start ./waved, then I can get the correct webroot, i.e. /root/wave/www

**Comment by occoder** [comment]
Since this problem is not specific to docker environment, herein I report a bug that waved server webroot is incorrectly set if it is started up from PATH search instead of from current directory, i.e. ./waved

**Comment by lo5** [comment]
@occoder - we don't have any documented best practices related to deployments on Docker. We're open to ideas. The easiest way is to run both the Wave server and your app in the same container. 

Regarding your other question - I'm not sure what the specific bug is. The rules for interpreting the web root path are simple -absolute paths are used as-is, everything else is interpreted relative to the current working directory.

**Comment by occoder** [comment]
@lo5 Thank you for the reply.
Considering the waved server could be a shared service among multiple clients, it might be better to leave it in a separate container.
The bug could be reproduced as follows:
1. copy wave folder to $HOME/wave folder in Dockerfile
2. set ENV PATH $HOME/wave:$PATH in Dockerfile
3. set ENTRYPOINT ["waved"]
4. start the container
5. the waved server starts successfully, but the webroot shows up routing to "/www" directory where actually should be "root/wave/www" instead
6.  open localhost:10101, it shows "404 page not found"

**Comment by sairaamv** [comment]
I made a symbolic link to `/www` folder and it works fine. Here is my Dockerfile

```
FROM ubuntu:latest
COPY . /root/wave/
RUN ln -s /root/wave/www /www
CMD ["/root/wave/waved"]
EXPOSE 10101
```

I will hook up the local examples/tour. I think, we may need to EXPOSE some more ports is my thought

**Comment by sairaamv** [comment]
@occoder , https://h2oai.github.io/wave/docs/configuration/ 
Found this to change the default `www` folder location in waved by passing `-web-dir` and it works fine. Would it answer the docker challenge?

**Comment by occoder** [comment]
> @occoder , https://h2oai.github.io/wave/docs/configuration/
> Found this to change the default `www` folder location in waved by passing `-web-dir` and it works fine. Would it answer the docker challenge?

Thanks @sairaamv , this is yet another workaround.
