### ISSUE TITLE
Tour not working on Linux

### ISSUE THREAD

**Issue by edlee123** [h2oai/wave#462]
#### Wave SDK Version, OS

0.10.0, Ubuntu Focal Fossa, Python 3.8.5

#### Actual behavior

Tour of Wave, Step 2:

```
wave run --no-reload examples.tour

Command 'wave' not found, did you mean:

  command 'kwave' from deb kwave (19.12.3-0ubuntu1)
  command 'save' from deb atfs (1.4pl6-14)
  command 'gwave' from deb gwave (20190116-2)
  command 'dave' from deb libhttp-dav-perl (0.49-1)
  command 'weave' from deb texlive-binaries (2019.20190605.51237-3build2)

Try: sudo apt install <deb name>
```

If I do this from the virtual env:

`python3 tour.py`

There will be a "waiting for content" message at http://localhost:10101/tour

#### Expected behavior

See step 3 of the tour: https://h2oai.github.io/wave/docs/tour

#### Steps To Reproduce

https://h2oai.github.io/wave/docs/installation

https://h2oai.github.io/wave/docs/tour

**Comment by lo5** [comment]
@edlee123 - the `wave` command is only available inside the virtual environment.

Can you please retry with:
```
source venv/bin/activate
wave run --no-reload examples.tour
```

Then go to http://localhost:10101/tour

**Comment by edlee123** [comment]
Thank you  @lo5 - I don't know why but I was pretty sure I activated the virtual env when I tried it.  Turned on my computer this morning and works.
