### ISSUE TITLE
ui.plot/mark hover data looks non intuitive 

### ISSUE THREAD

**Issue by tkmaker** [h2oai/wave#472]
#### Wave SDK Version, OS

Version 0.10.0. Mac OS. 

#### Actual behavior

Plot hover looks broken. (see screenshot). Was expecting to see X and Y labels but it includes the legend across the Y values. For cases where X axis is date, it might make sense to see time over different Y values labeled this way but for other data, it looks almost like something is missing. It might be more intuitive to add `legend: (x, y)` on hover. 

 Attaching sample code. 
![Screen Shot 2021-01-04 at 3 03 16 PM](https://user-images.githubusercontent.com/5984232/103588556-4c7d2000-4e9e-11eb-8955-cb63293ae617.png)

```
from h2o_wave import Q, ui, app, main, data


@app('/')
async def server(q: Q):
    plot1(q)
    await q.page.save()


def plot1(q: Q):
    v = q.page.add('plot1', ui.plot_card(
        box='1 1 -1 -1',
        title='Route Plot',
        data=data('long lat type'),
        plot=ui.plot(
            [ui.mark(type='line', x='=long', y='=lat', x_title='Longitude', color='=type', x_min=0, y_min=0,
                     y_title='Latitude'),
             ])
    ))
    v.data = [(1,3,'abc'), (2,5,'abc'), (3,4,'def'), (5, 4, 'def')]
```

#### Expected behavior

(A clear and concise description of what you expected to happen.)

#### Steps To Reproduce

1. Do this
2. Do that
3. Do something else

**Comment by mturoci** [comment]
Resolved by #644.
