### ISSUE TITLE
Why not wave server packaged within python / R package?

### ISSUE THREAD

**Issue by sairaamv** [h2oai/wave#475]
Hi @lo5,

Any reason not to have wave server within h2o_wave package?
Like h2o-3, why not have the wrapper together was my thought. There could be better reasons to have it separate and I am curios about your take

Thanks

**Comment by mtanco** [comment]
This is slated for 0.12.0: https://github.com/h2oai/wave/issues/250

**Comment by sairaamv** [comment]
Awesome. Thanks @mtanco
