### ISSUE TITLE
Allow configuring wave daemon using a configuration file

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#481]
#### Is your feature request related to a problem? Please describe
Some organizations may have defaults or security best practices that they require for all internal products. They would not be able to use a product where they could not easily guarantee their needs were met. 

#### Describe the solution you'd like
A configuration file for the waved server which is applied to all applications would remove this responsibility from each individual developer and ensure compliance for productionalized applications at the organization

#### Additional context

Here is a list of specific items that I have heard would be needed in the server config file:
* `ui.file_upload` disabled
* `password=True` forced if the word `password` is used in the label of a textbox 
* Turn google analytics telemetry off

**Comment by lo5** [comment]
Implementation: Add `-config` option to specify a `.toml` configuration file. Priority: command line args > env vars > config file.

**Comment by lo5** [comment]
Update: `waved` [can be configured using env vars now](https://github.com/h2oai/wave/blob/master/website/docs/configuration.md#environment-variables).

**Comment by mtanco** [comment]
Bump as this came up again today
