### ISSUE TITLE
wave app don´t run in linux

### ISSUE THREAD

**Issue by sergiomora03** [h2oai/wave#482]
#### Wave SDK Version, OS

wave-0.10.0-linux-amd64.tar.gz
CentOS Linux release 7.8.2003 (Core)

#### Actual behavior

Wave application still launches with **'localhost'** and does not launch with **server IP**.

#### Expected behavior

It was expected that at least the application would show up with the server's IP

#### Steps To Reproduce

1. Run `./waved`
2. terminal return:
```
2021/01/12 13:27:13 #
2021/01/12 13:27:13 # ┌─────────────────────────┐
2021/01/12 13:27:13 # │  ┌    ┌ ┌──┐ ┌  ┌ ┌──┐  │ H2O Wave
2021/01/12 13:27:13 # │  │ ┌──┘ │──│ │  │ └┐    │ 0.10.0 20201129141901
2021/01/12 13:27:13 # │  └─┘    ┘  ┘ └──┘  └─┘  │ © 2020 H2O.ai, Inc.
2021/01/12 13:27:13 # └─────────────────────────┘
2021/01/12 13:27:13 #
2021/01/12 13:27:13 # {"address":":10101","t":"listen","webroot":"/home/desarrollo/wave/www"}
```
3. Run `$ wave run hello_world.py`
4. The wave terminal return: `2021/01/12 13:27:49 # {"host":"http://127.0.0.1:8000","route":"/hello","t":"app_add"}`
5. The server terminal return: 
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [13610] using statreload
INFO:     Started server process [13612]
INFO:     Waiting for application startup.
INFO:     Application startup complete. 
```
6. No more **INFO** was shown. expected at least: `INFO:     127.0.0.1:53722 - "POST / HTTP/1.1" 200 OK`
7. NOTE: the wave terminal still run the app in: `http://127.0.0.1:8000` not in server´s IP.
8. The script is come from [wave/docs/tutorial-hello](https://h2oai.github.io/wave/docs/tutorial-hello)

**Comment by lo5** [comment]
@sergiomora03 - you can set the ip:port to listen to using the `-listen` argument to `waved`, e.g. `waved -listen 192.168.2.45:80`. See https://h2oai.github.io/wave/docs/configuration

**Comment by sergiomora03** [comment]
Thanks @lo5 I just add: `H2O_WAVE_ADDRESS=http://192.168.2.45:80 wave run app`. When run the wave app.
