### ISSUE TITLE
Visible prop on textbox not working

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#484]
via @5675sp 
#### Wave SDK Version, OS

0.10.0

#### Actual behavior

After setting `visible` prop as `False`, textbox component is visible nonetheless.

#### Expected behavior

Textbox should not be visible.

**Comment by mturoci** [comment]
The problem is that `style` attr is not applied to Fluent component wrapper. This causes applying `display:none` on inner `input`, leaving Label and other divs visible in this particular case.

My proposal is to unify the visibility handling on [parent (Form) component level](https://github.com/h2oai/wave/blob/048885823f9fbeaa0e1fcfc1fffedabed8efcec1/ui/src/form.tsx#L205) via div wrapper with visibility handling logic, instead of handling it down at component level (e.g. textbox).

Related issue: #150

**Comment by lo5** [comment]
@mturoci Yes, it makes sense to do this in `XComponents`. The currently implementation is messy and repetitive. I don't recall why we decided to do this the component-level in the first place.

Secondly, if `visible` is going to be a property on every `XComponent`, we can make wavegen generate it instead.
