### ISSUE TITLE
Examples Tour yields errors in multi container setup due to references to 127.0.0.1

### ISSUE THREAD

**Issue by dirkdevriendt** [h2oai/wave#498]
Great idea and application!
Ran into a minor issue trying to test drive it:

#### Wave SDK Version, OS

wave-0.10.0-linux-amd64.tar.gz
Ubuntu (in docker)

#### Actual behavior

Examples don't work (various connection errors)
I assume this should be possible since the configuration documentation mentions split servers as an option

#### Steps To Reproduce

1. Build docker image
2. Run one container with the waved server and one with the wave command for the examples.tour app

First error is the uvicorn listening on 127.0.0.1 (code in cli.py)
Got around this with a `uvicorn --host "0.0.0.0" examples.tour:main` command

But some examples either reference the server or require communication, and possibly use defaults that don't get overwritten properly (the more static examples work fine and running it all in one container works fine)

Envvars set:
H2O_WAVE_ADDRESS=http://wave-server:10101
H2O_APP_ADDRESS=http://wave-examples:8000               # some confusion from diff in docs vs code which one is right
H2O_WAVE_APP_ADDRESS=http://wave-examples:8000    # some confusion from diff in docs vs code which one is right
H2O_WAVE_INTERNAL_ADDRESS=http://wave-examples:8000  # just to be sure
H2O_WAVE_EXTERNAL_ADDRESS=http://wave-examples:8000  # just to be sure

Error in the ToDo app:

```
wave-examples    |  Go to http://localhost:10101/tour
wave-examples    | ----------------------------------------
wave-examples    | INFO:     172.20.0.2:53034 - "POST / HTTP/1.1" 200 OK
wave-examples    | INFO:     172.20.0.2:53034 - "POST / HTTP/1.1" 200 OK
wave-examples    | INFO:     Started server process [10]
wave-examples    | INFO:     Waiting for application startup.
wave-examples    | ERROR:    Traceback (most recent call last):
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
wave-examples    |     yield
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
wave-examples    |     (status_code, headers, stream, ext,) = await transport.arequest(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest
wave-examples    |     response = await connection.arequest(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 93, in arequest
wave-examples    |     self.socket = await self._open_socket(timeout)
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 119, in _open_socket
wave-examples    |     return await self.backend.open_tcp_stream(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
wave-examples    |     return await self.backend.open_tcp_stream(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 246, in open_tcp_stream
wave-examples    |     return SocketStream(
wave-examples    |   File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
wave-examples    |     self.gen.throw(type, value, traceback)
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
wave-examples    |     raise to_exc(exc) from None
wave-examples    | httpcore.ConnectError: [Errno 111] Connect call failed ('127.0.0.1', 10101)
wave-examples    |
wave-examples    | The above exception was the direct cause of the following exception:
wave-examples    |
wave-examples    | Traceback (most recent call last):
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 526, in lifespan
wave-examples    |     async for item in self.lifespan_context(app):
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 467, in default_lifespan
wave-examples    |     await self.startup()
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 502, in startup
wave-examples    |     await handler()
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/h2o_wave/server.py", line 228, in _register
wave-examples    |     await self._wave.call('register_app', mode=self._mode, route=self._route, address=_config.app_address)
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/h2o_wave/server.py", line 185, in call
wave-examples    |     return await self._http.post(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1633, in post
wave-examples    |     return await self.request(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1371, in request
wave-examples    |     response = await self.send(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1406, in send
wave-examples    |     response = await self._send_handling_auth(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1444, in _send_handling_auth
wave-examples    |     response = await self._send_handling_redirects(
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
wave-examples    |     response = await self._send_single_request(request, timeout)
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1502, in _send_single_request
wave-examples    |     (status_code, headers, stream, ext,) = await transport.arequest(
wave-examples    |   File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
wave-examples    |     self.gen.throw(type, value, traceback)
wave-examples    |   File "/usr/local/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
wave-examples    |     raise mapped_exc(message, **kwargs) from exc  # type: ignore
wave-examples    | httpx.ConnectError: [Errno 111] Connect call failed ('127.0.0.1', 10101)
```

**Comment by dirkdevriendt** [comment]
FYI: Same (or at least similar) result in wave-0.11.0-linux-amd64
Let me know if there is anywhere I can help with reproducing or qualifying whether it is a bug.

Note: also tested the `waved -listen` option, but that -predictably- did not make a difference.

**Comment by lo5** [comment]
@dirkdevriendt - Thanks for reporting - we'll have to investigate and get back.

**Comment by dirkdevriendt** [comment]
Not sure if it helps, because I got a bit lost in the different initializations in uvicorn, core, server and cli, but I did seem to notice the properties in _config are set correctly at first, but then reloaded with the 127.0.0.1 defaults.

**Comment by dirkdevriendt** [comment]
Just found out that, in version 0.11.0, my own test wave app seems to work fine (which was not the case in 0.10.0), so I'm thinking the remaining error must be something with the method the tour code uses to launch or run the demo apps.

**Comment by lo5** [comment]
Could be related to this fix: https://github.com/h2oai/wave/commit/5aada5fbeccceed14b22b92f299e1d82e36f6a07

**Comment by Kojon74** [comment]
@dirkdevriendt were you able to figure this out? I am also having similar issues trying to use uvicorn to deploy my web app to heroku

**Comment by dirkdevriendt** [comment]
No, but my self written apps work in version 0.11.0, so I think the above error is not relevant anymore and the remaining error in the Tour is related to code in the tour app itself, not to the wave server as such.

I do use `./waved -listen 0.0.0.0:10101` in the server container. Not sure if that would make a difference in the end (the default is `:10101` according to the docs so I don't think it should).

**Comment by Kojon74** [comment]
Do you need to use a container (with the wave directory) to deploy a wave app?

**Comment by dirkdevriendt** [comment]
No, not at all, please refer to the docs for the standard installation instructions: https://h2oai.github.io/wave/docs/installation
I am not familiar with the requirements for Heroku deployments.

**Comment by vopani** [comment]
I'm using Wave v0.12.1 (on Ubuntu 18.04) and it doesn't seem to use / take environment variables when set.
Tried same way as the first post and it always uses the default localhost:10101 address.

**Comment by lo5** [comment]
This was happening because tour.py always launched apps at 127.0.0.1:10102. This should be fixed now. The apps are now launched using the hostname from `$H2O_WAVE_APP_ADDRESS`.

Verification:

Start container 1:

    $ sudo docker run -it -v ~/downloads/wave:/wave --network host ubuntu bash

Run server:

    root@ugh:/wave# ./waved

Start container 2:

    $ sudo docker run -it -v ~/downloads/wave:/wave --network host python bash

Run apps or tour.  The tour listens at :8000. The tour makes apps listen at :10102.  All the following forms work:

    root@ugh:/wave# ./venv/bin/uvicorn examples.todo:main

    root@ugh:/wave# H2O_WAVE_APP_ADDRESS=http://192.168.1.12:8000 ./venv/bin/uvicorn --host "0.0.0.0" examples.todo:main

    root@ugh:/wave# H2O_WAVE_ADDRESS=http://192.168.1.12:10101 H2O_WAVE_APP_ADDRESS=http://192.168.1.12:8000 ./venv/bin/uvicorn --host "0.0.0.0" examples.todo:main

    root@ugh:/wave# H2O_WAVE_APP_ADDRESS=http://192.168.1.12:8000 ./venv/bin/uvicorn --host "0.0.0.0" examples.tour:main
