### ISSUE TITLE
Automatic reload triggers app to restart when uploading files

### ISSUE THREAD

**Issue by dirkdevriendt** [h2oai/wave#499]
`wave-0.10.0-linux-amd64.tar.gz on Ubuntu (in docker)`
note: not including the --no-reload option when starting the wave app

I assume the app also monitors the waved-managed ./data folder, detects a file being uploaded from the browser and reloads the app.
Not sure if this is intended behaviour and/or if there is a way to black-/whitelist folders

**Comment by dirkdevriendt** [comment]
Apologies, after a number of changes I can't reproduce it anymore, so I'm guessing I was doing something that triggered the reload before.

**Comment by lo5** [comment]
@dirkdevriendt You might have already figured this out, but in general the `wave` CLI is a development utility, and it's better to directly use `uvicorn` (or your preferred launcher) to run apps: `wave run --no-reload foo` is equivalent to `uvicorn foo:main`

See https://h2oai.github.io/wave/docs/deployment
