### ISSUE TITLE
ui.mark color for annotations 

### ISSUE THREAD

**Issue by tkmaker** [h2oai/wave#503]
#### Wave SDK Version, OS

0.10.0

Trying to use plot annotations for a horizontal line of a specific color.  The `color` arg works fine for the main plot but not for the annotations making it difficult to actually see the line on the same gray background.

eg:
I want the max/min bed capacity to be visible lines of a certain color. 

```py
ui.plot([ui.mark(type='line', x='=time', y='=beds', x_min=0, y_min=0-GlobalVars.bed_capacity, y_max=GlobalVars.bed_capacity+50,
                                      x_title='Time', y_title='Hospital Bed Availability', color='#33BBFF'),
                              ui.mark(y=GlobalVars.bed_capacity, label='Max Capacity', color='#33BBFF'),
                              ui.mark(y=0, label='Min Capacity', color='#33BBFF')]
                             ))
```

<img width="1627" alt="Screen Shot 2021-01-17 at 11 38 51 PM" src="https://user-images.githubusercontent.com/5984232/104885921-b0cbc500-591d-11eb-9786-e18e81dac057.png">

**Comment by mturoci** [comment]
Hi @tkmaker,

It seems like line color is controlled by `ref_stroke_color`. Could you please try that and let me know if that worked?

**Comment by lo5** [comment]
@tkmaker Is this still relevant? If not, we can close.

**Comment by tkmaker** [comment]
using `ref_stroke_color` fixes the issue
