### ISSUE TITLE
Code snippets for IDEs

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#506]
It might be a good idea to make an IDE extension / plugin (for VSCode and PyCharm) that would provide faster and easier way of building  apps:

https://user-images.githubusercontent.com/64769322/104925575-52dfc180-599f-11eb-9f98-cfdc39a5c71a.mov

We should be able to generate such snippets in the same way we generate our API for other languages. On top of that, we can add our own snippets for common Wave patterns like hash routing or client initialization. 

cc @lo5 @geomodular for discussion

**Comment by lo5** [comment]
Great idea! What would be a good way for us to work towards this? Specifically, have a central source of snippets that we can draw from, for both VSCode and Pycharm, that can be maintained over time as we expand our card/component library.

**Comment by mturoci** [comment]
Both VSC and Pycharm have different snippet formats and rules so I am not sure if we can centralize them easily. I propose to 
1. use the TS parser (in a similar way we use for `wavegen`) to autogenerate basic API the snippets.
2. More complex snippets should be written by hand in a separate file, then merged with the generated ones ^^
3. We could distribute these together with importing instructions per IDE or a better option could be to wrap them in extension/plugin. This would make installation easy and would allow us to add other features besides just snippets if needed.

**Comment by srini-x** [comment]
Yes, snippets will be very nice. I have been thinking about this.

**Comment by maxjeblick** [comment]
Idea for a `tqdm`-like progress bar
```
async def iterate_over_something(q: Q):
    async for idx in progress_bar(q, list(range(100))):
        time.sleep(0.05)


async def progress_bar(q: Q, iteratble, title='Progres bar'):
    start_time = time.time()
    for idx, item in enumerate(iteratble):
        await show_progress(q, idx + 1, 100, start_time, title=title)
        yield item


async def show_progress(q: Q,
                        tasks_completed: int,
                        total_tasks: int,
                        start_time: float, title):
    progress_percent = round((tasks_completed / total_tasks) * 100, 2)
    hours, rem = divmod(time.time() - start_time, 3600)
    minutes, seconds = divmod(rem, 60)
    minutes = minutes + hours * 60  # don't display hours, process shouldn't take that long
    q.page['main'].items = \
        [ui.progress(label=title,
                     caption=f'{tasks_completed} of {total_tasks} items ({progress_percent}%) completed. '
                             f'Time elapsed = {int(minutes):0>2}:{int(seconds):0>2}',
                     value=progress_percent / 100)]
    await q.page.save()
```
