### ISSUE TITLE
Allow text wrapping in string table cell

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#515]
via @mtanco 

@lo5 The only thing I am wondering about is where should we put the switch within API. Directly on `TableColumn` as `wrap`? This would however apply to text types only. Another option would be to wrap by default and swap it with current elipsis.

**Comment by mturoci** [comment]
related: via @goldentom42 

We could also allow tooltips on hover instead of wrapping.

Proposal: provide an `overflow` prop with 3 possible values:
* `ellipsis` - default, the three dots
* `wrap` - wrap the text in the column
* `tooltip` - show tooltip with full value

Another possible solution is to always show tooltips by default for every cell and go with the proposal above ^^

**Comment by goldentom42** [comment]
@mturci has there been any progress on this one ? thx.

**Comment by mturoci** [comment]
Not yet, but we can prioritize if needed.

**Comment by psinger** [comment]
@mturoci This would be quite handy for our app, as we have some larger tables with certain column width restrictions and it would be nice to hover over a cell, and be able to read the whole content.

**Comment by goldentom42** [comment]
@mturci if you can prioritize that would be awesome ! thank you.

**Comment by mturoci** [comment]
cc @lo5 for API review

Related: #1096
