### ISSUE TITLE
[Performance] Delay while switching between tabs

### ISSUE THREAD

**Issue by gbakthavatchalam** [h2oai/wave#517]
#### Wave SDK Version, OS

Wave: 0.10.0
OS: MacOS Catalina
Browser: Google chrome Version 87.0.4280.88 (Official Build) (x86_64)

#### Actual behavior

While switching between different insight types by clicking on the tabs, we can see considerable delay to load the content.

#### Expected behavior

Minimal or no delay to load the content

#### Steps To Reproduce

1. Follow the development guide and start the app locally.
2. Click on the `2-sigma` dataset and click on `Analyze` button
3. Select few columns from different categories (Measure, Temporal, Categorical) and click Next
4. Click `Analyze` to see the results
5. There will be a delay when switching between different tabs of the page. We could clearly notice a delay of 3-5 seconds.

### Debugging done so far
1. Profiled the python code by placing few timers and logged them. And in all cases, the request was served by the backend code within 0.3 seconds
2. Used Google Chrome->Developer Tools->Performance and noticed that `Scripting` (Javascript) takes unusually longer time when switching between the tabs
3. At the same time, we could see a spike in the CPU usage by Google chrome in the `Activity Monitor`

**Comment by lo5** [comment]
@gbakthavatchalam Have you isolated the problem to the tabs or is it the content on the page? We have no control over the content or the vega-lite visualization's performance.

**Comment by gbakthavatchalam** [comment]
Hi @lo5 , I think it is due to the content on the page because I have not experienced any delay while using tabs in other pages. I can double check that once.

**Comment by pramitchoudhary** [comment]
@lo5 @gbakthavatchalam it makes sense to check the content on the page and isolate the problem further.
