### ISSUE TITLE
Handle Events in Dashboard Apps

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#527]
#### Is your feature request related to a problem? Please describe

When using the Dashboard Demo some dashboards, like mint, have clickable items. When someone clicks the menu the home page (red dashboard) shows but the hash routing stays on the previous dashboard. Which can be confusing, especially to new users. 

#### Describe the solution you'd like
Go through each dashboard page and handle user events completely within that page.

**Comment by mturoci** [comment]
Note for anyone taking this up: Dashboard app code is located [here](https://github.com/h2oai/wave/tree/master/py/demo).

**Comment by aruiz2** [comment]
We can try to tackle the issue if that is ok!

**Comment by mturoci** [comment]
Go for it!

**Comment by Qingyang-Sophia** [comment]
Could we get a more specific description of this issue? Is the clickable menu the button on the top-left that is used to switch between dashboards? We try to switch between dashboards but the URL (e.g. http://localhost:10101/#dashboards/red) is changing. We are wondering in which case the hash routing stays on the previous dashboard. 
Thank you for any help!

**Comment by mturoci** [comment]
It seems like this has been fixed along the way somehow (as this is a 2-year-old issue). However, you can change the `xl` breakpoints to `xs` so that dashboards are shown irrespective of browser window size.
