### ISSUE TITLE
base_url argument or hidden option for waved server?

### ISSUE THREAD

**Issue by mklechan** [h2oai/wave#588]
Hi,
  Is there a way today, that I can specify a base url for the waved server? Maybe a config file somewhere? 
 I am running wave behind a proxy and the requests for static files, css, js is pointing at the wrong url

Thanks
-Mark

**Comment by lo5** [comment]
It's not possible to specify a base URL today, but it's reasonable to expect one.

**Comment by lo5** [comment]
Fixed via https://github.com/h2oai/wave/commit/41a43ba63b0b7afb859e877b50ca478c2e46f22e
