### ISSUE TITLE
Add Select / Unselect All for Table Filter

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#602]
#### Is your feature request related to a problem? Please describe
When looking at data in the table it's common to want to see all rows _except_ with a specific value. Today, you have to check mark every option except the one you'd like to filter. In this case I only had 12ish unique values, but it would be arduous with 100s 

![image](https://user-images.githubusercontent.com/4793561/110273923-804df200-7f82-11eb-8c27-5aaf7f6ea4e3.png)

#### Describe the solution you'd like

It would be nice to have a `select all` option to quickly unselect one or two options to filter by

**Comment by mturoci** [comment]
Implementation note: Make the UX and style the same as select / unselect all in `ui.checklist`.
