### ISSUE TITLE
Code editor card

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#624]
via @srini-x 

#### Is your feature request related to a problem? Please describe

There is currently no card for live-coding apps.

#### Describe the solution you'd like

Provide a card with embedded [monaco-editor](https://microsoft.github.io/monaco-editor/) or other suitable alternative.

#### Questions for discussion
What should a UI look like with best possible UX in mind? This includes:
* how/when would the card be saved
* how it should be marked as dirty

**Comment by lo5** [comment]
Including Monaco by default will bloat up our js bundle. Let's address after #297. In any case, we have this covered in #278.
