### ISSUE TITLE
Error Loading ASGI App. Could not import module "app"

### ISSUE THREAD

**Issue by AlexWenner1** [h2oai/wave#626]
I am attempting to launch my app.py file as instructed by the tutorial but keep running into this error. I have had this in the past, but after killing it and re running "wave run ..." it seems to have worked. Now, I am having no luck with that. 
![image](https://user-images.githubusercontent.com/42550706/111717894-f9710300-8826-11eb-9169-c8121790ab2e.png)

**Comment by AlexWenner1** [comment]
I was running it incorrectly. After running it correctly, I get "Error loading ASGI app. Attribute "main" not found in module app"

**Comment by lo5** [comment]
You'll need `from h2o_wave import main` in `app.py`.

**Comment by AlexWenner1** [comment]
Thanks so much, it worked!
