### ISSUE TITLE
Stacked Interval Plot looks strange

### ISSUE THREAD

**Issue by meganjkurka** [h2oai/wave#642]
I have a stacked plot that is not looking how I would expect.  You can see that `LIMIT_BAL` only shows rank 1.

Data:

```py
rows:[["rank","freq","variable"],
[["3",8,"LIMIT_BAL"],
["2",20,"LIMIT_BAL"],
["1",22,"LIMIT_BAL"],
["3",8,"EDUCATION"],
["2",23,"EDUCATION"],
["1",19,"EDUCATION"],
["3",34,"PAY_1"],
["2",7,"PAY_1"],
["1",9,"PAY_1"]]]
```

![image](https://user-images.githubusercontent.com/20548431/111795958-11d03480-889e-11eb-82bc-63da6025481b.png)

Code used:

```py
plot=ui.plot([
                    ui.mark(type='interval', x='=freq', y='=variable', stack='=auto', color='=rank',
                            y_min=0, 
                            color_domain=['1', '2', '3', '4', '5'],
                            color_range='#0091ad #3fcdda #83f9f8 #d6f6eb #fdf1d2',
                    )
                ])
```

**Comment by mturoci** [comment]
Hi @meganjkurka,

it seems like there is a typo in your code. Can you please try with `stack='auto'` instead of `stack='=auto'`. There seem to be extra `=` in your code.

**Comment by meganjkurka** [comment]
Thank you for catching that. That fixed it!
