### ISSUE TITLE
Allow displaying additional information on plot tooltips

### ISSUE THREAD

**Issue by fousasg** [h2oai/wave#644]
- Can we add more information to show on hover?  See Picture below of hover only being the original info ( I don't see a specific mark or anything that looks like this, but I can see it being requested a lot, Plotly and others allow this)

![image (2)](https://user-images.githubusercontent.com/20576978/111821487-a0fb3d80-88da-11eb-8738-7bb42d5b9bda.png)

-The events of a Line plot return the whole line when you click on it, what the user probably wants is the left and right point of that line segment. A work around is to add 2 marks, a line AND a point. This solution is working today but the user is having a hard time not accidentally clicking on the line. Also it looks a little clunky

**Comment by mtanco** [comment]
I would propose the hover value to be: `field: row` for all values - so if the user passed 6 fields and is plotting with two of them, all six pieces of information show on the hover. I'm not sure if this works for all `data` methods but it's what I would want as an end user
