### ISSUE TITLE
Wrong variable type for "value" 

### ISSUE THREAD

**Issue by ashrith** [h2oai/wave#663]
Shouldn't `value` expect an integer or numeric instead of a character? 

https://github.com/h2oai/wave/blob/983ca29d2b23cfdbf90216a0781b4fe0403d0179/r/R/ui.R#L3231

**Comment by lo5** [comment]
The value has to be formatted by the developer, especially for floating point values. Can also be a format expression for data binding: https://h2oai.github.io/wave/docs/expressions

**Comment by ashrith** [comment]
thank you sir. In case anyone wants to look at this issue and find the answer here is an example
`sample_crypto_price <- as.character(runif(1,1,500))`
Here `sample_crypto_price` is the variable. And it is converted to a `character` with `as.character`
