### ISSUE TITLE
Adapt plot colors to active theme

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#664]
via @shivam5992 

![image](https://user-images.githubusercontent.com/64769322/112282204-2db14d00-8c87-11eb-8c8c-68284151e3d2.png)

Axis titles are hard to see on dark background.

**Comment by vopani** [comment]
It will be useful to have this customizable as an argument (like `x_title_color` or something) apart from improving the default color in dark theme.

**Comment by mturoci** [comment]
@lo5 wdyt about @vopani 's suggestion? Should we add an ability to color titles as well? We don't usually do it for other textual components although it might play well if a dev wants to match the plot color.

**Comment by lo5** [comment]
From the screenshot, it doesn't look like the title is using the foreground color from the theme at all. I'd prefer if that were fixed, instead of allowing customizability, which would be harder to maintain long-term.
