### ISSUE TITLE
Possible to consider to add tooltips for nav_item?

### ISSUE THREAD

**Issue by pramitchoudhary** [h2oai/wave#692]
Is it possible to consider enabling the ability to add tooltips to `nav_items`?
For e.g. for the list below, end-user wants to hover and get a quick description about each item.

<img width="287" alt="Screen Shot 2021-03-26 at 1 28 41 PM" src="https://user-images.githubusercontent.com/1318029/112689902-21b8bd00-8e38-11eb-9d3b-18a1c6c90298.png">

**Comment by lo5** [comment]
@mturoci Maybe there's a quick solution to this - a `title` or `aria-` attribute? I'm not in favor of javascript-tooltips on top of menus.

**Comment by mturoci** [comment]
I would suggest using tooltips only sparsely to provide additional, non-critical contextual description/explanation. Menu items shouldn't require tooltips at all as it should be clear where they lead IMO.

Just checked and `NavItem` accepts `title` attr, so should be easy to implement.
