### ISSUE TITLE
Include more light/dark themes

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#696]
There are currently two themes bundled in. It's super-easy to ship more. Ship at least 10 more for 2021.

**Comment by mturoci** [comment]
@lo5  How do we want to approach this? Should I come up with the themes and we can then review them with @shanaka-rajitha or let @shanaka-rajitha come up with themes and I will implement them after approval?

**Comment by mturoci** [comment]
FYI Added `h2o-dark` theme in 0b03c9cb30d23d50f20697938349bd552caaa656 based on https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/0eaf1110-4f69-40da-9417-3f764032248f/
