### ISSUE TITLE
OIDC not working properly

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#719]
I am attempting to use an external auth provider, and am entering all of the correct parameters when I start the wave server, but no authentication is being done. I am also printing out the user and access token but both imply no auth is happening.
Any additional information on this would be extremely helpful. I have seen a few code examples and I am doing the same as them as well. 

![image](https://user-images.githubusercontent.com/78372056/113343997-25e05100-92f6-11eb-8ced-cbc678b35c71.png)

**Comment by AlexWennerDT** [comment]
I wrote an OIDC Implicit auth flow and it worked when using the same credentials. I would much rather use Wave's OIDC however.

**Comment by lo5** [comment]
@AlexWennerDT - Do you mind providing more details on the `-oidc-` parameters you passed to `waved`?

I just added [some notes on how this can be tested locally](https://github.com/h2oai/wave/blob/master/website/docs/development.md#using-openid-connect) - it'll help to know your particular auth setup and if we need to make changes to Wave or the docs.

**Comment by AlexWennerDT** [comment]
@lo5 of course! I have blocked out the client id and secret for security purposes, but also I will note I am not using Keycloak. I am using an external Authentication provider, but it still OIDC so I assumed  it shouldn't make a difference... maybe it does though. Not sure!
![oidc_wave_params](https://user-images.githubusercontent.com/78372056/113588153-64775380-95f5-11eb-88a2-80fc4ffd50c9.png)

**Comment by AlexWennerDT** [comment]
Figured out my issue, it was a user error! Just an FYI, as expected probably, OIDC in Wave does work with any provider not just Keycloak!
