### ISSUE TITLE
Improve header card 

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#722]
#### Is your feature request related to a problem? Please describe

Many apps use similar features such as user information, searching, alerts, etc. Currently, using individual components like ui.header and ui.section_cards which lacks an integrated feel

#### Describe the solution you'd like

https://xd.adobe.com/view/714ead4b-4020-4ba6-ab95-efdc3a61bb0d-241d/

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/4793561/113809706-8c61d680-971d-11eb-8f4d-6ea1ce4210f9.png">

**Comment by lo5** [comment]
Good idea - this is much needed. 

1. It would be good to refine the design further:
    - The spacing between the hamburger and the icon looks off. 
    - Having both the hamburger and icon together in the above design looks odd.
2. Some (simpler) apps don't have a need for the sidebar menu, so it would be good to have a design variation that includes a horizontal list of links as suggested in #367 #378
3. What does the user menu look like when expanded?

**Comment by sandruparo** [comment]
@shanaka-rajitha  please find the xd link to the above design https://xd.adobe.com/view/714ead4b-4020-4ba6-ab95-efdc3a61bb0d-241d/

**Comment by sandruparo** [comment]
> Good idea - this is much needed.
> 
> 1. It would be good to refine the design further:
>    
>    * The spacing between the hamburger and the icon looks off.
>    * Having both the hamburger and icon together in the above design looks odd.
> 2. Some (simpler) apps don't have a need for the sidebar menu, so it would be good to have a design variation that includes a horizontal list of links as suggested in #367 #378
> 3. What does the user menu look like when expanded?

Thanks @lo5 Prithivi, sure i will see how can i make that improve too.
