### ISSUE TITLE
Wave on Raspberry Pi 4

### ISSUE THREAD

**Issue by fishbigger** [h2oai/wave#724]
#### Wave SDK Version, OS

0.13.0, Linux (Raspbian)

#### Actual behavior

When trying to run `./waved` after downloading the linux release I get `bash: ./waved: cannot execute binary file: Exec format error`. I believe this is because it was compiled for an amd processor whereas a pi uses an arm processor. In [this](https://h2oai.github.io/wave/docs/tutorial-monitor) tutorial it mentions using a raspberry pi making me think its possible for wave to run on it.

#### Expected behavior

Wave server boots up

#### Steps To Reproduce

1. Download the latest linux release on the latest version of raspbian
2. Try and run `./waved` as in the installation instructions
3. See `Exec format error`

**Comment by lo5** [comment]
@fishbigger - correct, the release is for amd64, but you probably want a 32-bit ARM build for Raspbian, which we currently don't ship along with our releases. 

To build it yourself, first [install Go for your platform](https://golang.org/doc/install), then:

```
$ git clone https://github.com/h2oai/wave.git
$ cd wave
$ git checkout tags/v0.13.0 -b v0.13.0
$ GOOS=linux GOARCH=arm go build -o waved cmd/wave/main.go
```

You should now have a `waved` executable for your Pi in the current directory. Just replace the amd64 `waved` with the new one.
