### ISSUE TITLE
Add pagination support to table component

### ISSUE THREAD

**Issue by AlexWennerFHR** [h2oai/wave#730]
Would be a cool feature to have pagination within a table. My use case is specifically pandas, but could see how any table would benefit. I apologize if I this exists and I have missed it, didn't see it in the docs anywhere! Please do let me know if this exists and I am over looking it. Thanks!

**Comment by lo5** [comment]
+1 - we need many more utilities like this.

Blocked by #35

**Comment by lo5** [comment]
**Implementation notes**

One solution would be to expose two new attributes on `Table`:
- a `pagination: Pagination` attribute.
- a `change_page` event (similar to the plot's `select_marks` event).

If `pagination` is set, display a pagination control below the table, and raise the `change_page` event whenever the first, prev, next, last, or jump-to-page links are clicked on. 

The docs can indicate that the author must handle the `change_page` event if `pagination` is set.

The `Pagination` class can have, at a minimum, `rows_per_page` and `trigger_on_scroll` attributes. If `trigger_on_scroll` is set, then no pagination control is required, and the table can raise the `change_page` event when the table is scrolled to a position where a new chunk of rows need to be fetched from the app. Obviously this paginate-on-scroll strategy is not suitable for every use case, but the app author can take the call.

The `change_page` event arg needs to specify what the front-end table needs. An `offset` and `length` should be enough (similar to SQL's offset and length), e.g. `{ offset: 201, length: 25 }` would mean "I need 25 rows starting at row 201".

This pagination strategy isolates the front-end from having to memory-manage large tables, and instead can allow out-of-viewport rows to get GC'd, and re-fetch rows as necessary. Of course there are ways to make this smarter, but the naive strategy should be enough for the first-cut implementation.

**Comment by mturoci** [comment]
According to https://github.com/microsoft/fluentui/issues/14242, it seems like Fluent does not have native support for the proposed `trigger_on_scroll` just yet. For the sake of time, I suggest going with regular pagination support for now, leaving this for the future - cc @lo5 @mtanco
