### ISSUE TITLE
Codecov 3.7.0 backdoor vulnerability

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#750]
Codecov 3.7.0 has had a significant data compromise. Please look into upgrading codecov to the latest patch/deprecating and replacing the package. There is more information here https://about.codecov.io/security-update/

**Comment by AlexWennerDT** [comment]
Please look into rotating/changing any API Keys or other endpoints that this code may have been hitting if possible.

**Comment by lo5** [comment]
Thanks for reporting. 

This is a false positive. We don't use `codecov` in Wave.

**Analysis**

The reference to `"codecov":"^3.7.0"` in `2.32df2173.chunk.js` in the Wave 0.13 release tar is a *build-time* dependency (`devDependencies`) in `vega-tooltip` 0.23.2:
https://github.com/vega/vega-tooltip/blob/c73dc4d0e11c60e0f318510c5317ae81a53d828f/package.json#L62

Wave 0.13.0 has a transitive dependency on `vega-tooltip` 0.23.2 via `vega-embed` 0.23.2.

There is no indication that `codecov` is used/executed at run-time in Wave.

**Next steps**

`codecov` was removed by vega-tooltip in this commit:
https://github.com/vega/vega-tooltip/commit/27156be49085ea966bae83a40cb8231b1db1eb5a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

The latest `vega-embed` uses `vega-tooltip` 0.25.1.

Current Wave `master` reports:
```
$ npm ci
added 143 packages, and audited 144 packages in 2s
found 0 vulnerabilities
```

The presence of the string `"codecov":"^3.7.0"` in the release `.js` will go away once we upgrade to a newer version of ` vega-embed`.

**Comment by AlexWennerDT** [comment]
This is great news. Thank you for the clarification.
