### ISSUE TITLE
Trying to dynamically trend/plot through the ui.dialog component

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#755]
Upon user selection, I am trying to trend specific data in the ui.dialog component. Seems to not break any rules being that ui.dialog can take an 'items' parameter which is where my visuals are specified. It shows the title and no trend as expected. Here below is a sample of the code I am attempting. Let me know if you have any thoughts on how to get this to work. Thanks!

![image](https://user-images.githubusercontent.com/78372056/115588658-95fa4b00-a294-11eb-81a9-76f2b5fda15d.png)

(Excuse the loose bracket near the string interpolation. That wasn't there when the code was executed)

**Comment by AlexWennerDT** [comment]
Seems to be specifically the ui.visualization that is not showing on the dialog!

**Comment by mturoci** [comment]
Hi @AlexWennerDT, thanks for the issue. It seems like this is already fixed in #625, but is not released just yet. Tmp fix until next release is to add any component (e.g. `ui.text('')` to the end of the `items` list. Please let me know if that worked for you.

**Comment by AlexWennerDT** [comment]
Hi @mturoci thanks for the response! I am not sure I fully understand... A quick example (even a one liner) would be incredibly helpful!

**Comment by mturoci** [comment]
Sure, try this sample:
```py
from h2o_wave import main, app, Q, ui, data
from .synth import FakeCategoricalSeries


f = FakeCategoricalSeries()
n = 20


@app('/demo')
async def serve(q: Q):
    if not q.client.initialized:
        q.page['meta'] = ui.meta_card(box='')
        q.page['example'] = ui.form_card(box='1 1 12 10', items=[
            ui.button(name='show_dialog', label='Order donuts', primary=True)
        ])
        q.client.initialized = True
    else:
        if q.args.show_dialog:
            q.page['meta'].dialog = ui.dialog(title='Order Donuts', items=[
                ui.visualization(
                    plot=ui.plot([ui.mark(type='interval', x='=product', y='=price', y_min=0)]),
                    data=data(fields='product price', rows=[(c, x) for c, x, _ in [f.next() for _ in range(n)]], pack=True),
                ),
                ui.text('')  #HACK: Last element is not rendered in wave 0.13 so we need to insert some that we don't care about.
            ])
    await q.page.save()
```
This is edited `meta_dialog.py` example.

**Comment by AlexWennerDT** [comment]
Ah I see, that is interesting that the last element is not rendered. That would explain the pattern of behavior I have been seeing. Thanks a ton for the quick solution! Worked like a charm.
