### ISSUE TITLE
Way to prevent "httpx.ReadTimeout"

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [h2oai/wave#756]
Wave app seems to randomly crash at times. Would  like to get a better understanding on why this is happening so I may be able to come up with a solution on my end. If not, any suggestions on how to prevent this going forward? Plan to productionalize app but having httpx.ReadTimeout would not be an ideal occurence!

**Comment by lo5** [comment]
@AlexWennerDT Do you mind sharing the full stack trace and error message? I don't have any reports of apps crashing that way.

**Comment by AlexWennerDT** [comment]
@lo5 yes of course. Let me try to replicate the crash and I will provide logs!

**Comment by AlexWennerDT** [comment]
![image](https://user-images.githubusercontent.com/78372056/115895283-ddf9a900-a41f-11eb-920f-cbdcec06dbfa.png)
At first I thought this may be because of computation or big data but it really doesn't seem like either. The Action that seemed to trigger this doesn't trigger it every time and it isn't consistent. Nor is that action computationally extensive. If you need more information, would be happy to help anyway I can!

**Comment by lo5** [comment]
It looks like `httpx.ReadTimeout` is thrown when the app is trying to reach the Wave server (when you call `q.page.save()`. This means the Wave server is either unresponsive (rare) or unreachable. Additional information will help: what kind of server is it running on (CPU/memory), how many users are accessing the server, and what is the frequency and amount of data your app is writing to the Wave server (via `q.page.save()`)?

**Comment by AlexWennerDT** [comment]
I am only calling q.pag.save() in my async serve function. This was happening on my local machine running it on local host. Although I did see the same issue occur a few times on an instance that was of type m5d.large. Local host may make sense being that my system may not be the most optimal. There are ~10 users at this point in time that will be accessing the instance on which this is hosted. Would something like a load balancer maybe help running into this in the future? Thanks for the prompt response, glad to get some more clarity around this!

**Comment by mturoci** [comment]
@Alex-Wenner-FHR do you still encounter this issue even with newer Wave versions?

**Comment by mturoci** [comment]
Soft closing. Feel free to reopen in case the issue occurs again.
