### ISSUE TITLE
File Upload is not working in 0.14

### ISSUE THREAD

**Issue by sairaamv** [h2oai/wave#771]
Example file_upload is not working in 0.14 

https://wave.h2o.ai/docs/examples/file-upload

and here is the result

<img width="635" alt="Screenshot 2021-04-29 at 6 00 27 PM" src="https://user-images.githubusercontent.com/41129569/116550927-f59bca80-a914-11eb-9289-9c7e6fe715a3.png">

-- thanks

**Comment by mturoci** [comment]
Thanks for reporting @sairaamv!

@geomodular @lo5 seems like an auth issue:
![image](https://user-images.githubusercontent.com/64769322/116553932-ef005980-a8fa-11eb-8aa5-bd428ba66cf5.png)

**Comment by lo5** [comment]
Thanks for report @sairaamv. Patched in https://github.com/h2oai/wave/releases/tag/v0.14.1
