### ISSUE TITLE
@on handling fails for False / 0 values

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#787]
#### Wave SDK Version, OS
0.14.1, Mac

#### Actual behaviour
The `@on` handling fails for toggles when toggled to `False` (and slider values of 0)

#### Expected behaviour
It should handle the function when toggle is switched off to `False`

#### Steps To reproduce
Any toggle component that is handled with `@on` 
I can provide a full example if helpful, but it is the same issue as the one described here: #168 

#### Comments
I believe `@on` does truth comparison and not an explicit check of not None.

It might be this: https://github.com/h2oai/wave/blob/master/py/h2o_wave/routing.py#L91 (setting this to `elif arg_value is not None:` fixes it locally)

**Comment by vopani** [comment]
@lo5 I did some more checking and this might not be very straightforward after all. It can break other apps.
I have another app that had three buttons. That fails because `handle_on` will now execute the function of the first button in args (even though it might be False) whereas I earlier expected only the True one to get executed.

**Comment by lo5** [comment]
Whoops.

How about introducing a second parameter to `@on()` called `predicate`, which tests the value?

Example:
```
    A function annotated with `@on('foo')` is invoked whenever `q.args['foo']` is found and the value is truthy.
    A function annotated with `@on('foo', lambda x: x is False)` is invoked whenever `q.args['foo']` is False.
    A function annotated with `@on('foo', lambda x: isinstance(x, bool)` is invoked whenever `q.args['foo']` is True or False.
    A function annotated with `@on('foo', lambda x: 42 <= x <= 420)` is invoked whenever `q.args['foo']` between 42 and 420.
```

**Comment by lo5** [comment]
> On a high level, it will always end up executing the first @on function it finds (even if False), which IMO is very unintuitive.
> I'm wondering if it makes sense to execute all matches rather than just the first one?

Agree. I've added the ability to do this. 

See https://github.com/h2oai/wave/blob/master/py/examples/routing_predicates.py

Let me know what you think. Existing apps shouldn't be affected by this change.

**Comment by vopani** [comment]
Yes, this seems like a nice approach. Will test out locally and get back here if there are still some issues.

Thanks a lot!
