### ISSUE TITLE
Dialog is not automatically cleared when closable is True

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#790]
See https://github.com/h2oai/wave/discussions/789 via @vopani 

Setting `closable = True` should clear the dialog from the meta_card's state. Currently, the dialog is marked as dismissed, but it continues to persist in the meta_card.

**Comment by 5675sp** [comment]
I currently have the same problem and I am wondering If I need to update my wave version (I have 0.13.0)? @lo5

**Comment by mturoci** [comment]
Hi @5675sp, this fix is not released yet, will be available with the next wave version (`0.16`).

**Comment by lo5** [comment]
@mturoci Reopening. The fix will only work if the `meta_card` is named `"meta"`. Also, the fix does not check if the dialog is `closable`.

The fix also breaks pattern, in the sense that it's the only component in there that attempts to broadcast its state out-of-band.

I'm thinking that only way to correctly allow app code to deal with `closable` is to raise a `dismissed` event.
