### ISSUE TITLE
Way to dynamically append Items to card?

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#797]
Wondering if there is a way to dynamically append items to a card. Ex: instead of having n ui.form components each with 1 ui.picker, have 1 ui.form component with n ui.pickers. Can provide a visual example if needed!

**Comment by AlexWennerDT** [comment]
Would it be possible to provide an example of what something like this would look like? No persistence on this but would love to see an example if willing!

**Comment by lo5** [comment]
Something like this: 
https://github.com/h2oai/wave/blob/171c13c827fa2fdb55efc50435927e1b07e1b532/py/examples/todo.py#L48-L55

Produces the entire form whenever items need to be add/removed from it.

**Comment by AlexWennerDT** [comment]
Ah I see. Awesome, thank you!
