### ISSUE TITLE
Blank Screen when starting the waved server

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#798]
![image](https://user-images.githubusercontent.com/78372056/117458864-5bd5ae00-af10-11eb-8a2b-71dcdb1b356a.png)
![image](https://user-images.githubusercontent.com/78372056/117458878-5f693500-af10-11eb-91f0-5442c9d800b6.png)
Not sure what is going on here, any thoughts?

**Comment by AlexWennerDT** [comment]
This happens when executing the examples found in the wave sdk as well.

**Comment by AlexWennerDT** [comment]
Yeah that worked! I killed the application and the server a handful of times, and after doing that it just seemed to start working. Not sure if that was a problem on my end or what.

**Comment by lo5** [comment]
Could be because the browser was using an older, cached version of the front-end. I've pushed a fix to improve this behavior. Closing for now.
