### ISSUE TITLE
Graceful way to shutdown and start QD

### ISSUE THREAD

**Issue by surenH2oai** [h2oai/wave#80]
**Is your feature request related to a problem? Please describe.**
We need a graceful way to stop and start QD.  There may be a need to preserve state etc.
**Describe the solution you'd like**
We can do similar to popular other tools/servers,  a script to shutdown and start QD where in the start up script we can pass needed arguments (port,tmp/log location, log-level etc)

**Describe alternatives you've considered**
Documentation of graceful way to shutdown and start QD.
**Additional context**
customer interested in not always running QD but only in certain time windows and automatically shutting it down via cron etc to save on AWS usage.

**Comment by lo5** [comment]
Addressed by checkpointing (v0.13).
