### ISSUE TITLE
Navigation and Side Menu Improvements ( To use as a template ) 

### ISSUE THREAD

**Issue by sandruparo** [h2oai/wave#811]
https://xd.adobe.com/view/05dadb5a-1157-4225-b74b-72e4c355e3cb-5089/

Based on the xd link attached , Shall we think of a way to improve the header and the side navigation ( collapsible ) across all the applications ? We might need to think about a way to improve it, by letting the user to customise the header, side navigation and the body color according to the needs. How can we achieve  this ?

The main points we should think is , 

1. Header 
2. Side nav bar
3. Breadcrumb with the Main Title of the Context 
4. Button ( colors and make buttons with icons, having a 4px border radius )  
5. Body 
6. Color configuration to the header, side nav and the body.  

It would be really great, if we can add the user's name and the picture , notification and setting icon , search bar on the header. ( sample design attached )

![image](https://user-images.githubusercontent.com/9942408/117920567-b1dd9380-b30c-11eb-8cb5-2694ad69c4b1.png)

@lo5 @shanaka-rajitha @mtanco @mturoci @venky74  @surenH2oai @VijithaEkanayake

**Comment by mturoci** [comment]
What about this:
* Header - in addition to our existing header (which includes the left hand side of the design attached), we could add:
     - search - optional
        - label: string displayed when searchbox is empty. [Fluent component](https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox)
        - name: key under which the search value will be submitted. The question is whether we want to manage this as `q.event` or `q.arg`
     - toolbar - optional
        - items - this can be either just buttons or maybe even whatever component - same as `ui.inline`
     - user - optional
        - name
        - title
        - user_img
        - actions: Command[]
* Sidebar - not sure what is suggested here. We use https://developer.microsoft.com/en-us/fluentui#/controls/web/nav.
* Breadcrumb with the Main Title of the Context - maybe enhancing our existing `ui.breadcrumbs_card` would suffice.
* Button ( colors and make buttons with icons, having a 4px border radius ) 
     - as discussed in https://github.com/h2oai/wave/issues/792, we will introduce a new component called badge/chip that will have the `color` and `icon` props.
     - having a 4px border radius - where does `4px` come from? The Fluent uses `2px`, so I guess it would be good to be consistent.
* Body - not sure what is meant by this. In general, colors for background, cards and text are changed altogether via themes.
* Color configuration to the header, side nav and the body - same answer as ^^.

@lo5 wdyt
