### ISSUE TITLE
Message bar visibility doesn't hide component

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#817]
#### Wave SDK Version, OS
v0.15.0 in Chrome on Mac

#### Actual behaviour
`ui.message_bar` with `visible=False` still shows the background.

#### Expected behaviour
It should be hidden completely.

#### Steps to Reproduce
```python
ui.message_bar(type='success', text='Predictions successfully completed!', visible=False)
ui.message_bar(type='success', text='Predictions successfully completed!', visible=True)
```

<img width="269" alt="Screenshot 2021-05-16 at 1 04 23 AM" src="https://user-images.githubusercontent.com/8954217/118375981-e8543080-b5e2-11eb-80a9-ad1eafb643b9.png">

Maybe related to #484 ?

**Comment by mturoci** [comment]
Thanks for the issue @vopani! Correct, this is the same problem as #484 and will be closed in the same PR.
