### ISSUE TITLE
Icon on button is misaligned

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#837]
#### Wave SDK Version, OS
v0.16.0 in Chrome on Mac

#### Actual behaviour
Icons in buttons are not vertically centre-aligned and looks odd.

#### Expected behaviour
Icons and text in a button should be at the same alignment.

#### Steps To Reproduce
<img width="304" alt="Screenshot 2021-05-25 at 6 24 44 PM" src="https://user-images.githubusercontent.com/8954217/119541966-a5e1df00-bdac-11eb-83d0-13071bc820c0.png">

You can see the icon is slightly `above` the text (I can also confirm that the text is correctly centred but the icon is not). It is true for all icons and checked with different texts and they all look weird.

**Comment by mturoci** [comment]
> It is true for all icons

Not sure about this. Take `Search` icon for example:
![image](https://user-images.githubusercontent.com/64769322/119825219-02511580-bef7-11eb-9dbb-b3aece05ce00.png)

The reason some icons are centered and some not depends on how they are clipped. The icon from your example `NavigationBack` has extra bottom space, which causes the visual inconsistence (It appears slightly up). 

![image](https://user-images.githubusercontent.com/64769322/119822266-c10b3680-bef3-11eb-9f44-c9e9ab39a61a.png)

On the other hand, `Search` is clipped perfectly:
![image](https://user-images.githubusercontent.com/64769322/119825419-37f5fe80-bef7-11eb-9afa-41b2b2f6551e.png)
Same goes for `Add`:
![image](https://user-images.githubusercontent.com/64769322/119827479-78ef1280-bef9-11eb-967d-9a8d4c44d3af.png)

I guess there is not much we can do about this.

**Comment by vopani** [comment]
:-(

**Comment by mturoci** [comment]
Seems like this is now possible to fix due to switching to SVG icons instead of font icons.

**Comment by vopani** [comment]
@mturoci Can you share an example here for reference purposes? Thanks!

**Comment by mturoci** [comment]
Sure.

Before
![image](https://user-images.githubusercontent.com/64769322/180381626-d749c745-f5ce-4f86-ae50-98e9813923d0.png)
After
![image](https://user-images.githubusercontent.com/64769322/180381691-6c0e55b4-fd37-4d5e-8e90-946df473ef04.png)

https://github.com/h2oai/wave/issues/837#issuecomment-849600340 still stands as some icons are not cropped properly, making it impossible to achieve centering perfection.
