### ISSUE TITLE
installation__waiting.png is outdated in installation.md

### ISSUE THREAD

**Issue by Nayananga** [h2oai/wave#840]
#### Wave SDK Version, OS

(e.g. 0.16.0, Linux)

#### Actual behavior

After installing and running the wave server locally, opening [http://localhost:10101/](http://localhost:10101/) shows a blinker gif in the browser instead of a spinner mentioned on the installation page.

#### Expected behaviour

Show the blinker gif on the installation page instead of showing outdated spinner png

#### Steps To Reproduce

1. install wave-0.16.0-linux-amd64.tar.gz
2. start wave server
3. open [http://localhost:10101/](http://localhost:10101/)
4. installation page shows a spinner image instead of a blinker gif

![Screenshot from 2021-05-26 22-39-41](https://user-images.githubusercontent.com/25351304/119702650-4c90b300-be73-11eb-816b-77fdfc314ce6.png)

![Screenshot from 2021-05-26 22-40-19](https://user-images.githubusercontent.com/25351304/119702708-616d4680-be73-11eb-894d-ae2fa72ad952.png)

**Comment by lo5** [comment]
Fixed via https://github.com/h2oai/wave/commit/a97df7e0674972a22bd3c019d5231fdc49515adf

**Comment by lo5** [comment]
Thanks for the PR @Nayananga, and welcome!
