### ISSUE TITLE
Handle 'on' for events

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#844]
#### Is your feature request related to a problem? Please describe
The `on` decorator is very useful for `q.args`. If it can also support `q.events`, that'd be great.

#### Describe the solution you'd like
Either `handle_on` to support `q.events` or an equivalent function for events.

#### Additional context
This comes from the fix for #790 leading to a lot more if-else in code.

**Comment by lo5** [comment]
The `@on` handlers now support events. Example:

https://github.com/h2oai/wave/blob/d5686ebc40a22d8a26f30478c484bb7a05ce3f8a/py/examples/plot_events_routing.py#L7-L10

Here `pricing` is the name of the event source (in this case, the plot card) and `select_marks` is the type of event you want to handle.

Complete example:

https://github.com/h2oai/wave/blob/d5686ebc40a22d8a26f30478c484bb7a05ce3f8a/py/examples/plot_events_routing.py#L4-L35

Compare with manually handling events:

https://github.com/h2oai/wave/blob/d5686ebc40a22d8a26f30478c484bb7a05ce3f8a/py/examples/plot_events.py#L27-L29
