### ISSUE TITLE
file_upload component return wrong file path

### ISSUE THREAD

**Issue by Nayananga** [h2oai/wave#845]
#### Wave SDK Version, OS

(e.g. 0.16.0, Linux)

#### Actual behavior

ui.file_upload component returns file path as ```[‘/_f/177b8ca1-dc8a-43ef-9e6d-6eba7bad0e0c/log.csv’]``` but it actually save file into ```/f/177b8ca1-dc8a-43ef-9e6d-6eba7bad0e0c``` in wave sdk folder

#### Expected behavior

ui.file_upload return path is the same as the path it saves files into.
1. Return path as ``/f/177b8ca1-dc8a-43ef-9e6d-6eba7bad0e0c``` or
2. Rename data folder as ```_f``` instead ```f```

#### Steps To Reproduce

1. Run wave tour 
2. Goto Form/File Upload example
3. Print the q.args.<name argument of the ui.file_upload> and observer the \<uuid\>
4. Check-in wave_sdk_path/data/f/\<uuid\> for the file
>Path return by file_upload
![Screenshot from 2021-05-27 21-40-45](https://user-images.githubusercontent.com/25351304/119862072-c1c4bc80-bf35-11eb-9926-c72e0dc73878.png)
>Actual path
![Screenshot from 2021-05-27 21-52-28](https://user-images.githubusercontent.com/25351304/119862168-dacd6d80-bf35-11eb-8b83-2a2320cdb749.png)

**Comment by lo5** [comment]
@Nayananga This is not a bug. The `/_*/` handlers in Wave are special, and has little to do with the way the files are managed on disk. The contents of `/f/*`  are not intended to be manually managed/tampered with.

**Comment by Nayananga** [comment]
@lo5 Thank you for the clarification :)
