### ISSUE TITLE
h2o_wave.core.ServiceError

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#846]
Seeing this error. Attached is the stack trace 
![image](https://user-images.githubusercontent.com/78372056/119882495-18110b80-bef4-11eb-9ba9-3cd67d47c9ac.png)

**Comment by vopani** [comment]
This is a pandas error, your DataFrame `df` most likely is missing the column `reason`.

**Comment by AlexWennerDT** [comment]
Agreed that was likely a pandas issue. I posted the wrong screen grab, my apologies. This is happening when I am changing pages using hash routing.

![image](https://user-images.githubusercontent.com/78372056/119887969-6de8b200-befa-11eb-92f6-fc16b8960364.png)

**Comment by AlexWennerDT** [comment]
This is my serve function... think this potentially is causing the issue. When I route to le_view.
![image](https://user-images.githubusercontent.com/78372056/119889131-d4ba9b00-befb-11eb-9773-905134887776.png)
