### ISSUE TITLE
h2o_wave.core.ServiceError: Request failed (code=500): Internal Server Error

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#849]
I have pinpointed this occurrence. I get this error when I render a table. I have a large dataset so I am rendering the table with 10,000 maximum records. When I do, I get this error. 
![image](https://user-images.githubusercontent.com/78372056/119996154-02532300-bf94-11eb-9a89-eb5ce3d413f8.png)

render_table(q, q.app.anomaly[0].head(10000)) causes this error. While render_table(q, q.app.anomaly[0].head(6000)) does not. I have no issue limiting data shown to 6k records.  render_table() is simply creating a ui.table component and passing a dataframe into it.

**Comment by AlexWennerDT** [comment]
I can work around this with no issue, I just wanted to bring this to attention. Thanks!

**Comment by lo5** [comment]
Requests to the Wave server are limited to 5MB. [See -max-request-size](https://wave.h2o.ai/docs/configuration). 
In general, attempting to display 10K records in a single table in the UI results in poor UX, and may not work at all. It's better to limit the number of records displayed and implement pagination.

**Comment by AlexWennerDT** [comment]
Agreed, pagination is a great solution. Does something like that currently exist for the table rending in Wave?

**Comment by lo5** [comment]
We should probably make it easy to add pagination to a table. You already filed an issue for that: #730 :)

**Comment by AlexWennerDT** [comment]
Completely forgot, thanks!
