### ISSUE TITLE
`ui.image(..)` takes up unexpected amount of space while displaying an image

### ISSUE THREAD

**Issue by AakashKumarNain** [h2oai/wave#854]
#### Wave SDK Version, OS
0.15.0, macOS

(e.g. 4.2.0, Windows)

#### Actual behavior
The displayed image takes extremely large space in a given form card. Check the screenshot below. Also, here is the code for the same

```python
def read_and_encode_image(img_path: str, ext: str = ".png", size=(200, 200)):
    """Reads an image from the disk, save it to a buffer and encode it in base64.

    Arguments:
        img_path: Path to the image on the disk
        ext: Extension of the image file
        size: Resize to the given size
    Returns:
        base64 encoded image buffer
    """

    img = cv2.imread(str(img_path))
    img = cv2.resize(img, size)
    is_success, buffer = cv2.imencode(ext, img)
    if is_success:
        buf = io.BytesIO(buffer)
        buf.seek(0)
        img = base64.b64encode(buf.read()).decode('utf-8')
    return img
```

#### Expected behavior

There should be some way to control the height and the width of the displayed image.

<img width="1182" alt="Screenshot 2021-05-31 at 3 09 34 PM" src="https://user-images.githubusercontent.com/11736571/120181145-46f7ec00-c22a-11eb-84da-04ad01d347d3.png">

**Comment by mturoci** [comment]
The expanding is expected as Wave tries to leave no whitespace and fill all the available space of the card. The immediate solution is to make the containing card smaller.

Possible alternative solutions:
* Introduce `width` & `height` props to allow users control dimensions themselves

wdyt @lo5 ?

Note: The image is blurred as it is too small (200x200) and expand causes the quality to decrease ofc. Using larger image would be better regarding quality.

**Comment by lo5** [comment]
If you want to preserve the original size, you can use `ui.text()` - it supports markdown: https://wave.h2o.ai/docs/examples/text

**Comment by AakashKumarNain** [comment]
Thanks @mturoci and @lo5 for the response. I resolved it. Although I agree that in future versions, we should introduce a `height` and `width` parameter. It would become very handy.
