### ISSUE TITLE
Attempting to use inline script and get error

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#856]
![image](https://user-images.githubusercontent.com/78372056/120241414-4fe7be00-c228-11eb-81d5-1f2d70b60db1.png)
![image](https://user-images.githubusercontent.com/78372056/120241418-51b18180-c228-11eb-95bb-c2bcd55420b7.png)
![image](https://user-images.githubusercontent.com/78372056/120241420-52e2ae80-c228-11eb-8aa0-857ef92efa34.png)

Trying to change the color of table rows on hover using classnames of wave generated elements. Made sure I was running 0.16.0 and I am.

**Comment by lo5** [comment]
What parameters were passed to `ui.inline_script(...)`?

**Comment by AlexWennerDT** [comment]
Just these two!
![image](https://user-images.githubusercontent.com/78372056/120483308-98fa5800-c377-11eb-81e5-65f4fa0ea5eb.png)

**Comment by lo5** [comment]
The script will fail if an HTML element with `id='fmxcu1e'` was not found on the page.

**Comment by AlexWennerDT** [comment]
Does it have to be by ID? I was targeting elements by class.

**Comment by lo5** [comment]
Yes, it's currently by `id`, but we can support classes and selectors as well in the next release.

**Comment by lo5** [comment]
This is fixed. In the next release, you can use a CSS selector like `targets = ['.fmxcu1e']` to check for classes.

**Comment by AlexWennerDT** [comment]
Awesome! Thanks for the efforts!
