### ISSUE TITLE
ML Examples not working

### ISSUE THREAD

**Issue by AlexWennerDT** [h2oai/wave#874]
I get the error displayed in the screenshot when I try to execute any ML examples. I do have the ML Ops .whl downloaded and installed.

![image](https://user-images.githubusercontent.com/78372056/121703843-d3ab7100-ca98-11eb-990b-87d0f75aa069.png)

**Comment by vopani** [comment]
This was a bug in Wave ML v0.8.0

Could you please try upgrading h2o_wave_ml to v0.8.1? It should work without needing the MLOps wheel.
