### ISSUE TITLE
Conda Documentation 

### ISSUE THREAD

**Issue by sairaamv** [h2oai/wave#887]
Just noticed this: 
Shouldn't this be `conda install -c h2oai h2o-wave` rather `conda install -c h2oai h2o_wave` ? 
ref: https://github.com/h2oai/wave/tree/master/py#installing
I see a similar description over here as well. https://anaconda.org/h2oai/h2o-wave 
-- thanks

**Comment by mturoci** [comment]
Resolved by 4d7a3c80fc6eaac83f55b7a10cc5e6592d966ee4
