### ISSUE TITLE
H2O Wave Apps deployment

### ISSUE THREAD

**Issue by rmfjd78** [h2oai/wave#889]
Hi

I'm trying to deploy a wave app in Nginx is it possible? 
How can i specify the IP address of my app and the port number? instead of using localhost:10101?

Best regards,

**Comment by CH3V4L13R** [comment]
@rmfjd78 this is a clear tutorial that would be needed indeed. I was able to make it worked by a combination of those two:
https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-20-04
and
https://docs.gunicorn.org/en/latest/deploy.html#nginx-configuration

Here is the nginx server site configuration file:

server {
    client_max_body_size 4G;

    server_name YOURSITEURL;

    location / {
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      include proxy_params;
      proxy_pass http://127.0.0.1:10101;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/YOURSITEURL/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/YOURSITEURL/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

server {
    if ($host = YOURSITEURL) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;

    server_name YOURSITEURL;
    return 404; # managed by Certbot
}

and the Uvicorn service conf:
WorkingDirectory=/PATH-TO-YOUR-VENV/src
Environment="PATH=/PATH-TO-YOUR-VENV/bin"
ExecStart=/PATH-TO-YOUR-VENV/bin/uvicorn online:main

and the Wave server service conf:
WorkingDirectory=PATH-TO-YOUR-WAVE-SERVER
Environment="PATH=/PATH-TO-YOUR-VENV/bin"
ExecStart=/PATH-TO-YOUR-WAVE-SERVER/waved

You need to change PATH-TO-YOUR-WAVE-SERVER and PATH-TO-YOUR-VENV and YOURSITEURL variables.
The config includes let's encrypt SSL, this config is automatically added when you setup Let's encrypt for your domain. Adjust as necessary. Here is a tutorial to setup let's encrypt with your app:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
Lastly don't forget to make the wave server executable on server, especially good to remember when you upgrade to new versions of the server.

**Comment by rmfjd78** [comment]
Thanks for the help, is there a way to specify the port instead of 10101?

**Comment by CH3V4L13R** [comment]
You probably can just change the port number of the Wave server for that. Then if you want to keep the port number along with the site url when you access your site, you don't need the NGINX proxy_pass. 
https://wave.h2o.ai/docs/configuration

**Comment by rmfjd78** [comment]
I'm having a problem that is i have a server with centos OS and when running waved and uvicorn of my app, the page is not rendering.
And in my local computer everything went well.

**Comment by CH3V4L13R** [comment]
It's difficult to say what is the issue if you don't provide an error code or log about the wave server. You don't think there is any problem about the type of server, either Ubuntu or Centos OS should work.

**Comment by rmfjd78** [comment]
My server description specifications are:
 - CentOS 64 bits
 - H2O_Wave latest version
 - Firefox and chrome both with javascript enabled
 - Without Internet acess

The error that appears in wave is:
<!doctype` html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><link rel="apple-touch-icon" href="/logo192.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Dashboard created using H2O Wave"/><link rel="manifest" href="/manifest.json" crossorigin="use-credentials"/><link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet"><title>H2O Wave</title><link href="/static/css/2.60eec0d8.chunk.css" rel="stylesheet"><link href="/static/css/main.30b2e0f1.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,i,l=r[0],a=r[1],f=r[2],c=0,s=[];c<l.length;c++)i=l[c],Object.prototype.hasOwnProperty.call(o,i)&&o[i]&&s.push(o[i][0]),o[i]=0;for(n in a)Object.prototype.hasOwnProperty.call(a,n)&&(e[n]=a[n]);for(p&&p(r);s.length;)s.shift()();return u.push.apply(u,f||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,l=1;l<t.length;l++){var a=t[l];0!==o[a]&&(n=!1)}n&&(u.splice(r--,1),e=i(i.s=t[0]))}return e}var n={},o={1:0},u=[];function i(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}i.m=e,i.c=n,i.d=function(e,r,t){i.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},i.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},i.t=function(e,r){if(1&r&&(e=i(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(i.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)i.d(t,n,function(r){return e[r]}.bind(null,n));return t},i.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(r,"a",r),r},i.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},i.p="/";var l=this["webpackJsonpwave-ui"]=this["webpackJsonpwave-ui"]||[],a=l.push.bind(l);l.push=r,l=l.slice();for(var f=0;f<l.length;f++)r(l[f]);var p=a;t()}([])</script><script src="/static/js/2.7b41fad7.chunk.js"></script><script src="/static/js/main.c7347f93.chunk.js"></script></body></html>

In my local pc with windows it loads the page

**Comment by rmfjd78** [comment]
is this enough to help me?

**Comment by rmfjd78** [comment]
The problem in CentOS is related with the upload files to use in an HTML

**Comment by CH3V4L13R** [comment]
I confirm your issue on the demo folder of wave. I made a fresh install of Centos and wave and was not able to display the dashboard from the demo folder.
maybe your issue is related to this one: https://github.com/h2oai/wave/issues/189

Kindly note that accessing the same demo app dashboard from a separate machine on the same network worked. (you may need to allow the port access in Centos firewall).
Also the examples folder worked too accessing both from local and separate machine.

Can you confirm you are able to access your wave app from a different machine via yourserverip:10101
Also can you try to run the examples folder apps? like: wave run examples/tour.py

I also tested on my personal app on Centos and it worked.
