### ISSUE TITLE
Side Panel for Configuration

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#898]
#### Is your feature request related to a problem? Please describe
It is common to use an app to configure based on information from the user. Today, this can be done by clicking a button and going to a new page, or by showing a dialog in the center of the page. Going to a new page can remove the end user mentally from the current flow they are working on, and the center dialog mostly blocks out the page the user is on.

#### Describe the solution you'd like
Having a side panel type dialog which would fade the background but allow it to still be seen. 

#### Additional context
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/4793561/124623485-e4010280-de30-11eb-8a9d-7110328580a4.png">

https://xd.adobe.com/view/a1f57a3b-dfdd-4d3c-ab5f-59d404c96593-f4a6/

**Comment by lo5** [comment]
Does the panel have to float 1" from the top, or can it be flush, like [this](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel)?

**Comment by sandruparo** [comment]
@lo5 It would be great if we can bring this on the top of the screen. sometime we blur the background when this overlay comes. I'm fine with either way. Having an overlay is fine.

**Comment by mturoci** [comment]
@lo5 As for API, I guess we go with (same as dialog is implemented):
```jsx
{
// ...inside a meta card
/** Display a side panel on the page. */
side_panel?: SidePanel
}

/** Create a side panel. */
interface SidePanel {
  /** The components in this panel. */
  items: Packed<Component[]>
}
```

**Comment by lo5** [comment]
@mturoci Sounds good!

@sandruparo @mturoci I'm OK with implementing this only if it's a Fluent `Panel`. From the screenshot above, I don't see how it's different from the dialog that we already have.
