### ISSUE TITLE
Scrollbar in tab_card

### ISSUE THREAD

**Issue by vopani** [h2oai/wave#904]
#### Wave SDK Version, OS
v0.16.0 using Mac OS on Chrome

#### Actual behaviour
A scrollbar appears (sometimes, for some users, cannot reproduce) when a tab_card is used in some of the apps.

#### Expected behaviour
The scrollbar should not appear for a tab_card.

@mturoci @geomodular and I saw it in the WaveML app: 
![image](https://user-images.githubusercontent.com/8954217/124880912-684bb500-dfec-11eb-972e-c10a2096f9c3.png)

I also noticed it in another app demo: 
<img width="778" alt="scroll" src="https://user-images.githubusercontent.com/8954217/124881128-9fba6180-dfec-11eb-82a4-3792bce77b9b.png">

@mturoci did try to look into it and suggested a workaround of increasing the height of the zone where the tabs are (which fixes it temporarily) but this issue seems to be constantly appearing in multiple apps so might be good to investigate or increase the default height or maybe just discuss why this might be happening.

cc: @mtanco

**Comment by mtanco** [comment]
@vopani 

🎉 We have figured out how to reproduce this issue - this is an operating system settings specific feature. On OS X you can search for `scrollbar` in preferences

![Kapture 2021-11-10 at 08 36 23](https://user-images.githubusercontent.com/4793561/141155280-68a22889-d144-487f-a050-5e7878075a69.gif)

**Comment by mtanco** [comment]
@mturoci is it worth reopening this issue for the unifying scrollbar color via CSS?

**Comment by mturoci** [comment]
@mtanco I would prefer to open a new one as this one was originally about unwanted scrollbar within tab card, not scrollbars in general.

**Comment by vopani** [comment]
Yes, this was particularly about scrollbar issue within a tab card.
