### ISSUE TITLE
Wave Tour Navigation bar is not working as expected

### ISSUE THREAD

**Issue by dulajra** [h2oai/wave#915]
#### Wave SDK Version, OS

Wave - 0.16.0
OS - Mac OS Big Sur
Browser - Chrome Version 91.0.4472.114  

#### Actual behavior

Nav pane is rest when clicked on an example while the browser search is opened. 

https://user-images.githubusercontent.com/12434380/125587273-68585857-db87-4db2-97f4-ab1a28e35fab.mov

#### Expected behaviour

The selected example should be opened in the Tour app irrespective of the browser search is opened or not.

#### Steps To Reproduce

1. Open the Wave tour app
2. Open the side navigation pane of examples
3. Press Cmd + F and search for a component
4. Click on the search result on the nav pane
5. The Nav pane resets to the top but the clicked example is not opened

**Comment by mturoci** [comment]
Closing since the Tour app has been reworked already and the described flow no longer exists.
