### ISSUE TITLE
handl ui.table interactions in serve

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#920]
#### Is your feature request related to a problem? Please describe
Today, the `ui.table` object handles functionality such as search, filter, and sort automatically. There are times when a user would want to have more direct control on what happens for these events:
* You are displaying a subset of records in the data but want to take the action on all records
   * EX: You have 100K rows but show users the first 100, when they sort by a column you want to use the backend to sort all rows and then return the sorted top 100 to the screen
* You want user analytics on how your data is being interacted with, you want to record what users are searching for or otherwise doing with the data to better prepare for them
    * EX: You see that users are always searching for the same piece of information in the table so you add a new card to the top that explicitly has that info
* You want to save user preferences and give them the same sort / filtered table the next time they come to the app
* You want to want to show secondary information in another card based on how someone interacts with the table   

#### Describe the solution you'd like
The option for all `ui.table` interactions to be handled either automatically or manually by the user with a `serve` function call

**Comment by lo5** [comment]
Related to https://github.com/h2oai/wave/issues/730#issuecomment-988159271

**Comment by mturoci** [comment]
Resolved by https://github.com/h2oai/wave/issues/646.
