### ISSUE TITLE
docs: broken link when clicking on edit this page

### ISSUE THREAD

**Issue by KishaniKandasamy** [h2oai/wave#928]
#### Actual behavior

When I click _edit this page_ in all example apps , they are directed to broken links.I couldn't find the exact github page.
![wave2](https://user-images.githubusercontent.com/53715187/126633100-977b9ba8-5033-4a45-8235-ac8267f38683.jpg)

![wave](https://user-images.githubusercontent.com/53715187/126632942-fa61b00e-db7a-437a-b61e-9c61adb33b34.jpg)

#### Expected behavior

Broken links should be fixed.

**Comment by surenH2oai** [comment]
@KishaniKandasamy  Thanks for the issue.  I am able to reproduce.

**Comment by KishaniKandasamy** [comment]
Great!
