### ISSUE TITLE
Title component

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#940]
via @mtanco 
### Discussed in https://github.com/h2oai/wave/discussions/884

<div type='discussions-op-text'>

<sup>Originally posted by **mtanco** June 20, 2021</sup>
Many apps will combine native Wave objects with 3rd party graphing libraries. It would be nice to have a `ui.title` component which would be similar to one of the `ui.text` component for creating stand-alone titles for plots made outside of wave. 

Here is an example of using just regular `ui.text`:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/4793561/122656914-ca16ae80-d113-11eb-849d-b740388decf6.png">

or bolding the `ui.text`
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/4793561/122656951-09dd9600-d114-11eb-8f22-f8fee28b18ce.png">

</div>

**Comment by lo5** [comment]
I'm not sure I understand the need for this. Cards already have a title, and the text component already supports size variants that provide predefined font size and weight variations.

**Comment by mturoci** [comment]
@mtanco I feel like `ui.text_s(**Your desired title**)` is what you are looking for. Both size and weight should match.

**Comment by mtanco** [comment]
It took six months but... they do not match. You'll notice the center card is a bit less bold than the 1st but more bold than the 3rd:
![image](https://user-images.githubusercontent.com/4793561/155616730-e9958d74-0477-4446-a504-34d69bbfbd11.png)


We can say that we won't update this, but they are different. 


```python
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):

    q.page["form"] = ui.form_card(
        box="1 1 3 1",
        items=[
            ui.text_s("**The quick brown fox jumped over the lazy dog.**")
        ]
    )
    q.page["frame"] = ui.frame_card(
        box="1 2 3 1",
        title="The quick brown fox jumped over the lazy dog.",
        content=" f"
    )
    q.page["form2"] = ui.form_card(
        box="1 3 3 1",
        items=[
            ui.text_s("The quick brown fox jumped over the lazy dog.")
        ]
    )
    await q.page.save()

```

**Comment by mtanco** [comment]
For anyone who might want this - here is how to make your `ui.text()` look like a wave frame or plot title:
`ui.text('<a style="font-size:12px;font-weight:600">Customer Data</a>'),`
