### ISSUE TITLE
Make form card clickable

### ISSUE THREAD

**Issue by dulajra** [h2oai/wave#945]
#### Is your feature request related to a problem? Please describe

Especially when implementing dashboards like user interfaces with Wave we can use `ui.form_card` as dashboard cards. But in most of the use cases, these cards should be clickable such that the user will be directed to a more details page for that particular card. 

#### Describe the solution you'd like

Trigger an event when clicked anywhere on the form card.

**Comment by mturoci** [comment]
@lo5 do we want to do this? I feel like `form_card` is intended to be used for forms which do not need this behavior. This feature could be provided by one of the many new cards in the design proposal.

However, I also understand @dulajra's point since the `form_card` is the most flexible in dev terms.

**Comment by lo5** [comment]
I think it makes sense on some of the cards that display stats or summary information, which the user can then click to get detailed information. The click behavior probably needs to be designed individually for each type of card. For example the small stats cards can be directly clicked on, but the ones that display lists or tables will probably need a link at the bottom.

**Comment by lo5** [comment]
> Trigger an event when clicked anywhere on the form card.

I don't think the form card needs a click behavior, since you already have the ability to include buttons on links inside the card. In any case this will be problematic to implement because the mouse handling will interfere with individual form fields.

**Comment by dulajra** [comment]
> This feature could be provided by one of the many new cards in the design proposal.

@mturoci Yes, I agree with you. But the problem here is currently no such cards are available to use for such use cases. For example, in the model monitoring app, we use a form card with `ui.markup` components to build the UX design prepared by the UX team. For MLOPs also this will be the case. 

@lo5 Yes we can use a button or a button link to open the card. But the problem here is then we cannot implement what is designed by the UX team as it is. For example please refer to [this design](https://xd.adobe.com/view/af608e86-b558-4f9e-bfa1-fbe6aaf40a7c-fa33/).

FYI @iamabhishekmathur @sandruparo @VijithaEkanayake

**Comment by Far0n** [comment]
@dulajra 

The following might not be the cleanest "wavey" app, but does it go into the direction you are looking for?


https://user-images.githubusercontent.com/6949295/128683431-3f839e2a-17ad-4939-af29-1de9a41bf676.mp4



```python
from h2o_wave import main, app, Q, ui, on, handle_on, site
import h2o_wave

on_click_js = r"""
c1 = document.querySelectorAll('[data-test="card1"]')[0];
c2 = document.querySelectorAll('[data-test="card2"]')[0];

c1.onclick = (e) => on_card_click(e, "card1");
c2.onclick = (e) => on_card_click(e, "card2");

function on_card_click(e, val) {
    elementMouseIsOver = document.elementFromPoint(e.clientX, e.clientY);
    background_clicked = elementMouseIsOver.getAttribute("data-test") == val
    wave.emit(val, "background_clicked", background_clicked)
}
"""

@app("/")
async def serve(q: Q):
    print("args", q.args)
    if not q.client.initialized:
        q.page["meta"] = ui.meta_card(box="", redirect="")
        q.client.initialized = True
        await q.page.save()

    q.page["card1"] = ui.form_card(
        box="2 2 2 2",
        title="",
        items=[ui.slider(name="slider1", label="Slider on Card 1", min=0, max=100)],
    )
    q.page["card2"] = ui.form_card(
        box="4 2 2 2",
        title="",
        items=[ui.slider(name="slider2", label="Slider on Card 2", min=0, max=100)],
    )

    if len(str(q.events)) > 0:
        if q.events.card1:
            msg = f"Click registered on card 1, backgound: {q.events.card1.background_clicked} "
        if q.events.card2:
            msg = f"Click registered on card 2, backgound: {q.events.card2.background_clicked} "

        q.page["click_event"] = ui.form_card(
            box="2 1 4 1",
            title="",
            items=[
                ui.text(content=msg),
            ],
        )
    await q.page.save()
    q.page["meta"].script = ui.inline_script(on_click_js)
    await q.page.save()
```

**Comment by mturoci** [comment]
> In any case this will be problematic to implement because the mouse handling will interfere with individual form fields

True, we would have to stop the event bubbling within form elements and prevent them from propagation into form.

@dulajra I see what you are asking for, but note that we cannot just do a "quick tmp" workaround for you until new cards are implemented. We try to keep the API well thought through with zero / minimum breaking changes. So as long as a feature is supposed to serve as a tmp solution, we are probably not going to implement it.

After the new card's design is reviewed and approved, we can prioritize accordingly.

I would suggest using @Far0n 's hack for now.

**Comment by dulajra** [comment]
Thanks @Far0n for the sample code.

**Comment by mturoci** [comment]
Closing as @Far0n 's solution is a good workaround for now.
