### ISSUE TITLE
docs: rendering performance issues in Windows Firefox

### ISSUE THREAD

**Issue by Far0n** [h2oai/wave#946]
The responsiveness of the wave documentation is really poor when browsed with Firefox (v.90.0.2):

https://user-images.githubusercontent.com/6949295/128404224-59e018dd-4ccd-4b63-883f-6677ca7ac2bb.mp4

#### Steps To Reproduce

1. Open https://wave.h2o.ai/docs/getting-started with Firefox
2. Navigate around like shown in the video

**Note:** No such issues with Chrome

**Comment by mturoci** [comment]
Cannot repro, running same FF version.

@Far0n what is your OS? Can you try rebooting your PC maybe?

Anyone else experiencing the issue?

**Comment by Far0n** [comment]
@mturoci windows 10 .. it's also kinda slow for me on other browsers (just not as bad as in Firefox) and I tested on 2 different PC's.
Maybe my internet connection?

**Comment by mturoci** [comment]
Will check on win10.

> Maybe my internet connection?

This only impacts the initial loading time. The problem shown in video is at point when JS is already loaded, it is just janky.

I guess you don't see such behavior on other sites, right? Can you please try some of [these sites](https://docusaurus.io/showcase) if you experience the same problem?

**Comment by Far0n** [comment]
> I guess you don't see such behavior on other sites, right?

That's correct. Wave's docs page is the first where I encountered it. Let me check the sites you posted.

**Comment by Far0n** [comment]
@mturoci btw this is a consistent way to repro for me: visit https://wave.h2o.ai/docs/routing and scroll down fast (right scrollbar).

**Comment by Far0n** [comment]
this here runs fine: https://docusaurus.io/docs

**Comment by mturoci** [comment]
Just checked on win10 FF and works fine. Can try upgrading our static site generator and see if that would help.

**Comment by mturoci** [comment]
Together with @Far0n, we have come to a conclusion that updating Docusaurus resolves the issue. Need to do a QA and regression testing to make sure the update doesn't break anything else.

**Comment by mturoci** [comment]
QA done, no regressions found, updating Docusaurus and closing the issue.

**Comment by lo5** [comment]
@mturoci @Far0n Awesome! Thanks for resolving this.
