### ISSUE TITLE
Location hash is not set when JS events are triggered

### ISSUE THREAD

**Issue by dulajra** [h2oai/wave#954]
#### Wave SDK Version, OS

Wave v0.17.0

#### Actual behavior

Location hash `q.args['#']` is not set when an event is triggered with Javascript and handled with `q.events`.

#### Expected behaviour

Location hash should be set always

#### Steps To Reproduce

1. Create a button click event with markup and JS using `wave.emit` on a page with a hash route.
2. Click on the button.
3. Check the value of `q.args['#']`. It will be `None`

**Comment by lo5** [comment]
Thanks for reporting @dulajra!
