### ISSUE TITLE
Collapsible table

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave#961]
via @sandruparo 

## Design
![image](https://user-images.githubusercontent.com/64769322/129566487-63067f9a-2543-4a31-9a71-a83602496736.png)
[design URL](https://xd.adobe.com/view/eebb600c-026b-4ca1-bb6b-0a439235452b-bbe8/specs/)

## Features
* Ability to collapse / expand a particular row
* Ability to collapse all
* ~~Tags column support~~
* ~~Text color column support~~

Needs discussion: How important is the row collapse / expand icon with the lines design (img below) as opposed to default [Fluent one](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist)? Asking since it is not impossible, but can take more time.

@lo5 I feel like this could be just an extension to our existing `ui.table` component. Wdyt? This way, we could leverage search / sort / filter and even maybe download if that makes sense. The table would display normal / grouped mode based on data provided - either `rows` or a new prop `groups` that would contain `rows` per each group.

**Comment by lo5** [comment]
Yeah, I would stick to the Fluent table in the interest of time, including expand/collapse behavior, in the interest of time. Also, we should do a design review before implementation (for instance, the expand/collapse controls are far too low-contrast - almost invisible to me).

**Comment by mturoci** [comment]
@lo5 there are 2 ways we can tackle this API-wise when integrating to our existing `ui.table` component.

## The Fluent way

The Fluent tackles this via decoupling data rows and groups completely. Each group has to specify a start (`startIndex`) and end index (`count`) so that Fluent knows how many rows should the group span. However, I consider this API to be a bit of mental gymnastics when it comes to real world scenarios. If we take this road, the API would look like

```ts
/**
 * Make rows within table collapsible / expandable.
 *
 * This type of table is best used for cases when your data 
 */
interface Group {
  /** The title of the group. */
  label: S
  /** Index of the first row to be included within this group. */
  start_index: U
  /** Index of the last row to be included within this group. */
  end_index: U
}

export interface Table {
  /** An identifying name for this component. */
  name: Id
  /** The columns in this table. */
  columns: TableColumn[]
  /** The rows in this table. */
  rows: TableRow[]
  /** True to allow multiple rows to be selected. */
  multiple?: B
  /** True to allow group by feature. */
  groupable?: B
  /** Indicates whether the contents of this table can be downloaded and saved as a CSV file. Defaults to False. */
  downloadable?: B
  /** Indicates whether a Reset button should be displayed to reset search / filter / group-by values to their defaults. Defaults to False. */
  resettable?: B
  /** The height of the table, e.g. '400px', '50%', etc. */
  height?: S
  /** The width of the table, e.g. '100px'. Defaults to '100%'. */
  width?: S
  /** The names of the selected rows. If this parameter is set, multiple selections will be allowed (`multiple` is assumed to be `True`). */
  values?: S[]
  /** Controls visibility of table rows when `multiple` is set to `True`. Defaults to 'on-hover'. */
  checkbox_visibility?: 'always' | 'on-hover' | 'hidden'
  /** True if the component should be visible. Defaults to true. */
  visible?: B
  /** An optional tooltip message displayed when a user clicks the help icon to the right of the component. */
  tooltip?: S
  /** Creates collapsible / expandable groups of data rows. */
  groups?: Group[]
}
```

## Alternative

A better alternative from DX perspective would probably be to couple groups with data.

```ts
/**
 * Make rows within table collapsible / expandable.
 *
 * This type of table is best used for cases when your data makes sense to be presented in chunks rather than  a single flat list.
 */
interface Group {
  /** The title of the group. */
  label: S
  /** The rows in this group. */
  rows: TableRow[]
}

export interface Table {
  /** An identifying name for this component. */
  name: Id
  /** The columns in this table. */
  columns: TableColumn[]
  /** The rows in this table. */
  rows: TableRow[]
  /** True to allow multiple rows to be selected. */
  multiple?: B
  /** True to allow group by feature. */
  groupable?: B
  /** Indicates whether the contents of this table can be downloaded and saved as a CSV file. Defaults to False. */
  downloadable?: B
  /** Indicates whether a Reset button should be displayed to reset search / filter / group-by values to their defaults. Defaults to False. */
  resettable?: B
  /** The height of the table, e.g. '400px', '50%', etc. */
  height?: S
  /** The width of the table, e.g. '100px'. Defaults to '100%'. */
  width?: S
  /** The names of the selected rows. If this parameter is set, multiple selections will be allowed (`multiple` is assumed to be `True`). */
  values?: S[]
  /** Controls visibility of table rows when `multiple` is set to `True`. Defaults to 'on-hover'. */
  checkbox_visibility?: 'always' | 'on-hover' | 'hidden'
  /** True if the component should be visible. Defaults to true. */
  visible?: B
  /** An optional tooltip message displayed when a user clicks the help icon to the right of the component. */
  tooltip?: S
  /** Creates collapsible / expandable groups of data rows. Mutually exclusive with `rows` attr. */
  groups?: Group[]
}
```

Note that with this API, the `groups` prop is mutually exclusive with `rows`.

Please, let me know what you think about this ^^.

**Comment by lo5** [comment]
I like the alternative proposal.

> Taking pagination and server-side (#730 #646) of things coming in the future, I feel like decoupling the rows from groups (like Fluent does) is the way to go since it will allow us to have just a single source of truth data-wise.

We can document that groups will be ignored if automatic pagination is turned on. Grouping might not make sense combined with pagination anyway. This way we'll have a more intuitive API in the non-paginated case instead of making grouping painful all the time.
