### ISSUE TITLE
Spinbox `step` has problems with floating-point imprecision

### ISSUE THREAD

**Issue by bminixhofer** [h2oai/wave#966]
#### Wave SDK Version, OS

v0.17.0, Linux

#### Actual behavior

Setting the `step` value of `ui.spinbox` to `0.0001` causes the following issue with floating-point imprecision:

https://user-images.githubusercontent.com/13353204/129863667-f880a2c1-9491-4d65-8889-996c72c6a00b.mp4

#### Expected behavior

I would expect there to be no small floating-point errors shown in the UI.

#### Steps To Reproduce

1. Create a `ui.spinbox` with `step=0.0001` (or smaller).
2. Try increment / decrement in the UI.

I believe possible solutions would be either passing a `Decimal` (or some other higher-precision value) to the `ui.spinbox`, or doing some clever rounding in the UI to avoid showing the imprecision artifacts.

**Comment by mturoci** [comment]
Thanks for catching this @bminixhofer!
