### ISSUE TITLE
New Component: Persona

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#970]
Component for representing a user, often used to show which users do or do not have access to something. This component will often be used inside of `ui.inline`

parameters:
* image - optional
* text - optional (it would be suggested that this is always 2 or less capital letters but we would need to handle developers adding too much text.
![image](https://user-images.githubusercontent.com/4793561/129982534-5d7123f7-da10-4cde-a25a-00c1b38034f0.png)

**Comment by mturoci** [comment]
I suggest going with https://developer.microsoft.com/en-us/fluentui#/controls/web/persona.
Suggested API:
```ts
/** Create a user avatar. */
interface Persona {
  /** Persona image URL or base64 encoded. */
  img?: S
  /** Persona title. */
  title?: S
  /** Persona subtitle. */
  subtitle?: S
  /** Persona caption. */
  caption?: S
  /** Persona size. */
  size?: S
  /** Persona initials. Only works if img is not specified. */
  initials?: S
}
```

Further questions:
* Should the component be clickable?
* ![image](https://user-images.githubusercontent.com/64769322/130034105-5411e049-7f72-4ce3-af8d-8aaa66840dc5.png) This is supposed to be a button I guess. Thanks to #958 we now support icon-only buttons, they are just not rounded. Is there a strong reason for rounding? Adding `rounded` prop to a button is something I would like to avoid as I can foresee app devs using it in inappropriate places making the apps looking funky. Better to have constraints and stick with one style of buttons.
* ![image](https://user-images.githubusercontent.com/64769322/130035324-7072005a-5cf5-4b25-b4bc-77b90c18e296.png) - same reasoning as ^^. IMO a regular text would be fine here.



cc @lo5 for design review

**Comment by mtanco** [comment]
The fluent persona look perfect. 

> Should the component be clickable?
Optionally, I think that the standard functionality for other components of "if there is a name it is clickable, otherwise it is not" would work here.

**Comment by mturoci** [comment]
@lo5 wdyt about the API?

**Comment by lo5** [comment]
```typescript
/** Create an individual's persona or avatar, a visual representation of a person across products. 
  * Can be used to display an individual's avatar (or a composition of the person’s initials on a background color), their name or identification, and online status.
  */
interface Persona {
  /** Primary text, displayed next to the persona coin. */
  title: S
  /** Secondary text, displayed next to the title. */
  subtitle?: S
  /** Tertiary text, displayed next to the subtitle. */
  caption?: S
  /** The size of the persona coin. */
  size?: PersonaSize
  /** Image, URL or base64-encoded. */
  image?: S  
  /** Initials, if `image` is not specified. */
  initials?: S
  /** An identifying name for this component. */
  name?: Id
}
```

Made title mandatory, reordered attributes, added descriptions, changed `img` to `image`.

Note that the compiler now spits out a summary of previously used attribute names. This can be used to verify consistency (e.g. `img` vs `image`).

**Comment by mturoci** [comment]
Thanks @lo5.

> Note that the compiler now spits out a summary of previously used attribute names. This can be used to verify consistency.

Great idea, that will help in future for sure. The printing was probably forgotten though so I added it in https://github.com/h2oai/wave/commit/3a6beebcd32e506ad054bc79463a72a183517592 FYI

**Comment by shihan007** [comment]
<img width="863" alt="Screenshot 2021-09-04 at 12 48 05" src="https://user-images.githubusercontent.com/38729017/132216876-2e2c1a03-9feb-4823-ac36-25f70dca1d61.png">
So we have designed this component based on microsoft web fluent design @mturoci @mtanco. This is how they play facepills and add new user functionality
