### ISSUE TITLE
Date Picker off for 6 weeks

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#988]
#### Wave SDK Version, OS
Wave 0.17.0

#### Actual behavior
When there are "6 weeks" in a month, the `go to today` is cut off
![image](https://user-images.githubusercontent.com/4793561/132768906-16e7cef6-fba4-495c-9368-8f052aacd852.png)

#### Expected behavior
size of the date picker to adjust for edge cases

**Comment by vopani** [comment]
Just for reference based on earlier discussion with @mturoci : Related to https://github.com/microsoft/fluentui/issues/16898

**Comment by tobybaratta** [comment]
+1 to this issue overall. We are still hoping to have this resolved, as "Go to Today" is extremely useful for our customers to actually set the dates that they want simply.

**Comment by ColinKrist** [comment]
This has been around since Jul 2020 for everyone's knowledge - the issue I was following just soft closed today [microsoft/fluentui#13991](https://github.com/microsoft/fluentui/issues/13991)

I wish this would get prioritized as it affects anyone using the date picker for multiple months of every year.

**Comment by mdg357** [comment]
@ColinKrist looks like this might have gotten fixed at some point. Looking at [Microsoft's demo site](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker):

![image](https://user-images.githubusercontent.com/2845121/152618947-06c34d6b-e103-41d0-8bff-48fc2e0ab6e2.png)

**Comment by mturoci** [comment]
@mdg357 is right, I just verified and it works as expected according to the @mtanco's example

![image](https://user-images.githubusercontent.com/64769322/152756354-d4cd3986-79a2-420b-8cb4-301d4f87d13b.png)

Our underlying component framework is updated in master, thus this fix is for now only available in [nightly builds](https://github.com/h2oai/wave/releases/tag/nightly) and will be available in the next (0.21) Wave release.
