### ISSUE TITLE
Website Make Docs doesn't work as is

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#990]
#### Wave SDK Version, OS
Wave 0.17.0: attempting to make the docs locally so that I can live-edit a new blog post. Used a fresh pull of the Wave repo

#### Actual behavior
Was not able to follow [these instructions](https://github.com/h2oai/wave/tree/master/website) for making the docs

#### Expected behavior

(A clear and concise description of what you expected to happen.)

#### Steps To Reproduce
1. Follow the install steps here: https://github.com/h2oai/wave/tree/master/website

```
mtanco@MTanco-MBP15 Desktop % cd wave         
mtanco@MTanco-MBP15 wave % make docs
cd py && /Library/Developer/CommandLineTools/usr/bin/make docs
./venv/bin/pdoc --force  --template-dir docs/templates --output-dir build/docs h2o_wave
make[1]: ./venv/bin/pdoc: No such file or directory
make[1]: *** [docs] Error 1
make: *** [docs] Error 2
```

#### Possible Solution?
I worked around this by changing [this line in the Makefile](https://github.com/h2oai/wave/blob/85bf4f648ebca9e7abdbd38849154522a1dfa42f/py/Makefile#L20) to `docs: setup ## Build API docs` so that I would have a venv, but I'm not positive if this is the right solution for developers who already have run `make setup`

**Comment by mturoci** [comment]
Hi @mtanco, running `make setup` from within `py` folder (which is also part of the main `make` setup` target) should resolve the issue.

Will update the instructions also.
