### ISSUE TITLE
Range slider pick the value doesn't fall into the step size

### ISSUE THREAD

**Issue by VijithaEkanayake** [h2oai/wave#996]
#### Wave SDK Version, OS
0.17.0, MacOS, 0.17.0, Linux

#### Actual behavior
The range slider picks the value that doesn't fall into the step size. 

#### Expected behavior
Values of the range slider should only fall into the step size of the slider.

#### Steps To Reproduce

Use the following code.
```py
from h2o_wave import main, app, Q, ui


@app('/demo')
async def serve(q: Q):
    if q.args.range_slider_step:
        q.page['example1'] = ui.form_card(box='1 1 4 1', items=[
            ui.text(f'range_slider_step={q.args.range_slider_step}')

        ])


    q.page['example'] = ui.form_card(box='1 2 4 4', items=[
        ui.range_slider(name='range_slider_step', label='Step slider 1', min=0, max=1, step=0.01, min_value=0.3,
                        max_value=0.5, trigger=True),

    ])
    await q.page.save()
```

Start wave server and run wave app with above code.
Goto http://localhost:10101/demo
keep adjusting slider right pointers several times
You'll notice it picks odd values like 0.400000000003 by not honoring step size

<img width="589" alt="Screenshot 2021-09-14 at 17 08 06" src="https://user-images.githubusercontent.com/5285626/133253293-53ff23fe-5768-4daa-b440-63e305703311.png">

**Comment by mturoci** [comment]
Closed with #984.
