### ISSUE TITLE
Links don't download when button is True

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave#999]
#### Wave SDK Version, OS
Wave 0.17.0 safari & chrome

#### Actual behavior
When using `ui.link(download=True, button=True)` the file opens in a new tab but is not actually downloaded locally. When `button=False` the file downloads as expected

#### Expected behavior
File to download

**Comment by mturoci** [comment]
Citing [docs](https://wave.h2o.ai/docs/api/ui#link) on `download` attribute:

_True if the link should prompt the user to save the linked URL instead of navigating to it. **Works only if button() is false**._

**Comment by mtanco** [comment]
Would love to know why this is a functionality? A download button seems like a common UI element.

**Comment by lo5** [comment]
@mturoci A button with a download attribute would be useful.

**Comment by mturoci** [comment]
Agree, just wasn't sure if there isn't any nom-obvious reason for this from your side @lo5. The implementation should be a no-brainer, will do.

**Comment by mturoci** [comment]
@mtanco can you please put up a small repro?

I managed to download with a button link like so:
```py
ui.link(
    label='Download link',
    path='https://file-examples-com.github.io/uploads/2017/02/file-sample_100kB.doc',
    download=True,
    button=True
)
```

**Comment by mturoci** [comment]
@Daniel-Kelvich can you add a min repro code please? Thanks!

**Comment by vopani** [comment]
Is there a way to force a download irrespective of format? Or at least open in a new tab?
Was facing a similar issue while using `.json` files.

Particularly because when the file is opened in browser, there is no way to go back to the app without refreshing it (losing saved arguments in the process).

cc: @Nischaydnk

**Comment by mturoci** [comment]
> Or at least open in a new tab?

Yes, this should be possible via `target` attribute.

It seems like I managed to get the download work consistently across browsers. Should be possible in the next release.

**Comment by vopani** [comment]
My use-case is a download through `meta's redirect` : https://github.com/vopani/waveton/blob/main/apps/data_apps/image_annotation/app.py#L284
